libopencm3: GPIO
GPIO
PAC55xx Defines
GPIO definitions for the Qorvo PAC55xx series of microcontrollers.
Modules
GPIO Port IDs
GPIO port base addresses (for convenience)
GPIO Pin Identifiers
GPIO number definitions (for convenience)
GPIO MODE register mapping.
GPIO Mode Register Definitions.
GPIO OUTMASK register mapping.
GPIO Output Mask Register Definitions.
GPIO OUT register mapping.
GPIO Output Register Definitions.
GPIO IN register mapping.
GPIO Input Register Definitions.
GPIO INTEN register mapping.
GPIO Interrupt Enable Register Definitions.
GPIO INTFLAG register mapping.
GPIO Interrupt Flag Register Definitions.
GPIO INTCLEAR register mapping.
GPIO Interrupt Clear Register Definitions.
GPIO INTTYPE register mapping.
GPIO Interrupt Type Register Definitions.
GPIO INTCFG register mapping.
GPIO Interrupt Config Register Definitions.
GPIO INTEDGEBOTH register mapping.
GPIO Interrupt Edge Both Definitions.
GPIO CLKSYNC register mapping.
GPIO Clock Synchronization Settings.
GPIO DOSET register mapping.
GPIO Set Register.
GPIO DOCLEAR register mapping.
GPIO Set Register.
Functions
static uint32_t get_ccs_port_base (uint32_t gpioport)
PAC55xxxx General-Purpose Input/Output (GPIO)
Detailed Description
GPIO definitions for the Qorvo PAC55xx series of microcontrollers.
Author
Brian Viele viels.nosp@m.ter@.nosp@m.alloc.nosp@m.or.t.nosp@m.ech LGPL License Terms libopencm3 License
Date
1 Dec 2019
Definitions in this file come from the PAC55XX Family User Guide Rev 1.21 by Active-Semi dated August 26, 2019.
Function Documentation
get_ccs_port_base()
static uint32_t get_ccs_port_base (uint32_t gpioport) static
PAC55xxxx General-Purpose Input/Output (GPIO)
Author
© 2019 Brian Viele viels.nosp@m.ter@.nosp@m.alloc.nosp@m.or.t.nosp@m.ech
Date
December 1, 2019
This library supports the GPIO module in the PAC55xx SoC from Qorvo.
LGPL License Terms libopencm3 License
Definition at line 29 of file gpio.c.
References CCS_PORTA, CCS_PORTB, CCS_PORTC, CCS_PORTD, CCS_PORTE, CCS_PORTF, CCS_PORTG, GPIOA, GPIOB, GPIOC, GPIOD, GPIOE, GPIOF, and GPIOG.
Referenced by gpio_mode_setup(), gpio_set_af(), gpio_set_output_options(), and gpio_set_schmidt_trigger().