libopencm3: CMU peripheral API
CMU peripheral API
Peripheral APIs
Macros
#define _CMU_REG(i) MMIO32(CMU_BASE + ((i) >> 5))
#define _CMU_BIT(i) (1 << ((i) & 0x1f))
Functions
void cmu_enable_lock (void)
Enable CMU registers lock.
void cmu_disable_lock (void)
Disable CMU registers lock.
bool cmu_get_lock_flag (void)
Get CMU register lock flag.
void cmu_periph_clock_enable (enum cmu_periph_clken clken)
Enable Peripheral Clock in running mode.
void cmu_periph_clock_disable (enum cmu_periph_clken clken)
Disable Peripheral Clock in running mode.
void cmu_osc_on (enum cmu_osc osc)
Turn on Oscillator.
void cmu_osc_off (enum cmu_osc osc)
Turn off Oscillator.
bool cmu_osc_ready_flag (enum cmu_osc osc)
Get Oscillator read flag.
void cmu_wait_for_osc_ready (enum cmu_osc osc)
Wait while oscillator is not ready.
void cmu_set_hfclk_source (enum cmu_osc osc)
Set HFCLK clock source.
enum cmu_osc cmu_get_hfclk_source (void)
Get HFCLK clock source.
void cmu_set_usbclk_source (enum cmu_osc osc)
Set USBCLK clock source.
void cmu_wait_for_usbclk_selected (enum cmu_osc osc)
Wait while USBCLK is not selected.
Detailed Description
Macro Definition Documentation
_CMU_BIT
#define _CMU_BIT (i) (1 << ((i) & 0x1f))
Definition at line 55 of file cmu.c.
_CMU_REG
#define _CMU_REG (i) MMIO32(CMU_BASE + ((i) >> 5))
Definition at line 54 of file cmu.c.
Function Documentation
cmu_disable_lock()
void cmu_disable_lock (void)
Disable CMU registers lock.
Definition at line 39 of file cmu.c.
References CMU_LOCK, and CMU_LOCK_LOCKKEY_UNLOCK.
cmu_enable_lock()
void cmu_enable_lock (void)
Enable CMU registers lock.
Definition at line 31 of file cmu.c.
References CMU_LOCK, and CMU_LOCK_LOCKKEY_LOCK.
cmu_get_hfclk_source()
enum cmu_osc cmu_get_hfclk_source (void)
Get HFCLK clock source.
Return values
enum cmu_osc Oscillator name
Definition at line 251 of file cmu.c.
References CMU_STATUS, CMU_STATUS_HFRCOSEL, CMU_STATUS_HFXOSEL, CMU_STATUS_LFRCOSEL, CMU_STATUS_LFXOSEL, CMU_STATUS_USHFRCODIV2SEL, HFRCO, HFXO, LFRCO, LFXO, and USHFRCODIV2.
cmu_get_lock_flag()
bool cmu_get_lock_flag (void)
Get CMU register lock flag.
Return values
true if flag is set
false if flag is not set
Definition at line 49 of file cmu.c.
References CMU_LOCK, CMU_LOCK_LOCKKEY_LOCKED, and CMU_LOCK_LOCKKEY_MASK.
cmu_osc_off()
void cmu_osc_off (enum cmu_osc osc)
Turn off Oscillator.
Parameters
[in] osc enum cmu_osc Oscillator name
Definition at line 123 of file cmu.c.
References AUXHFRCO, CMU_OSCENCMD, CMU_OSCENCMD_AUXHFRCODIS, CMU_OSCENCMD_HFRCODIS, CMU_OSCENCMD_HFXODIS, CMU_OSCENCMD_LFRCODIS, CMU_OSCENCMD_LFXODIS, CMU_OSCENCMD_USHFRCODIS, HFRCO, HFXO, LFRCO, LFXO, and USHFRCO.
cmu_osc_on()
void cmu_osc_on (enum cmu_osc osc)
Turn on Oscillator.
Parameters
[in] osc enum cmu_osc Oscillator name
Definition at line 92 of file cmu.c.
References AUXHFRCO, CMU_OSCENCMD, CMU_OSCENCMD_AUXHFRCOEN, CMU_OSCENCMD_HFRCOEN, CMU_OSCENCMD_HFXOEN, CMU_OSCENCMD_LFRCOEN, CMU_OSCENCMD_LFXOEN, CMU_OSCENCMD_USHFRCOEN, HFRCO, HFXO, LFRCO, LFXO, and USHFRCO.
Referenced by efm32hg_usbd_init().
cmu_osc_ready_flag()
bool cmu_osc_ready_flag (enum cmu_osc osc)
Get Oscillator read flag.
Parameters
[in] osc enum cmu_osc Oscillator name
Return values
true if flag is set
false if flag is not set
Definition at line 156 of file cmu.c.
References AUXHFRCO, CMU_STATUS, CMU_STATUS_AUXHFRCORDY, CMU_STATUS_HFRCORDY, CMU_STATUS_HFXORDY, CMU_STATUS_LFRCORDY, CMU_STATUS_LFXORDY, CMU_STATUS_USHFRCORDY, HFRCO, HFXO, LFRCO, LFXO, and USHFRCO.
cmu_periph_clock_disable()
void cmu_periph_clock_disable (enum cmu_periph_clken clken)
Disable Peripheral Clock in running mode.
Disable the clock on particular peripheral.
Parameters
[in] clken Peripheral Name
For available constants, see enum::cmu_periph_clken (CMU_LEUART1 for example)
Definition at line 83 of file cmu.c.
References _CMU_REG.
cmu_periph_clock_enable()
void cmu_periph_clock_enable (enum cmu_periph_clken clken)
Enable Peripheral Clock in running mode.
Enable the clock on particular peripheral.
Parameters
[in] clken Peripheral Name
For available constants, see enum::cmu_periph_clken (CMU_LEUART1 for example)
Definition at line 68 of file cmu.c.
References _CMU_BIT, and _CMU_REG.
Referenced by efm32hg_usbd_init().
cmu_set_hfclk_source()
void cmu_set_hfclk_source (enum cmu_osc osc)
Set HFCLK clock source.
Parameters
[in] osc enum cmu_osc Oscillator name
Note
calling cmu_set_hfclk_source() do not set source immediately, use cmu_get_hfclk_source() to verify that the source has been set.
See also
cmu_get_hfclk_source()
Definition at line 223 of file cmu.c.
References CMU_CMD, CMU_CMD_HFCLKSEL_HFRCO, CMU_CMD_HFCLKSEL_HFXO, CMU_CMD_HFCLKSEL_LFRCO, CMU_CMD_HFCLKSEL_LFXO, CMU_CMD_HFCLKSEL_USHFRCODIV2, HFRCO, HFXO, LFRCO, LFXO, and USHFRCODIV2.
cmu_set_usbclk_source()
void cmu_set_usbclk_source (enum cmu_osc osc)
Set USBCLK clock source.
Parameters
osc Oscillator name
Definition at line 274 of file cmu.c.
References CMU_CMD, CMU_CMD_USBCCLKSEL_LFRCO, CMU_CMD_USBCCLKSEL_LFXO, CMU_CMD_USBCCLKSEL_USHFRCO, LFRCO, LFXO, and USHFRCO.
Referenced by efm32hg_usbd_init().
cmu_wait_for_osc_ready()
void cmu_wait_for_osc_ready (enum cmu_osc osc)
Wait while oscillator is not ready.
Parameters
[in] osc enum cmu_osc Oscillator name
Definition at line 189 of file cmu.c.
References AUXHFRCO, CMU_STATUS, CMU_STATUS_AUXHFRCORDY, CMU_STATUS_HFRCORDY, CMU_STATUS_HFXORDY, CMU_STATUS_LFRCORDY, CMU_STATUS_LFXORDY, CMU_STATUS_USHFRCORDY, HFRCO, HFXO, LFRCO, LFXO, and USHFRCO.
Referenced by efm32hg_usbd_init().
cmu_wait_for_usbclk_selected()
void cmu_wait_for_usbclk_selected (enum cmu_osc osc)
Wait while USBCLK is not selected.
Parameters
[in] osc enum cmu_osc Oscillator name
Definition at line 296 of file cmu.c.
References CMU_STATUS, CMU_STATUS_USBCLFRCOSEL, CMU_STATUS_USBCLFXOSEL, CMU_STATUS_USBCUSHFRCOSEL, LFRCO, LFXO, and USHFRCO.
Referenced by efm32hg_usbd_init().