libopencm3: USB peripheral API
USB peripheral API
Peripheral APIs
USB Peripheral for Happy Gecko.
Macros
#define RX_FIFO_SIZE 256
#define ENDPOINT_COUNT 4
Functions
static usbd_device * efm32hg_usbd_init (void)
Initialize the USB device controller hardware of the EFM32HG.
Variables
static struct _usbd_device _usbd_dev
const struct _usbd_driver efm32hg_usb_driver
Detailed Description
USB Peripheral for Happy Gecko.
The Happy Gecko uses the "standard" usb_dwc_otg core.
See also
USB Defines
Copyright
See libopencm3 License
Macro Definition Documentation
ENDPOINT_COUNT
#define ENDPOINT_COUNT 4
Definition at line 49 of file usb_efm32hg.c.
RX_FIFO_SIZE
#define RX_FIFO_SIZE 256
Definition at line 44 of file usb_efm32hg.c.
Function Documentation
efm32hg_usbd_init()
static usbd_device * efm32hg_usbd_init (void) static
Initialize the USB device controller hardware of the EFM32HG.
Definition at line 54 of file usb_efm32hg.c.
References _usbd_dev, CMU_LE, CMU_LFCLKSEL, CMU_LFCLKSEL_LFC_LFRCO, cmu_osc_on(), cmu_periph_clock_enable(), cmu_set_usbclk_source(), CMU_USB, CMU_USBC, CMU_USBCRCTRL, CMU_USBCRCTRL_EN, CMU_USBLE, CMU_USHFRCOCONF, CMU_USHFRCOCONF_BAND_48MHZ, cmu_wait_for_osc_ready(), cmu_wait_for_usbclk_selected(), efm32hg_usb_driver, OTG_DCFG_DSPD, OTG_DIEPMSK_XFRCM, OTG_FS_DAINTMSK, OTG_FS_DCFG, OTG_FS_DCTL, OTG_FS_DIEPMSK, OTG_FS_GAHBCFG, OTG_FS_GINTMSK, OTG_FS_GINTSTS, OTG_FS_GRSTCTL, OTG_FS_GRXFSIZ, OTG_FS_GUSBCFG, OTG_FS_PCGCCTL, OTG_GAHBCFG_GINT, OTG_GINTMSK_ENUMDNEM, OTG_GINTMSK_IEPINT, OTG_GINTMSK_RXFLVLM, OTG_GINTMSK_USBSUSPM, OTG_GINTMSK_WUIM, OTG_GINTSTS_MMIS, OTG_GRSTCTL_AHBIDL, OTG_GRSTCTL_CSRST, OTG_GUSBCFG_FDMOD, OTG_GUSBCFG_TRDT_MASK, USB_CTRL, USB_ROUTE, USB_ROUTE_PHYPEN, and USHFRCO.
Variable Documentation
_usbd_dev
struct _usbd_device _usbd_dev static
Definition at line 51 of file usb_efm32hg.c.
Referenced by efm32hg_usbd_init().
efm32hg_usb_driver
const struct _usbd_driver efm32hg_usb_driver
Initial value:
= {
        .init = efm32hg_usbd_init,
        .set_address = dwc_set_address,
        .ep_setup = dwc_ep_setup,
        .ep_reset = dwc_endpoints_reset,
        .ep_stall_set = dwc_ep_stall_set,
        .ep_stall_get = dwc_ep_stall_get,
        .ep_nak_set = dwc_ep_nak_set,
        .ep_write_packet = dwc_ep_write_packet,
        .ep_read_packet = dwc_ep_read_packet,
        .poll = dwc_poll,
        .disconnect = dwc_disconnect,
        .base_address = USB_OTG_FS_BASE,
        .set_address_before_status = 1,
        .rx_fifo_size = RX_FIFO_SIZE,
}
Definition at line 123 of file usb_efm32hg.c.
Referenced by efm32hg_usbd_init().