libopencm3: usb_standard.c File Reference
usb_standard.c File Reference
#include <string.h>
#include <libopencm3/usb/usbd.h>
#include "usb_private.h"
Functions
int usbd_register_set_config_callback (usbd_device *usbd_dev, usbd_set_config_callback callback)
Registers a "Set Config" callback.
void usbd_register_set_altsetting_callback (usbd_device *usbd_dev, usbd_set_altsetting_callback callback)
Registers a "Set Interface" (alternate setting) callback.
static uint16_t build_config_descriptor (usbd_device *usbd_dev, uint8_t index, uint8_t *buf, uint16_t len)
static int usb_descriptor_type (uint16_t wValue)
static int usb_descriptor_index (uint16_t wValue)
static enum usbd_request_return_codes usb_standard_get_descriptor (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_set_address (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_set_configuration (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_get_configuration (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_set_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_get_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_device_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_interface_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_endpoint_get_status (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_endpoint_stall (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
static enum usbd_request_return_codes usb_standard_endpoint_unstall (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
enum usbd_request_return_codes _usbd_standard_request_device (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
enum usbd_request_return_codes _usbd_standard_request_interface (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
enum usbd_request_return_codes _usbd_standard_request_endpoint (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
enum usbd_request_return_codes _usbd_standard_request (usbd_device *usbd_dev, struct usb_setup_data *req, uint8_t **buf, uint16_t *len)
Function Documentation
_usbd_standard_request()
enum usbd_request_return_codes _usbd_standard_request (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 616 of file usb_standard.c.
References _usbd_standard_request_device(), _usbd_standard_request_endpoint(), _usbd_standard_request_interface(), usb_setup_data::bmRequestType, USB_REQ_TYPE_DEVICE, USB_REQ_TYPE_ENDPOINT, USB_REQ_TYPE_INTERFACE, USB_REQ_TYPE_RECIPIENT, USB_REQ_TYPE_STANDARD, USB_REQ_TYPE_TYPE, usbd_dev, and USBD_REQ_NOTSUPP.
Referenced by usb_control_request_dispatch().
_usbd_standard_request_device()
enum usbd_request_return_codes _usbd_standard_request_device (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 489 of file usb_standard.c.
References usb_setup_data::bRequest, USB_FEAT_DEVICE_REMOTE_WAKEUP, USB_FEAT_TEST_MODE, USB_REQ_CLEAR_FEATURE, USB_REQ_GET_CONFIGURATION, USB_REQ_GET_DESCRIPTOR, USB_REQ_GET_STATUS, USB_REQ_SET_ADDRESS, USB_REQ_SET_CONFIGURATION, USB_REQ_SET_DESCRIPTOR, USB_REQ_SET_FEATURE, usb_standard_device_get_status(), usb_standard_get_configuration(), usb_standard_get_descriptor(), usb_standard_set_address(), usb_standard_set_configuration(), usbd_dev, USBD_REQ_NOTSUPP, and usb_setup_data::wValue.
Referenced by _usbd_standard_request().
_usbd_standard_request_endpoint()
enum usbd_request_return_codes _usbd_standard_request_endpoint (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 577 of file usb_standard.c.
References usb_setup_data::bRequest, USB_FEAT_ENDPOINT_HALT, USB_REQ_CLEAR_FEATURE, USB_REQ_GET_STATUS, USB_REQ_SET_FEATURE, USB_REQ_SET_SYNCH_FRAME, usb_standard_endpoint_get_status(), usb_standard_endpoint_stall(), usb_standard_endpoint_unstall(), usbd_dev, USBD_REQ_NOTSUPP, and usb_setup_data::wValue.
Referenced by _usbd_standard_request().
_usbd_standard_request_interface()
enum usbd_request_return_codes _usbd_standard_request_interface (usbd_device * usbd_dev, struct usb_setup_data * req, uint8_t ** buf, uint16_t * len)
Definition at line 545 of file usb_standard.c.
References usb_setup_data::bRequest, USB_REQ_CLEAR_FEATURE, USB_REQ_GET_INTERFACE, USB_REQ_GET_STATUS, USB_REQ_SET_FEATURE, USB_REQ_SET_INTERFACE, usb_standard_get_interface(), usb_standard_interface_get_status(), usb_standard_set_interface(), usbd_dev, and USBD_REQ_NOTSUPP.
Referenced by _usbd_standard_request().