libopencm3: PHY Generic Drivers
PHY Generic Drivers
Ethernet PHY Generic Drivers
Functions
bool phy_link_isup (uint8_t phy)
Is the link up ?
void phy_reset (uint8_t phy)
Reset the PHY.
Detailed Description
Ethernet PHY Generic Drivers
Version
1.0.0
Author
© 2013 Frantisek Burian BuFra.nosp@m.n@se.nosp@m.znam..nosp@m.cz
Date
1 September 2013
LGPL License Terms libopencm3 License
Function Documentation
phy_link_isup()
bool phy_link_isup (uint8_t phy)
Is the link up ?
Parameters
[in] phy uint8_t phy ID of the PHY
Returns
bool true, if link is up
Definition at line 46 of file phy.c.
References eth_smi_read(), PHY_REG_BSR, and PHY_REG_BSR_UP.
phy_reset()
void phy_reset (uint8_t phy)
Reset the PHY.
Reset the PHY chip and wait for done
Parameters
[in] phy uint8_t phy ID of the PHY
Definition at line 57 of file phy.c.
References eth_smi_read(), eth_smi_write(), PHY_REG_BCR, and PHY_REG_BCR_RESET.
Referenced by eth_init().