libopencm3: usart.c File Reference
usart.c File Reference
#include <libopencm3/lm3s/usart.h>
Functions
void usart_send (uint32_t usart, uint16_t data)
uint16_t usart_recv (uint32_t usart)
void usart_send_blocking (uint32_t usart, uint16_t data)
bool usart_is_recv_ready (uint32_t usart)
bool usart_is_send_ready (uint32_t usart)
uint16_t usart_recv_blocking (uint32_t usart)
void usart_enable_rx_interrupt (uint32_t usart)
void usart_enable_tx_interrupt (uint32_t usart)
void usart_disable_rx_interrupt (uint32_t usart)
void usart_disable_tx_interrupt (uint32_t usart)
void usart_clear_rx_interrupt (uint32_t usart)
void usart_clear_tx_interrupt (uint32_t usart)
bool usart_get_interrupt_source (uint32_t usart, uint32_t flag)
Function Documentation
usart_clear_rx_interrupt()
void usart_clear_rx_interrupt (uint32_t usart)
Definition at line 75 of file usart.c.
References USART_IC, and USART_IC_RX.
usart_clear_tx_interrupt()
void usart_clear_tx_interrupt (uint32_t usart)
Definition at line 80 of file usart.c.
References USART_IC, and USART_IC_TX.
usart_disable_rx_interrupt()
void usart_disable_rx_interrupt (uint32_t usart)
Definition at line 65 of file usart.c.
References USART_IM.
usart_disable_tx_interrupt()
void usart_disable_tx_interrupt (uint32_t usart)
Definition at line 70 of file usart.c.
References USART_IM.
usart_enable_rx_interrupt()
void usart_enable_rx_interrupt (uint32_t usart)
Definition at line 55 of file usart.c.
References USART_IM, and USART_IM_RX.
usart_enable_tx_interrupt()
void usart_enable_tx_interrupt (uint32_t usart)
Definition at line 60 of file usart.c.
References USART_IM, and USART_IM_TX.
usart_get_interrupt_source()
bool usart_get_interrupt_source (uint32_t usart, uint32_t flag)
Definition at line 85 of file usart.c.
References USART_RIS.
usart_is_recv_ready()
bool usart_is_recv_ready (uint32_t usart)
Definition at line 39 of file usart.c.
References USART_FR, and USART_FR_RXFE.
Referenced by usart_recv_blocking().
usart_is_send_ready()
bool usart_is_send_ready (uint32_t usart)
Definition at line 44 of file usart.c.
References USART_FR, and USART_FR_BUSY.
Referenced by usart_send_blocking().
usart_recv()
uint16_t usart_recv (uint32_t usart)
Definition at line 28 of file usart.c.
References USART_DR.
Referenced by usart_recv_blocking().
usart_recv_blocking()
uint16_t usart_recv_blocking (uint32_t usart)
Definition at line 49 of file usart.c.
References usart_is_recv_ready(), and usart_recv().
usart_send()
void usart_send (uint32_t usart, uint16_t data)
Definition at line 23 of file usart.c.
References USART_DR.
Referenced by usart_send_blocking().
usart_send_blocking()
void usart_send_blocking (uint32_t usart, uint16_t data)
Definition at line 33 of file usart.c.
References usart_is_send_ready(), and usart_send().