libopencm3: fdcan.c File Reference
fdcan.c File Reference
#include <libopencm3/stm32/fdcan.h>
#include <libopencm3/stm32/rcc.h>
#include <stddef.h>
Functions
static int fdcan_cccr_init_cfg (uint32_t canport, bool set, uint32_t timeout)
Routine implementing FDCAN_CCCR's INIT bit manipulation.
static int fdcan_get_free_txbuf (uint32_t canport)
Return ID of next free Tx buffer.
static void fdcan_get_fill_rxfifo (uint32_t canport, uint8_t fifo_id, unsigned *get_index, unsigned *pending_frames)
Returns fill state and next available get index from receive FIFO.
static struct fdcan_message_ram * fdcan_get_msgram_addr (uint32_t canport)
Obtain address of FDCAN Message RAM for certain FDCAN block.
static uint32_t fdcan_length_to_dlc (uint8_t length)
Converts frame length to DLC value.
static uint8_t fdcan_dlc_to_length (uint32_t dlc)
Converts DLC value into frame payload length.
int fdcan_init (uint32_t canport, uint32_t timeout)
Put FDCAN block into INIT mode for setup.
void fdcan_set_can (uint32_t canport, bool auto_retry_disable, bool rx_fifo_locked, bool tx_queue_mode, bool silent, uint32_t n_sjw, uint32_t n_ts1, uint32_t n_ts2, uint32_t n_br_presc)
Set essential FDCAN block parameters for plain CAN operation.
void fdcan_set_fdcan (uint32_t canport, bool brs_enable, bool fd_op_enable, uint32_t f_sjw, uint32_t f_ts1, uint32_t f_ts2, uint32_t f_br_presc)
Set FDCAN block parameters for FDCAN transmission.
void fdcan_set_test (uint32_t canport, bool testing, bool loopback)
Set FDCAN block testing features.
int fdcan_start (uint32_t canport, uint32_t timeout)
Enable FDCAN operation after FDCAN block has been set up.
int fdcan_get_init_state (uint32_t canport)
Return current FDCAN block operation state.
void fdcan_init_filter (uint32_t canport, uint8_t std_filt, uint8_t ext_filt)
Configure amount of filters and initialize filtering block.
void fdcan_set_std_filter (uint32_t canport, uint32_t nr, uint8_t id_list_mode, uint32_t id1, uint32_t id2, uint8_t action)
Configure filter rule for standard ID frames.
void fdcan_set_ext_filter (uint32_t canport, uint32_t nr, uint8_t id_list_mode, uint32_t id1, uint32_t id2, uint8_t action)
Configure filter rule for extended ID frames.
int fdcan_transmit (uint32_t canport, uint32_t id, bool ext, bool rtr, bool fdcan_fmt, bool btr_switch, uint8_t length, const uint8_t *data)
Transmit Message using FDCAN.
int fdcan_receive (uint32_t canport, uint8_t fifo_id, bool release, uint32_t *id, bool *ext, bool *rtr, uint8_t *fmi, uint8_t *length, uint8_t *data, uint16_t *timestamp)
Receive Message from FDCAN FIFO.
void fdcan_release_fifo (uint32_t canport, uint8_t fifo_id)
Release receive oldest FIFO entry.
void fdcan_enable_irq (uint32_t canport, uint32_t irq)
Enable IRQ from FDCAN block.
void fdcan_disable_irq (uint32_t canport, uint32_t irq)
Disable IRQ from FDCAN block.
bool fdcan_available_tx (uint32_t canport)
Check if there is free transmit buffer.
bool fdcan_available_rx (uint32_t canport, uint8_t fifo)
Tell if there is message waiting in receive FIFO.
Function Documentation
fdcan_cccr_init_cfg()
static int fdcan_cccr_init_cfg (uint32_t canport, bool set, uint32_t timeout) static
Routine implementing FDCAN_CCCR's INIT bit manipulation.
This routine will change INIT bit and wait for it to actually change its value. If change won't happen before timeout, error is signalized. If INIT bit already has value which should be set, this function will return immediately.
Parameters
[in] canport FDCAN block base address. See FDCAN block base addresses.
[in] set new value of INIT, true means set
[in] timeout Amount of busyloop cycles, function will wait for FDCAN to switch it's state. If set to 0, then function returns immediately.
Returns
FDCAN_E_OK on success, FDCAN_E_TIMEOUT if INIT bit value didn't change before timeout has expired.
Definition at line 60 of file fdcan.c.
References FDCAN_CCCR, FDCAN_CCCR_INIT, FDCAN_E_OK, and FDCAN_E_TIMEOUT.
Referenced by fdcan_init(), and fdcan_start().
fdcan_dlc_to_length()
static uint8_t fdcan_dlc_to_length (uint32_t dlc) static
Converts DLC value into frame payload length.
Works for both CAN and FDCAN DLC values.
Parameters
[in] dlc DLC value
Returns
data payload length in bytes
Definition at line 210 of file fdcan.c.
Referenced by fdcan_receive().
fdcan_get_fill_rxfifo()
static void fdcan_get_fill_rxfifo (uint32_t canport, uint8_t fifo_id, unsigned * get_index, unsigned * pending_frames) static
Returns fill state and next available get index from receive FIFO.
Examines FDCAN receive FIFO and returns fill status of FIFO and ID of next message available for reading. If fill status is 0 (FIFO is empty), then get index is undefined.
Parameters
[in] canport FDCAN block base address. See FDCAN block base addresses.
[in] fifo_id ID of fifo queried (currently 0 or 1)
[out] get_index Address of buffer where next get index will be stored
[out] pending_frames Address of buffer where amount of pending frame will be stored.
Definition at line 128 of file fdcan.c.
References FDCAN_RXFIFO_FL_MASK, FDCAN_RXFIFO_FL_SHIFT, FDCAN_RXFIFO_GI_MASK, FDCAN_RXFIFO_GI_SHIFT, and FDCAN_RXFIS.
Referenced by fdcan_receive().
fdcan_get_free_txbuf()
static int fdcan_get_free_txbuf (uint32_t canport) static
Return ID of next free Tx buffer.
Examines transmit buffer allocation in message RAM and returns ID of buffer, which is free.
Parameters
[in] canport FDCAN block base address. See FDCAN block base addresses.
Returns
Non-negative number ID of Tx buffer which is free, or FDCAN_E_BUSY if no Tx buffer is available
Definition at line 104 of file fdcan.c.
References FDCAN_E_BUSY, FDCAN_TXBRP, FDCAN_TXBRP_TRP0, FDCAN_TXBRP_TRP1, and FDCAN_TXBRP_TRP2.
Referenced by fdcan_available_tx(), and fdcan_transmit().
fdcan_get_msgram_addr()
static struct fdcan_message_ram* fdcan_get_msgram_addr (uint32_t canport) static
Obtain address of FDCAN Message RAM for certain FDCAN block.
Parameters
[in] canport identification of FDCAN block. See FDCAN block base addresses.
Returns
Address of Message RAM for given FDCAN block or null pointer if FDCAN block identification is invalid.
Definition at line 144 of file fdcan.c.
References CAN1, CAN2, CAN3, and FDCAN1_RAM_BASE.
Referenced by fdcan_init_filter(), fdcan_receive(), fdcan_set_ext_filter(), fdcan_set_std_filter(), and fdcan_transmit().
fdcan_length_to_dlc()
static uint32_t fdcan_length_to_dlc (uint8_t length) static
Converts frame length to DLC value.
Works for both CAN and FDCAN frame lengths. If length is invalid value, then returns 0xFF.
Parameters
[in] length intended frame payload length in bytes
Returns
DLC value representing lengths or 0xFF if length cannot be encoded into DLC format (applies only to FDCAN frame lengths)
Definition at line 186 of file fdcan.c.
Referenced by fdcan_transmit().