libopencm3: DMAMUX Defines
DMAMUX Defines
STM32G4xx Defines
Defined Constants and Types for the STM32G4xx DMAMUX.
Modules
DMAMUX register base addresses
SYNCID Synchronization input selected
DMAREQID DMA request line selected
SIGID DMA request trigger input selected
CxCR DMA request line multiplexer channel x control register
CSR request line multiplexer interrupt channel status register
CFR request line multiplexer interrupt clear flag register
RGxCR DMA request generator channel x control register
RGSR DMA request generator interrupt status register
RGCFR DMA request generator clear flag register
DMAMUX Request Generator Channel Number
Macros
#define DMAMUX_CxCR(dmamux_base, dma_channel) MMIO32((dmamux_base) + 0x04 * ((dma_channel) - 1))
#define DMAMUX1_CxCR(dma_channel) DMAMUX_CxCR(DMAMUX1, (dma_channel))
#define DMAMUX2_CxCR(dma_channel) DMAMUX_CxCR(DMAMUX2, (dma_channel))
#define DMAMUX_CSR(dmamux_base) MMIO32((dmamux_base) + 0x80)
#define DMAMUX1_CSR DMAMUX_CSR(DMAMUX1)
#define DMAMUX2_CSR DMAMUX_CSR(DMAMUX2)
#define DMAMUX_CFR(dmamux_base) MMIO32((dmamux_base) + 0x84)
#define DMAMUX1_CFR DMAMUX_CFR(DMAMUX1)
#define DMAMUX2_CFR DMAMUX_CFR(DMAMUX2)
#define DMAMUX_RGxCR(dmamux_base, rg_channel) MMIO32((dmamux_base) + 0x100 + 0x04 * ((rg_channel) - 1))
#define DMAMUX1_RGxCR(rg_channel) DMAMUX_RGxCR(DMAMUX1, (rg_channel))
#define DMAMUX2_RGxCR(rg_channel) DMAMUX_RGxCR(DMAMUX2, (rg_channel))
#define DMAMUX_RGSR(dmamux_base) MMIO32((dmamux_base) + 0x140)
#define DMAMUX1_RGSR DMAMUX_RSGR(DMAMUX1)
#define DMAMUX2_RGSR DMAMUX_RSGR(DMAMUX2)
#define DMAMUX_RGCFR(dmamux_base) MMIO32((dmamux_base) + 0x144)
#define DMAMUX1_RGCFR DMAMUX_RGCFR(DMAMUX1)
#define DMAMUX2_RGCFR DMAMUX_RGCFR(DMAMUX2)
Functions
void dmamux_reset_dma_channel (uint32_t dmamux, uint8_t channel)
DMAMUX Reset DMA Channel.
void dmamux_enable_dma_request_event_generation (uint32_t dmamux, uint8_t channel)
DMAMUX Enable DMA Request Event Generation.
void dmamux_disable_dma_request_event_generation (uint32_t dmamux, uint8_t channel)
DMAMUX Disable DMA Request Event Generation.
void dmamux_set_dma_channel_request (uint32_t dmamux, uint8_t channel, uint8_t request_id)
DMAMUX Set DMA Channel Request.
uint8_t dmamux_get_dma_channel_request (uint32_t dmamux, uint8_t channel)
DMAMUX Get DMA Channel Request Selection.
void dmamux_enable_dma_request_sync (uint32_t dmamux, uint8_t channel)
DMAMUX Enable DMA Request Synchronization.
void dmamux_disable_dma_request_sync (uint32_t dmamux, uint8_t channel)
DMAMUX Disable DMA Request Synchronization.
void dmamux_set_dma_request_sync_input (uint32_t dmamux, uint8_t channel, uint8_t sync_id)
DMAMUX Set DMA Request Synchronization Input.
void dmamux_set_dma_request_sync_pol (uint32_t dmamux, uint8_t channel, uint8_t polarity)
DMAMUX Set DMA Request Synchronization Event Polarity.
void dmamux_set_dma_request_sync_nbreq (uint32_t dmamux, uint8_t channel, uint8_t nbreq)
DMAMUX Set DMA Request NBREQ To Forward.
void dmamux_enable_dma_request_sync_overrun_interrupt (uint32_t dmamux, uint8_t channel)
DMAMUX Enable DMA Request Overrun Interrupt.
void dmamux_disable_dma_request_sync_overrun_interrupt (uint32_t dmamux, uint8_t channel)
DMAMUX Disable DMA Request Overrun Interrupt.
uint32_t dmamux_get_dma_request_sync_overrun (uint32_t dmamux, uint8_t channel)
DMAMUX Get DMA Request Synchronization Overrun Interrupt Flag.
void dmamux_clear_dma_request_sync_overrun (uint32_t dmamux, uint8_t channel)
DMAMUX Clear DMA Request Synchronization Overrun Interrupt Flag.
void dmamux_reset_request_generator_channel (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Reset Request Generator Channel.
void dmamux_enable_request_generator (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Enable Request Generator Channel.
void dmamux_disable_request_generator (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Disable Request Generator Channel.
void dmamux_set_request_generator_trigger (uint32_t dmamux, uint8_t rg_channel, uint8_t sig_id)
DMAMUX Set Request Generator Input Trigger Signal.
void dmamux_set_request_generator_trigger_pol (uint32_t dmamux, uint8_t rg_channel, uint8_t polarity)
DMAMUX Set Request Generator Trigger Polarity.
void dmamux_set_request_generator_trigger_gnbreq (uint32_t dmamux, uint8_t rg_channel, uint8_t gnbreq)
DMAMUX Set Request Generator Trigger GNBREQ.
void dmamux_enable_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Enable Request Generator Trigger Overrun Interrupt.
void dmamux_disable_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Disable Request Generator Trigger Overrun Interrupt.
uint32_t dmamux_get_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Get Request Generator Trigger Overrun Interrupt Flag.
void dmamux_clear_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Clear Request Generator Trigger Overrun Interrupt Flag.
Detailed Description
Defined Constants and Types for the STM32G4xx DMAMUX.
Version
1.0.0
LGPL License Terms libopencm3 License
Author
© 2019 Guillaume Revaillot g.rev.nosp@m.aill.nosp@m.ot@gm.nosp@m.ail..nosp@m.com
Version
1.0.0
LGPL License Terms libopencm3 License
Macro Definition Documentation
DMAMUX1_CFR
#define DMAMUX1_CFR DMAMUX_CFR(DMAMUX1)
Definition at line 41 of file dmamux_common_all.h.
DMAMUX1_CSR
#define DMAMUX1_CSR DMAMUX_CSR(DMAMUX1)
Definition at line 37 of file dmamux_common_all.h.
DMAMUX1_CxCR
#define DMAMUX1_CxCR (dma_channel) DMAMUX_CxCR(DMAMUX1, (dma_channel))
Definition at line 33 of file dmamux_common_all.h.
DMAMUX1_RGCFR
#define DMAMUX1_RGCFR DMAMUX_RGCFR(DMAMUX1)
Definition at line 53 of file dmamux_common_all.h.
DMAMUX1_RGSR
#define DMAMUX1_RGSR DMAMUX_RSGR(DMAMUX1)
Definition at line 49 of file dmamux_common_all.h.
DMAMUX1_RGxCR
#define DMAMUX1_RGxCR (rg_channel) DMAMUX_RGxCR(DMAMUX1, (rg_channel))
Definition at line 45 of file dmamux_common_all.h.
DMAMUX2_CFR
#define DMAMUX2_CFR DMAMUX_CFR(DMAMUX2)
Definition at line 42 of file dmamux_common_all.h.
DMAMUX2_CSR
#define DMAMUX2_CSR DMAMUX_CSR(DMAMUX2)
Definition at line 38 of file dmamux_common_all.h.
DMAMUX2_CxCR
#define DMAMUX2_CxCR (dma_channel) DMAMUX_CxCR(DMAMUX2, (dma_channel))
Definition at line 34 of file dmamux_common_all.h.
DMAMUX2_RGCFR
#define DMAMUX2_RGCFR DMAMUX_RGCFR(DMAMUX2)
Definition at line 54 of file dmamux_common_all.h.
DMAMUX2_RGSR
#define DMAMUX2_RGSR DMAMUX_RSGR(DMAMUX2)
Definition at line 50 of file dmamux_common_all.h.
DMAMUX2_RGxCR
#define DMAMUX2_RGxCR (rg_channel) DMAMUX_RGxCR(DMAMUX2, (rg_channel))
Definition at line 46 of file dmamux_common_all.h.
DMAMUX_CFR
#define DMAMUX_CFR (dmamux_base) MMIO32((dmamux_base) + 0x84)
Definition at line 40 of file dmamux_common_all.h.
DMAMUX_CSR
#define DMAMUX_CSR (dmamux_base) MMIO32((dmamux_base) + 0x80)
Definition at line 36 of file dmamux_common_all.h.
DMAMUX_CxCR
#define DMAMUX_CxCR (dmamux_base, dma_channel) MMIO32((dmamux_base) + 0x04 * ((dma_channel) - 1))
Definition at line 32 of file dmamux_common_all.h.
DMAMUX_RGCFR
#define DMAMUX_RGCFR (dmamux_base) MMIO32((dmamux_base) + 0x144)
Definition at line 52 of file dmamux_common_all.h.
DMAMUX_RGSR
#define DMAMUX_RGSR (dmamux_base) MMIO32((dmamux_base) + 0x140)
Definition at line 48 of file dmamux_common_all.h.
DMAMUX_RGxCR
#define DMAMUX_RGxCR (dmamux_base, rg_channel) MMIO32((dmamux_base) + 0x100 + 0x04 * ((rg_channel) - 1))
Definition at line 44 of file dmamux_common_all.h.
Function Documentation
dmamux_clear_dma_request_sync_overrun()
void dmamux_clear_dma_request_sync_overrun (uint32_t dmamux, uint8_t channel)
DMAMUX Clear DMA Request Synchronization Overrun Interrupt Flag.
Clear DMA Request Synchronization Overrun Interrupt for given DMA channel
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 219 of file dmamux.c.
References DMAMUX_CFR, and DMAMUX_CFR_CSOF.
Referenced by dmamux_reset_dma_channel().
dmamux_clear_request_generator_trigger_overrun_interrupt()
void dmamux_clear_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Clear Request Generator Trigger Overrun Interrupt Flag.
Clear DMA Request Synchronization Overrun Interrupt Flag for given Request Generator Channel
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
Definition at line 361 of file dmamux.c.
References DMAMUX_RGCFR, and DMAMUX_RGCFR_COF.
Referenced by dmamux_reset_request_generator_channel().
dmamux_disable_dma_request_event_generation()
void dmamux_disable_dma_request_event_generation (uint32_t dmamux, uint8_t channel)
DMAMUX Disable DMA Request Event Generation.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 90 of file dmamux.c.
References DMAMUX_CxCR.
dmamux_disable_dma_request_sync()
void dmamux_disable_dma_request_sync (uint32_t dmamux, uint8_t channel)
DMAMUX Disable DMA Request Synchronization.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 152 of file dmamux.c.
References DMAMUX_CxCR.
dmamux_disable_dma_request_sync_overrun_interrupt()
void dmamux_disable_dma_request_sync_overrun_interrupt (uint32_t dmamux, uint8_t channel)
DMAMUX Disable DMA Request Overrun Interrupt.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 192 of file dmamux.c.
References DMAMUX_CxCR.
dmamux_disable_request_generator()
void dmamux_disable_request_generator (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Disable Request Generator Channel.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
Definition at line 258 of file dmamux.c.
References DMAMUX_RGxCR.
dmamux_disable_request_generator_trigger_overrun_interrupt()
void dmamux_disable_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Disable Request Generator Trigger Overrun Interrupt.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
Definition at line 333 of file dmamux.c.
References DMAMUX_RGxCR.
dmamux_enable_dma_request_event_generation()
void dmamux_enable_dma_request_event_generation (uint32_t dmamux, uint8_t channel)
DMAMUX Enable DMA Request Event Generation.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 79 of file dmamux.c.
References DMAMUX_CxCR, and DMAMUX_CxCR_EGE.
dmamux_enable_dma_request_sync()
void dmamux_enable_dma_request_sync (uint32_t dmamux, uint8_t channel)
DMAMUX Enable DMA Request Synchronization.
Enable DMAMUX request synchronization for a given DMA channel, propagating DMA request when configured event edge (DMAREQ_CxCR_SPOL) is detected on previously selected synchronization trigger input id.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 141 of file dmamux.c.
References DMAMUX_CxCR, and DMAMUX_CxCR_SE.
dmamux_enable_dma_request_sync_overrun_interrupt()
void dmamux_enable_dma_request_sync_overrun_interrupt (uint32_t dmamux, uint8_t channel)
DMAMUX Enable DMA Request Overrun Interrupt.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 181 of file dmamux.c.
References DMAMUX_CxCR, and DMAMUX_CxCR_SOIE.
dmamux_enable_request_generator()
void dmamux_enable_request_generator (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Enable Request Generator Channel.
Enable Request Generator Channel, Producting DMA Request on input signal trigger. These Requests are usable by the DMA Request Router.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
Definition at line 247 of file dmamux.c.
References DMAMUX_RGxCR, and DMAMUX_RGxCR_GE.
dmamux_enable_request_generator_trigger_overrun_interrupt()
void dmamux_enable_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Enable Request Generator Trigger Overrun Interrupt.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
Definition at line 322 of file dmamux.c.
References DMAMUX_RGxCR, and DMAMUX_RGxCR_OIE.
dmamux_get_dma_channel_request()
uint8_t dmamux_get_dma_channel_request (uint32_t dmamux, uint8_t channel)
DMAMUX Get DMA Channel Request Selection.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Returns
DMA request (DMAREQID DMA request line selected)
Definition at line 68 of file dmamux.c.
References DMAMUX_CxCR, DMAMUX_CxCR_DMAREQ_ID_MASK, and DMAMUX_CxCR_DMAREQ_ID_SHIFT.
dmamux_get_dma_request_sync_overrun()
uint32_t dmamux_get_dma_request_sync_overrun (uint32_t dmamux, uint8_t channel)
DMAMUX Get DMA Request Synchronization Overrun Interrupt Flag.
Get DMA Request Synchronization Overrun Interrupt for given DMA channel
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Returns
DMA Channel Synchronization Overrun Interrupt Flag
Definition at line 206 of file dmamux.c.
References DMAMUX_CSR, and DMAMUX_CSR_SOF.
dmamux_get_request_generator_trigger_overrun_interrupt()
uint32_t dmamux_get_request_generator_trigger_overrun_interrupt (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Get Request Generator Trigger Overrun Interrupt Flag.
Get DMA Request Synchronization Overrun Interrupt Flag for given Request Generator Channel
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
Returns
Request Generator Channel Trigger Overrun Interrupt Flag
Definition at line 347 of file dmamux.c.
References DMAMUX_RGSR, and DMAMUX_RGSR_OF.
dmamux_reset_dma_channel()
void dmamux_reset_dma_channel (uint32_t dmamux, uint8_t channel)
DMAMUX Reset DMA Channel.
Reset DMA Request configuration and interrupt flags for given DMA channel.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
Definition at line 37 of file dmamux.c.
References dmamux_clear_dma_request_sync_overrun(), and DMAMUX_CxCR.
dmamux_reset_request_generator_channel()
void dmamux_reset_request_generator_channel (uint32_t dmamux, uint8_t rg_channel)
DMAMUX Reset Request Generator Channel.
Reset Request Generator Channel Configuration and interrupt flags.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
Definition at line 232 of file dmamux.c.
References dmamux_clear_request_generator_trigger_overrun_interrupt(), and DMAMUX_RGxCR.
dmamux_set_dma_channel_request()
void dmamux_set_dma_channel_request (uint32_t dmamux, uint8_t channel, uint8_t request_id)
DMAMUX Set DMA Channel Request.
Set DMA Request Signal ID (DMAREQID DMA request line selected) for given DMA channel. Request must be set before enabling and after configuring said DMA channel.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
[in] request_id DMA request (DMAREQID DMA request line selected)
Definition at line 53 of file dmamux.c.
References DMAMUX_CxCR, DMAMUX_CxCR_DMAREQ_ID_MASK, and DMAMUX_CxCR_DMAREQ_ID_SHIFT.
dmamux_set_dma_request_sync_input()
void dmamux_set_dma_request_sync_input (uint32_t dmamux, uint8_t channel, uint8_t sync_input_id)
DMAMUX Set DMA Request Synchronization Input.
Set DMAMUX request synchronization input trigger signal id (SYNCID Synchronization input selected) for a given DMA channel.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
[in] sync_input_id synchronization signal input id (SYNCID Synchronization input selected)
Definition at line 105 of file dmamux.c.
References DMAMUX_CxCR, DMAMUX_CxCR_SYNC_ID_MASK, and DMAMUX_CxCR_SYNC_ID_SHIFT.
dmamux_set_dma_request_sync_nbreq()
void dmamux_set_dma_request_sync_nbreq (uint32_t dmamux, uint8_t channel, uint8_t nbreq)
DMAMUX Set DMA Request NBREQ To Forward.
Set number of request to forward (minus 1) to the dma controller after a synchronization event. This must be configured with synchronization and event generation disabled.
Parameters
[in] dmamux DMAMUX Controller base address (DMAMUX register base addresses)
[in] channel DMA Channel Number (DMA Channel Number)
[in] nbreq Number of DMA Requests to Forward - minus 1 (0..31)
Definition at line 167 of file dmamux.c.
References DMAMUX_CxCR, DMAMUX_CxCR_NBREQ_MASK, and DMAMUX_CxCR_NBREQ_SHIFT.
dmamux_set_dma_request_sync_pol()
void dmamux_set_dma_request_sync_pol (uint32_t dmamux, uint8_t channel, uint8_t polarity)
DMAMUX Set DMA Request Synchronization Event Polarity.
Set DMAMUX request synchronization input signal polarity (SPOL Event Polarity) for a given DMA channel.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] channel DMA channel number (DMA Channel Number)
[in] polarity synchronization signal input polarity (SPOL Event Polarity)
Definition at line 123 of file dmamux.c.
References DMAMUX_CxCR, DMAMUX_CxCR_SPOL_MASK, and DMAMUX_CxCR_SPOL_SHIFT.
dmamux_set_request_generator_trigger()
void dmamux_set_request_generator_trigger (uint32_t dmamux, uint8_t rg_channel, uint8_t sig_id)
DMAMUX Set Request Generator Input Trigger Signal.
Set DMAMUX Request Generator input signal id (SIGID DMA request trigger input selected) for given Request Generator Channel.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
[in] sig_id Request Generator Channel Input Signal Id (SIGID DMA request trigger input selected)
Definition at line 273 of file dmamux.c.
References DMAMUX_RGxCR, DMAMUX_RGxCR_SIG_ID_MASK, and DMAMUX_RGxCR_SIG_ID_SHIFT.
dmamux_set_request_generator_trigger_gnbreq()
void dmamux_set_request_generator_trigger_gnbreq (uint32_t dmamux, uint8_t rg_channel, uint8_t gnbreq)
DMAMUX Set Request Generator Trigger GNBREQ.
Set number of request to generate (minus 1). This must be configured while given Request Generator is disabled.
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
[in] gnbreq Number of DMA Requests to Generate - minus 1 (0..31).
Definition at line 308 of file dmamux.c.
References DMAMUX_RGxCR, DMAMUX_RGxCR_GNBREQ_MASK, and DMAMUX_RGxCR_GNBREQ_SHIFT.
dmamux_set_request_generator_trigger_pol()
void dmamux_set_request_generator_trigger_pol (uint32_t dmamux, uint8_t rg_channel, uint8_t polarity)
DMAMUX Set Request Generator Trigger Polarity.
Set DMAMUX Request Generator input signal polarity (GPOL Event Polarity).
Parameters
[in] dmamux DMAMUX controller base address (DMAMUX register base addresses)
[in] rg_channel Request Generator Channel Number (DMAMUX Request Generator Channel Number)
[in] polarity Trigger signal input polarity (GPOL Event Polarity)
Definition at line 290 of file dmamux.c.
References DMAMUX_RGxCR, DMAMUX_RGxCR_GPOL_MASK, and DMAMUX_RGxCR_GPOL_SHIFT.