libopencm3: DAC Defines
DAC Defines
STM32G4xx Defines
Defined Constants and Types for the STM32G4xx DAC
Modules
DAC register base addresses
DAC Registers
DAC_CR values
DAC_SWTRIGR Values
DAC_DHRxxx Values
DAC_DORx Values
DAC_SR Values
DAC Channel Identifier
DAC_CCR values
DAC_MCR values
DAC Channel 1 Sawtooth Direction Setting
DAC Channel 2 Sawtooth Direction Setting
DAC Channel 2 Sawtooth Increment Trigger
DAC Channel 2 Sawtooth Reset Trigger
DAC Channel 1 Sawtooth Increment Trigger
DAC Channel 1 Sawtooth Reset Trigger
Macros
#define DAC_SHSR1_TSAMPLE1_SHIFT 0
#define DAC_SHSR1_TSAMPLE1_MASK 0x1FF
#define DAC_SHSR2_TSAMPLE2_SHIFT 0
#define DAC_SHSR2_TSAMPLE2_MASK 0x1FF
#define DAC_SHHSR_THOLD2_SHIFT 16
#define DAC_SHHSR_THOLD2_MASK 0x1FF
#define DAC_SHHSR_THOLD1_SHIFT 0
#define DAC_SHHSR_THOLD1_MASK 0x1FF
#define DAC_STR1_STINCDATA1_SHIFT 16
#define DAC_STR1_STINCDATA1_MASK 0xFFFF
#define DAC_STR1_STDIR1_SHIFT 12
#define DAC_STR1_STRSTDATA1_SHIFT 0
#define DAC_STR1_STRSTDATA1_MASK 0xFFF
#define DAC_STR2_STINCDATA2_SHIFT 16
#define DAC_STR2_STINCDATA2_MASK 0xFFFF
#define DAC_STR2_STDIR2_SHIFT 12
#define DAC_STR2_STRSTDATA2_SHIFT 0
#define DAC_STR2_STRSTDATA2_MASK 0xFFF
#define DAC_STMODR_STINCTRIGSEL2_SHIFT 24
#define DAC_STMODR_STRSTTRIGSEL2_SHIFT 16
#define DAC_STMODR_STINCTRIGSEL1_SHIFT 8
#define DAC_STMODR_STRSTTRIGSEL1_SHIFT 0
Enumerations
enum dac_align { DAC_ALIGN_RIGHT8 , DAC_ALIGN_RIGHT12 , DAC_ALIGN_LEFT12 }
DAC data size (8/12 bits), alignment (right/left)
enum dac_wave { DAC_WAVE_DISABLE = 0 , DAC_WAVE_NOISE = 1 , DAC_WAVE_TRIANGLE = 2 , DAC_WAVE_SAWTOOTH = 3 }
DAC waveform generation options.
Functions
void dac_enable (uint32_t dac, int channel)
DAC Channel Enable.
void dac_disable (uint32_t dac, int channel)
DAC Channel Disable.
void dac_buffer_enable (uint32_t dac, int channel)
DAC Channel Output Buffer Enable.
void dac_buffer_disable (uint32_t dac, int channel)
DAC Channel Output Buffer Disable.
void dac_dma_enable (uint32_t dac, int channel)
DAC Channel DMA Enable.
void dac_dma_disable (uint32_t dac, int channel)
DAC Channel DMA Disable.
void dac_trigger_enable (uint32_t dac, int channel)
DAC Channel Trigger Enable.
void dac_trigger_disable (uint32_t dac, int channel)
DAC Channel Trigger Disable.
void dac_set_trigger_source (uint32_t dac, uint32_t source)
Set DAC Channel Trigger Source.
void dac_set_waveform_generation (uint32_t dac, int channel, enum dac_wave wave)
Set DAC Channel Waveform Generation mode for one or both channels.
void dac_disable_waveform_generation (uint32_t dac, int channel)
Disable DAC Channel Waveform Generation.
void dac_set_waveform_characteristics (uint32_t dac, int channel, int mamp)
Set DAC Channel LFSR Mask or Triangle Wave Amplitude.
void dac_load_data_buffer_single (uint32_t dac, uint16_t data, enum dac_align align, int channel)
Load DAC Data Register.
void dac_load_data_buffer_dual (uint32_t dac, uint16_t data1, uint16_t data2, enum dac_align align)
Load DAC Dual Data Register.
void dac_software_trigger (uint32_t dac, int channel)
Trigger the DAC by a Software Trigger.
void dac_set_mode (uint32_t dac, uint32_t mode)
DAC Channel Output Mode.
bool dac_is_ready (uint32_t dac, int channel)
Check if DAC channel is ready to receive data.
void dac_wait_on_ready (uint32_t dac, int channel)
Wait until DAC channel is ready to receive data.
void dac_set_high_frequency_mode (uint32_t dac, uint32_t hfsel)
High frequency interface mode selection.
Detailed Description
Defined Constants and Types for the STM32G4xx DAC
Version
1.0.0
Date
3 August 2020
LGPL License Terms libopencm3 License
Author
© 2012 Felix Held felix.nosp@m.-lib.nosp@m.openc.nosp@m.m3@f.nosp@m.elixh.nosp@m.eld..nosp@m.de
© 2020 Ben Brewer ben.b.nosp@m.rewe.nosp@m.r@cod.nosp@m.ethi.nosp@m.nk.co.nosp@m..uk
© 2020 Ben Brewer ben.b.nosp@m.rewe.nosp@m.r@cod.nosp@m.ethi.nosp@m.nk.co.nosp@m..uk
Macro Definition Documentation
DAC_SHHSR_THOLD1_MASK
#define DAC_SHHSR_THOLD1_MASK 0x1FF
Definition at line 353 of file dac_common_v2.h.
DAC_SHHSR_THOLD1_SHIFT
#define DAC_SHHSR_THOLD1_SHIFT 0
Definition at line 352 of file dac_common_v2.h.
DAC_SHHSR_THOLD2_MASK
#define DAC_SHHSR_THOLD2_MASK 0x1FF
Definition at line 349 of file dac_common_v2.h.
DAC_SHHSR_THOLD2_SHIFT
#define DAC_SHHSR_THOLD2_SHIFT 16
Definition at line 348 of file dac_common_v2.h.
DAC_SHSR1_TSAMPLE1_MASK
#define DAC_SHSR1_TSAMPLE1_MASK 0x1FF
Definition at line 337 of file dac_common_v2.h.
DAC_SHSR1_TSAMPLE1_SHIFT
#define DAC_SHSR1_TSAMPLE1_SHIFT 0
Definition at line 336 of file dac_common_v2.h.
DAC_SHSR2_TSAMPLE2_MASK
#define DAC_SHSR2_TSAMPLE2_MASK 0x1FF
Definition at line 343 of file dac_common_v2.h.
DAC_SHSR2_TSAMPLE2_SHIFT
#define DAC_SHSR2_TSAMPLE2_SHIFT 0
Definition at line 342 of file dac_common_v2.h.
DAC_STMODR_STINCTRIGSEL1_SHIFT
#define DAC_STMODR_STINCTRIGSEL1_SHIFT 8
Definition at line 487 of file dac_common_v2.h.
DAC_STMODR_STINCTRIGSEL2_SHIFT
#define DAC_STMODR_STINCTRIGSEL2_SHIFT 24
Definition at line 402 of file dac_common_v2.h.
DAC_STMODR_STRSTTRIGSEL1_SHIFT
#define DAC_STMODR_STRSTTRIGSEL1_SHIFT 0
Definition at line 529 of file dac_common_v2.h.
DAC_STMODR_STRSTTRIGSEL2_SHIFT
#define DAC_STMODR_STRSTTRIGSEL2_SHIFT 16
Definition at line 444 of file dac_common_v2.h.
DAC_STR1_STDIR1_SHIFT
#define DAC_STR1_STDIR1_SHIFT 12
Definition at line 362 of file dac_common_v2.h.
DAC_STR1_STINCDATA1_MASK
#define DAC_STR1_STINCDATA1_MASK 0xFFFF
Definition at line 359 of file dac_common_v2.h.
DAC_STR1_STINCDATA1_SHIFT
#define DAC_STR1_STINCDATA1_SHIFT 16
Definition at line 358 of file dac_common_v2.h.
DAC_STR1_STRSTDATA1_MASK
#define DAC_STR1_STRSTDATA1_MASK 0xFFF
Definition at line 375 of file dac_common_v2.h.
DAC_STR1_STRSTDATA1_SHIFT
#define DAC_STR1_STRSTDATA1_SHIFT 0
Definition at line 374 of file dac_common_v2.h.
DAC_STR2_STDIR2_SHIFT
#define DAC_STR2_STDIR2_SHIFT 12
Definition at line 384 of file dac_common_v2.h.
DAC_STR2_STINCDATA2_MASK
#define DAC_STR2_STINCDATA2_MASK 0xFFFF
Definition at line 381 of file dac_common_v2.h.
DAC_STR2_STINCDATA2_SHIFT
#define DAC_STR2_STINCDATA2_SHIFT 16
Definition at line 380 of file dac_common_v2.h.
DAC_STR2_STRSTDATA2_MASK
#define DAC_STR2_STRSTDATA2_MASK 0xFFF
Definition at line 397 of file dac_common_v2.h.
DAC_STR2_STRSTDATA2_SHIFT
#define DAC_STR2_STRSTDATA2_SHIFT 0
Definition at line 396 of file dac_common_v2.h.
Enumeration Type Documentation
dac_align
enum dac_align
DAC data size (8/12 bits), alignment (right/left)
Enumerator
DAC_ALIGN_RIGHT8
DAC_ALIGN_RIGHT12
DAC_ALIGN_LEFT12
Definition at line 237 of file dac_common_all.h.
dac_wave
enum dac_wave
DAC waveform generation options.
Not all wave shapes are available on all parts.
Enumerator
DAC_WAVE_DISABLE
DAC_WAVE_NOISE
DAC_WAVE_TRIANGLE
DAC_WAVE_SAWTOOTH
Definition at line 246 of file dac_common_all.h.
Function Documentation
dac_buffer_disable()
void dac_buffer_disable (uint32_t dac, int channel)
DAC Channel Output Buffer Disable.
Disable a digital to analog converter channel output drive buffer. Disabling this will reduce power consumption slightly and will increase the output impedance of the DAC. The buffers are enabled by default after a reset.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 69 of file dac_common_v2.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_MCR, DAC_MCR_MODE1_UNBUFFERED, and DAC_MCR_MODE2_UNBUFFERED.
dac_buffer_enable()
void dac_buffer_enable (uint32_t dac, int channel)
DAC Channel Output Buffer Enable.
Enable a digital to analog converter channel output drive buffer. This is an optional amplifying buffer that provides additional drive for the output signal. The buffer is enabled by default after a reset and needs to be explicitly disabled if required.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 42 of file dac_common_v2.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_MCR, DAC_MCR_MODE1_UNBUFFERED, and DAC_MCR_MODE2_UNBUFFERED.
dac_disable()
void dac_disable (uint32_t dac, int channel)
DAC Channel Disable.
Disable a digital to analog converter channel.
Parameters
[in] dac the base address of the DAC DAC register base addresses
[in] channel with DAC mask DAC Channel Identifier
Definition at line 159 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_EN1, and DAC_CR_EN2.
dac_disable_waveform_generation()
void dac_disable_waveform_generation (uint32_t dac, int channel)
Disable DAC Channel Waveform Generation.
Note
this is equivalent to dac_set_waveform_generation (dac, channel, DAC_WAVE_DISABLE)
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 332 of file dac_common_all.c.
References dac_set_waveform_generation(), and DAC_WAVE_DISABLE.
dac_dma_disable()
void dac_dma_disable (uint32_t dac, int channel)
DAC Channel DMA Disable.
Disable a digital to analog converter channel DMA mode.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 209 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_DMAEN1, and DAC_CR_DMAEN2.
dac_dma_enable()
void dac_dma_enable (uint32_t dac, int channel)
DAC Channel DMA Enable.
Enable a digital to analog converter channel DMA mode (connected to DMA2 channel 3 for DAC channel 1 and DMA2 channel 4 for DAC channel 2). A DMA request is generated following an external trigger.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 185 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_DMAEN1, and DAC_CR_DMAEN2.
dac_enable()
void dac_enable (uint32_t dac, int channel)
DAC Channel Enable.
Enable a digital to analog converter channel. After setting this enable, the DAC requires a twakeup time typically around 10 microseconds before it actually wakes up.
Parameters
[in] dac the base address of the DAC DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 137 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_EN1, and DAC_CR_EN2.
dac_is_ready()
bool dac_is_ready (uint32_t dac, int channel)
Check if DAC channel is ready to receive data.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 112 of file dac_common_v2.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_SR, DAC_SR_DAC1RDY, and DAC_SR_DAC2RDY.
Referenced by dac_wait_on_ready().
dac_load_data_buffer_dual()
void dac_load_data_buffer_dual (uint32_t dac, uint16_t data1, uint16_t data2, enum dac_align align)
Load DAC Dual Data Register.
Loads the appropriate digital to analog converter dual data register with 12 or 8 bit data to be converted for both channels. This allows high bandwidth simultaneous or independent analog output. The data in both channels are aligned identically.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] data1 uint16_t for channel 1 with appropriate alignment.
[in] data2 uint16_t for channel 2 with appropriate alignment.
[in] align enum dac_align. Right or left aligned, and 8 or 12 bit.
Definition at line 441 of file dac_common_all.c.
References DAC_ALIGN_LEFT12, DAC_ALIGN_RIGHT12, DAC_ALIGN_RIGHT8, DAC_DHR12LD, DAC_DHR12RD, and DAC_DHR8RD.
dac_load_data_buffer_single()
void dac_load_data_buffer_single (uint32_t dac, uint16_t data, enum dac_align align, int channel)
Load DAC Data Register.
Loads the appropriate digital to analog converter data register with 12 or 8 bit data to be converted on a channel. The data can be aligned as follows:
right-aligned 8 bit data in bits 0-7
right-aligned 12 bit data in bits 0-11
left aligned 12 bit data in bits 4-15
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] data uint16_t with appropriate alignment.
[in] align enum dac_align. Alignment and size.
[in] channel uint8_t with DAC mask.
Definition at line 393 of file dac_common_all.c.
References DAC_ALIGN_LEFT12, DAC_ALIGN_RIGHT12, DAC_ALIGN_RIGHT8, DAC_CHANNEL1, DAC_CHANNEL2, DAC_DHR12L1, DAC_DHR12L2, DAC_DHR12R1, DAC_DHR12R2, DAC_DHR8R1, and DAC_DHR8R2.
dac_set_high_frequency_mode()
void dac_set_high_frequency_mode (uint32_t dac, uint32_t hfsel)
High frequency interface mode selection.
If the AHB frequency of the DAC is above 80MHz then this value needs setting to an appropriate value.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] hfsel uint32_t with appropriate HFSEL mask.
Definition at line 143 of file dac_common_v2.c.
References DAC_MCR, DAC_MCR_HFSEL_MASK, and DAC_MCR_HFSEL_SHIFT.
dac_set_mode()
void dac_set_mode (uint32_t dac, uint32_t mode)
DAC Channel Output Mode.
Each DAC channel can be configured in Normal mode or Sample and hold mode. The output buffer can be enabled to allow a high drive capability. Before enabling output buffer, the voltage offset needs to be calibrated. This calibration is performed at the factory (loaded after reset) and can be adjusted by software during application operation.
Note
This must be called before enabling the DAC as the settings will then become read-only.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] mode Taken from DAC Channel 2 Mode Selection or DAC Channel 1 Mode Selection or a logical OR of one of each of these to set both channels simultaneously.
Definition at line 102 of file dac_common_v2.c.
References DAC_MCR.
dac_set_trigger_source()
void dac_set_trigger_source (uint32_t dac, uint32_t source)
Set DAC Channel Trigger Source.
Sets the digital to analog converter trigger source, which can be taken from various timers, an external trigger or a software trigger.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] source Taken from DAC Channel 2 Trigger Source Selection or DAC Channel 1 Trigger Source Selection or a logical OR of one of each of these to set both channels simultaneously.
Definition at line 287 of file dac_common_all.c.
References DAC_CR.
dac_set_waveform_characteristics()
void dac_set_waveform_characteristics (uint32_t dac, int channel, int mamp)
Set DAC Channel LFSR Mask or Triangle Wave Amplitude.
Sets the digital to analog converter superimposed waveform generation characteristics.
If the noise generation mode is set, this sets the length of the PRBS sequence and hence the amplitude of the output noise signal. Default setting is length 1.
If the triangle wave generation mode is set, this sets the amplitude of the output signal as 2^(n)-1 where n is the parameter value. Default setting is 1.
Note
High amplitude levels of these waveforms can overload the DAC and distort the signal output.
This must be called before enabling the DAC as the settings will then become read-only.
The DAC trigger must be enabled for this to work.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel one or both, select from DAC Channel Identifier
[in] mamp amplitude of mixed waveform, bit width DAC_CR_MAMPx_MASK
Definition at line 356 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_MAMP1_SHIFT, DAC_CR_MAMP2_SHIFT, and DAC_CR_MAMPx_MASK.
dac_set_waveform_generation()
void dac_set_waveform_generation (uint32_t dac, int channel, enum dac_wave wave)
Set DAC Channel Waveform Generation mode for one or both channels.
These signals are superimposed on existing output values in the DAC output registers. Waveform can be disabled, noise, triangular, or sawtooth, depending on family.
Note
The DAC trigger must be enabled for this to work.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel one or both, DAC Channel Identifier
[in] wave enum dac_wave. mode for channel
Definition at line 302 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_WAVE1_SHIFT, DAC_CR_WAVE2_SHIFT, and DAC_CR_WAVEx_MASK.
Referenced by dac_disable_waveform_generation().
dac_software_trigger()
void dac_software_trigger (uint32_t dac, int channel)
Trigger the DAC by a Software Trigger.
If the trigger source is set to be a software trigger, cause a trigger to occur. The trigger is cleared by hardware after conversion.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 470 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_SWTRIGR, DAC_SWTRIGR_SWTRIG1, and DAC_SWTRIGR_SWTRIG2.
dac_trigger_disable()
void dac_trigger_disable (uint32_t dac, int channel)
DAC Channel Trigger Disable.
Disable a digital to analog converter channel external trigger.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 260 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_TEN1, and DAC_CR_TEN2.
dac_trigger_enable()
void dac_trigger_enable (uint32_t dac, int channel)
DAC Channel Trigger Enable.
Enable a digital to analog converter channel external trigger mode. This allows an external trigger to initiate register transfers from the buffer register to the DAC output register, followed by a DMA transfer to the buffer register if DMA is enabled. The trigger source must also be selected.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 236 of file dac_common_all.c.
References DAC_CHANNEL1, DAC_CHANNEL2, DAC_CHANNEL_BOTH, DAC_CR, DAC_CR_TEN1, and DAC_CR_TEN2.
dac_wait_on_ready()
void dac_wait_on_ready (uint32_t dac, int channel)
Wait until DAC channel is ready to receive data.
Parameters
[in] dac the base address of the DAC. DAC register base addresses
[in] channel with DAC mask. DAC Channel Identifier
Definition at line 130 of file dac_common_v2.c.
References dac_is_ready().