libopencm3: LCD Defines
LCD Defines
STM32L1xx Defines
Defined Constants and Types for the STM32L1xx LCD Controller.
Modules
LCD registers
Macros
#define LCD_RAM_BASE (LCD_BASE + 0x14)
#define LCD_RAM_COM0 MMIO64(LCD_RAM_BASE + 0x00)
#define LCD_RAM_COM1 MMIO64(LCD_RAM_BASE + 0x08)
#define LCD_RAM_COM2 MMIO64(LCD_RAM_BASE + 0x10)
#define LCD_RAM_COM3 MMIO64(LCD_RAM_BASE + 0x18)
#define LCD_RAM_COM4 MMIO64(LCD_RAM_BASE + 0x20)
#define LCD_RAM_COM5 MMIO64(LCD_RAM_BASE + 0x28)
#define LCD_RAM_COM6 MMIO64(LCD_RAM_BASE + 0x30)
#define LCD_RAM_COM7 MMIO64(LCD_RAM_BASE + 0x38)
#define LCD_CR_LCDEN (1 << 0)
#define LCD_CR_VSEL (1 << 1)
#define LCD_CR_DUTY_SHIFT 2
#define LCD_CR_DUTY_MASK 0x7
#define LCD_CR_DUTY_STATIC 0x0
#define LCD_CR_DUTY_1_2 0x1
#define LCD_CR_DUTY_1_3 0x2
#define LCD_CR_DUTY_1_4 0x3
#define LCD_CR_DUTY_1_8 0x4
#define LCD_CR_BIAS_SHIFT 5
#define LCD_CR_BIAS_MASK 0x3
#define LCD_CR_BIAS_1_4 0x0
#define LCD_CR_BIAS_1_2 0x1
#define LCD_CR_BIAS_1_3 0x2
#define LCD_CR_MUX_SEG (1 << 7)
#define LCD_FCR_HD (1 << 0)
#define LCD_FCR_SOFIE (1 << 1)
#define LCD_FCR_UDDIE (1 << 3)
#define LCD_FCR_PON_SHIFT 4
#define LCD_FCR_PON_MASK 0x7
#define LCD_FCR_PON_0 0x0
#define LCD_FCR_PON_1 0x1
#define LCD_FCR_PON_2 0x2
#define LCD_FCR_PON_3 0x3
#define LCD_FCR_PON_4 0x4
#define LCD_FCR_PON_5 0x5
#define LCD_FCR_PON_6 0x6
#define LCD_FCR_PON_7 0x7
#define LCD_FCR_DEAD_SHIFT 7
#define LCD_FCR_DEAD_MASK 0x7
#define LCD_FCR_DEAD_NONE 0x0
#define LCD_FCR_DEAD_1_PHASE 0x1
#define LCD_FCR_DEAD_2_PHASE 0x2
#define LCD_FCR_DEAD_3_PHASE 0x3
#define LCD_FCR_DEAD_4_PHASE 0x4
#define LCD_FCR_DEAD_5_PHASE 0x5
#define LCD_FCR_DEAD_6_PHASE 0x6
#define LCD_FCR_DEAD_7_PHASE 0x7
#define LCD_FCR_CC_SHIFT 10
#define LCD_FCR_CC_MASK 0x7
#define LCD_FCR_CC_0 0x0
#define LCD_FCR_CC_1 0x1
#define LCD_FCR_CC_2 0x2
#define LCD_FCR_CC_3 0x3
#define LCD_FCR_CC_4 0x4
#define LCD_FCR_CC_5 0x5
#define LCD_FCR_CC_6 0x6
#define LCD_FCR_CC_7 0x7
#define LCD_FCR_BLINKF_SHIFT 13
#define LCD_FCR_BLINKF_MASK 0x7
#define LCD_FCR_BLINKF_8 0x0
#define LCD_FCR_BLINKF_16 0x1
#define LCD_FCR_BLINKF_32 0x2
#define LCD_FCR_BLINKF_64 0x3
#define LCD_FCR_BLINKF_128 0x4
#define LCD_FCR_BLINKF_256 0x5
#define LCD_FCR_BLINKF_512 0x6
#define LCD_FCR_BLINKF_1024 0x7
#define LCD_FCR_BLINK_SHIFT 16
#define LCD_FCR_BLINK_MASK 0x3
#define LCD_FCR_BLINK_DISABLE 0x0
#define LCD_FCR_BLINK_SEG0_COM0_ENABLE 0x1
#define LCD_FCR_BLINK_SEG0_ENABLE 0x2
#define LCD_FCR_BLINK_ALL_ENABLE 0x3
#define LCD_FCR_DIV_SHIFT 18
#define LCD_FCR_DIV_MASK 0xF
#define LCD_FCR_DIV_16 0x0
#define LCD_FCR_DIV_17 0x1
#define LCD_FCR_DIV_18 0x2
#define LCD_FCR_DIV_19 0x3
#define LCD_FCR_DIV_20 0x4
#define LCD_FCR_DIV_21 0x5
#define LCD_FCR_DIV_22 0x6
#define LCD_FCR_DIV_23 0x7
#define LCD_FCR_DIV_24 0x8
#define LCD_FCR_DIV_25 0x9
#define LCD_FCR_DIV_26 0xA
#define LCD_FCR_DIV_27 0xB
#define LCD_FCR_DIV_28 0xC
#define LCD_FCR_DIV_29 0xD
#define LCD_FCR_DIV_30 0xE
#define LCD_FCR_DIV_31 0xF
#define LCD_FCR_PS_SHIFT 22
#define LCD_FCR_PS_MASK 0xF
#define LCD_FCR_PS_1 0x0
#define LCD_FCR_PS_2 0x1
#define LCD_FCR_PS_4 0x2
#define LCD_FCR_PS_8 0x3
#define LCD_FCR_PS_16 0x4
#define LCD_FCR_PS_32 0x5
#define LCD_FCR_PS_64 0x6
#define LCD_FCR_PS_128 0x7
#define LCD_FCR_PS_256 0x8
#define LCD_FCR_PS_512 0x9
#define LCD_FCR_PS_1024 0xA
#define LCD_FCR_PS_2048 0xB
#define LCD_FCR_PS_4096 0xC
#define LCD_FCR_PS_8192 0xD
#define LCD_FCR_PS_16384 0xE
#define LCD_FCR_PS_32768 0xF
#define LCD_SR_ENS (1 << 0)
#define LCD_SR_SOF (1 << 1)
#define LCD_SR_UDR (1 << 2)
#define LCD_SR_UDD (1 << 3)
#define LCD_SR_RDY (1 << 4)
#define LCD_SR_FCRSF (1 << 5)
#define LCD_CLR_SOFC (1 << 1)
#define LCD_CLR_UDDC (1 << 3)
Functions
void lcd_enable (void)
void lcd_update (void)
void lcd_wait_for_lcd_enabled (void)
void lcd_wait_for_step_up_ready (void)
void lcd_wait_for_update_ready (void)
int lcd_is_enabled (void)
int lcd_is_step_up_ready (void)
int lcd_is_for_update_ready (void)
void lcd_set_contrast (uint8_t contrast)
void lcd_set_bias (uint8_t bias)
void lcd_set_duty (uint8_t duty)
void lcd_set_prescaler (uint8_t ps)
void lcd_set_divider (uint8_t div)
void lcd_enable_segment_multiplexing (void)
void lcd_disable_segment_multiplexing (void)
void lcd_set_refresh_frequency (uint32_t frequency)
Detailed Description
Defined Constants and Types for the STM32L1xx LCD Controller.
Version
1.0.0
Author
© 2014 Nikolay Merinov nikol.nosp@m.ay.m.nosp@m.erino.nosp@m.v@me.nosp@m.mber..nosp@m.fsf..nosp@m.org
Date
2 March 2014
LGPL License Terms libopencm3 License
Macro Definition Documentation
LCD_CLR_SOFC
#define LCD_CLR_SOFC (1 << 1)
Definition at line 197 of file lcd.h.
LCD_CLR_UDDC
#define LCD_CLR_UDDC (1 << 3)
Definition at line 198 of file lcd.h.
LCD_CR_BIAS_1_2
#define LCD_CR_BIAS_1_2 0x1
Definition at line 89 of file lcd.h.
LCD_CR_BIAS_1_3
#define LCD_CR_BIAS_1_3 0x2
Definition at line 90 of file lcd.h.
LCD_CR_BIAS_1_4
#define LCD_CR_BIAS_1_4 0x0
Definition at line 88 of file lcd.h.
LCD_CR_BIAS_MASK
#define LCD_CR_BIAS_MASK 0x3
Definition at line 87 of file lcd.h.
LCD_CR_BIAS_SHIFT
#define LCD_CR_BIAS_SHIFT 5
Definition at line 86 of file lcd.h.
LCD_CR_DUTY_1_2
#define LCD_CR_DUTY_1_2 0x1
Definition at line 81 of file lcd.h.
LCD_CR_DUTY_1_3
#define LCD_CR_DUTY_1_3 0x2
Definition at line 82 of file lcd.h.
LCD_CR_DUTY_1_4
#define LCD_CR_DUTY_1_4 0x3
Definition at line 83 of file lcd.h.
LCD_CR_DUTY_1_8
#define LCD_CR_DUTY_1_8 0x4
Definition at line 84 of file lcd.h.
LCD_CR_DUTY_MASK
#define LCD_CR_DUTY_MASK 0x7
Definition at line 79 of file lcd.h.
LCD_CR_DUTY_SHIFT
#define LCD_CR_DUTY_SHIFT 2
Definition at line 78 of file lcd.h.
LCD_CR_DUTY_STATIC
#define LCD_CR_DUTY_STATIC 0x0
Definition at line 80 of file lcd.h.
LCD_CR_LCDEN
#define LCD_CR_LCDEN (1 << 0)
Definition at line 75 of file lcd.h.
LCD_CR_MUX_SEG
#define LCD_CR_MUX_SEG (1 << 7)
Definition at line 92 of file lcd.h.
LCD_CR_VSEL
#define LCD_CR_VSEL (1 << 1)
Definition at line 76 of file lcd.h.
LCD_FCR_BLINK_ALL_ENABLE
#define LCD_FCR_BLINK_ALL_ENABLE 0x3
Definition at line 148 of file lcd.h.
LCD_FCR_BLINK_DISABLE
#define LCD_FCR_BLINK_DISABLE 0x0
Definition at line 145 of file lcd.h.
LCD_FCR_BLINK_MASK
#define LCD_FCR_BLINK_MASK 0x3
Definition at line 144 of file lcd.h.
LCD_FCR_BLINK_SEG0_COM0_ENABLE
#define LCD_FCR_BLINK_SEG0_COM0_ENABLE 0x1
Definition at line 146 of file lcd.h.
LCD_FCR_BLINK_SEG0_ENABLE
#define LCD_FCR_BLINK_SEG0_ENABLE 0x2
Definition at line 147 of file lcd.h.
LCD_FCR_BLINK_SHIFT
#define LCD_FCR_BLINK_SHIFT 16
Definition at line 143 of file lcd.h.
LCD_FCR_BLINKF_1024
#define LCD_FCR_BLINKF_1024 0x7
Definition at line 141 of file lcd.h.
LCD_FCR_BLINKF_128
#define LCD_FCR_BLINKF_128 0x4
Definition at line 138 of file lcd.h.
LCD_FCR_BLINKF_16
#define LCD_FCR_BLINKF_16 0x1
Definition at line 135 of file lcd.h.
LCD_FCR_BLINKF_256
#define LCD_FCR_BLINKF_256 0x5
Definition at line 139 of file lcd.h.
LCD_FCR_BLINKF_32
#define LCD_FCR_BLINKF_32 0x2
Definition at line 136 of file lcd.h.
LCD_FCR_BLINKF_512
#define LCD_FCR_BLINKF_512 0x6
Definition at line 140 of file lcd.h.
LCD_FCR_BLINKF_64
#define LCD_FCR_BLINKF_64 0x3
Definition at line 137 of file lcd.h.
LCD_FCR_BLINKF_8
#define LCD_FCR_BLINKF_8 0x0
Definition at line 134 of file lcd.h.
LCD_FCR_BLINKF_MASK
#define LCD_FCR_BLINKF_MASK 0x7
Definition at line 133 of file lcd.h.
LCD_FCR_BLINKF_SHIFT
#define LCD_FCR_BLINKF_SHIFT 13
Definition at line 132 of file lcd.h.
LCD_FCR_CC_0
#define LCD_FCR_CC_0 0x0
Definition at line 123 of file lcd.h.
LCD_FCR_CC_1
#define LCD_FCR_CC_1 0x1
Definition at line 124 of file lcd.h.
LCD_FCR_CC_2
#define LCD_FCR_CC_2 0x2
Definition at line 125 of file lcd.h.
LCD_FCR_CC_3
#define LCD_FCR_CC_3 0x3
Definition at line 126 of file lcd.h.
LCD_FCR_CC_4
#define LCD_FCR_CC_4 0x4
Definition at line 127 of file lcd.h.
LCD_FCR_CC_5
#define LCD_FCR_CC_5 0x5
Definition at line 128 of file lcd.h.
LCD_FCR_CC_6
#define LCD_FCR_CC_6 0x6
Definition at line 129 of file lcd.h.
LCD_FCR_CC_7
#define LCD_FCR_CC_7 0x7
Definition at line 130 of file lcd.h.
LCD_FCR_CC_MASK
#define LCD_FCR_CC_MASK 0x7
Definition at line 122 of file lcd.h.
LCD_FCR_CC_SHIFT
#define LCD_FCR_CC_SHIFT 10
Definition at line 121 of file lcd.h.
LCD_FCR_DEAD_1_PHASE
#define LCD_FCR_DEAD_1_PHASE 0x1
Definition at line 113 of file lcd.h.
LCD_FCR_DEAD_2_PHASE
#define LCD_FCR_DEAD_2_PHASE 0x2
Definition at line 114 of file lcd.h.
LCD_FCR_DEAD_3_PHASE
#define LCD_FCR_DEAD_3_PHASE 0x3
Definition at line 115 of file lcd.h.
LCD_FCR_DEAD_4_PHASE
#define LCD_FCR_DEAD_4_PHASE 0x4
Definition at line 116 of file lcd.h.
LCD_FCR_DEAD_5_PHASE
#define LCD_FCR_DEAD_5_PHASE 0x5
Definition at line 117 of file lcd.h.
LCD_FCR_DEAD_6_PHASE
#define LCD_FCR_DEAD_6_PHASE 0x6
Definition at line 118 of file lcd.h.
LCD_FCR_DEAD_7_PHASE
#define LCD_FCR_DEAD_7_PHASE 0x7
Definition at line 119 of file lcd.h.
LCD_FCR_DEAD_MASK
#define LCD_FCR_DEAD_MASK 0x7
Definition at line 111 of file lcd.h.
LCD_FCR_DEAD_NONE
#define LCD_FCR_DEAD_NONE 0x0
Definition at line 112 of file lcd.h.
LCD_FCR_DEAD_SHIFT
#define LCD_FCR_DEAD_SHIFT 7
Definition at line 110 of file lcd.h.
LCD_FCR_DIV_16
#define LCD_FCR_DIV_16 0x0
Definition at line 152 of file lcd.h.
LCD_FCR_DIV_17
#define LCD_FCR_DIV_17 0x1
Definition at line 153 of file lcd.h.
LCD_FCR_DIV_18
#define LCD_FCR_DIV_18 0x2
Definition at line 154 of file lcd.h.
LCD_FCR_DIV_19
#define LCD_FCR_DIV_19 0x3
Definition at line 155 of file lcd.h.
LCD_FCR_DIV_20
#define LCD_FCR_DIV_20 0x4
Definition at line 156 of file lcd.h.
LCD_FCR_DIV_21
#define LCD_FCR_DIV_21 0x5
Definition at line 157 of file lcd.h.
LCD_FCR_DIV_22
#define LCD_FCR_DIV_22 0x6
Definition at line 158 of file lcd.h.
LCD_FCR_DIV_23
#define LCD_FCR_DIV_23 0x7
Definition at line 159 of file lcd.h.
LCD_FCR_DIV_24
#define LCD_FCR_DIV_24 0x8
Definition at line 160 of file lcd.h.
LCD_FCR_DIV_25
#define LCD_FCR_DIV_25 0x9
Definition at line 161 of file lcd.h.
LCD_FCR_DIV_26
#define LCD_FCR_DIV_26 0xA
Definition at line 162 of file lcd.h.
LCD_FCR_DIV_27
#define LCD_FCR_DIV_27 0xB
Definition at line 163 of file lcd.h.
LCD_FCR_DIV_28
#define LCD_FCR_DIV_28 0xC
Definition at line 164 of file lcd.h.
LCD_FCR_DIV_29
#define LCD_FCR_DIV_29 0xD
Definition at line 165 of file lcd.h.
LCD_FCR_DIV_30
#define LCD_FCR_DIV_30 0xE
Definition at line 166 of file lcd.h.
LCD_FCR_DIV_31
#define LCD_FCR_DIV_31 0xF
Definition at line 167 of file lcd.h.
LCD_FCR_DIV_MASK
#define LCD_FCR_DIV_MASK 0xF
Definition at line 151 of file lcd.h.
LCD_FCR_DIV_SHIFT
#define LCD_FCR_DIV_SHIFT 18
Definition at line 150 of file lcd.h.
LCD_FCR_HD
#define LCD_FCR_HD (1 << 0)
Definition at line 95 of file lcd.h.
LCD_FCR_PON_0
#define LCD_FCR_PON_0 0x0
Definition at line 101 of file lcd.h.
LCD_FCR_PON_1
#define LCD_FCR_PON_1 0x1
Definition at line 102 of file lcd.h.
LCD_FCR_PON_2
#define LCD_FCR_PON_2 0x2
Definition at line 103 of file lcd.h.
LCD_FCR_PON_3
#define LCD_FCR_PON_3 0x3
Definition at line 104 of file lcd.h.
LCD_FCR_PON_4
#define LCD_FCR_PON_4 0x4
Definition at line 105 of file lcd.h.
LCD_FCR_PON_5
#define LCD_FCR_PON_5 0x5
Definition at line 106 of file lcd.h.
LCD_FCR_PON_6
#define LCD_FCR_PON_6 0x6
Definition at line 107 of file lcd.h.
LCD_FCR_PON_7
#define LCD_FCR_PON_7 0x7
Definition at line 108 of file lcd.h.
LCD_FCR_PON_MASK
#define LCD_FCR_PON_MASK 0x7
Definition at line 100 of file lcd.h.
LCD_FCR_PON_SHIFT
#define LCD_FCR_PON_SHIFT 4
Definition at line 99 of file lcd.h.
LCD_FCR_PS_1
#define LCD_FCR_PS_1 0x0
Definition at line 171 of file lcd.h.
LCD_FCR_PS_1024
#define LCD_FCR_PS_1024 0xA
Definition at line 181 of file lcd.h.
LCD_FCR_PS_128
#define LCD_FCR_PS_128 0x7
Definition at line 178 of file lcd.h.
LCD_FCR_PS_16
#define LCD_FCR_PS_16 0x4
Definition at line 175 of file lcd.h.
LCD_FCR_PS_16384
#define LCD_FCR_PS_16384 0xE
Definition at line 185 of file lcd.h.
LCD_FCR_PS_2
#define LCD_FCR_PS_2 0x1
Definition at line 172 of file lcd.h.
LCD_FCR_PS_2048
#define LCD_FCR_PS_2048 0xB
Definition at line 182 of file lcd.h.
LCD_FCR_PS_256
#define LCD_FCR_PS_256 0x8
Definition at line 179 of file lcd.h.
LCD_FCR_PS_32
#define LCD_FCR_PS_32 0x5
Definition at line 176 of file lcd.h.
LCD_FCR_PS_32768
#define LCD_FCR_PS_32768 0xF
Definition at line 186 of file lcd.h.
LCD_FCR_PS_4
#define LCD_FCR_PS_4 0x2
Definition at line 173 of file lcd.h.
LCD_FCR_PS_4096
#define LCD_FCR_PS_4096 0xC
Definition at line 183 of file lcd.h.
LCD_FCR_PS_512
#define LCD_FCR_PS_512 0x9
Definition at line 180 of file lcd.h.
LCD_FCR_PS_64
#define LCD_FCR_PS_64 0x6
Definition at line 177 of file lcd.h.
LCD_FCR_PS_8
#define LCD_FCR_PS_8 0x3
Definition at line 174 of file lcd.h.
LCD_FCR_PS_8192
#define LCD_FCR_PS_8192 0xD
Definition at line 184 of file lcd.h.
LCD_FCR_PS_MASK
#define LCD_FCR_PS_MASK 0xF
Definition at line 170 of file lcd.h.
LCD_FCR_PS_SHIFT
#define LCD_FCR_PS_SHIFT 22
Definition at line 169 of file lcd.h.
LCD_FCR_SOFIE
#define LCD_FCR_SOFIE (1 << 1)
Definition at line 96 of file lcd.h.
LCD_FCR_UDDIE
#define LCD_FCR_UDDIE (1 << 3)
Definition at line 97 of file lcd.h.
LCD_RAM_BASE
#define LCD_RAM_BASE (LCD_BASE + 0x14)
Definition at line 55 of file lcd.h.
LCD_RAM_COM0
#define LCD_RAM_COM0 MMIO64(LCD_RAM_BASE + 0x00)
Definition at line 58 of file lcd.h.
LCD_RAM_COM1
#define LCD_RAM_COM1 MMIO64(LCD_RAM_BASE + 0x08)
Definition at line 60 of file lcd.h.
LCD_RAM_COM2
#define LCD_RAM_COM2 MMIO64(LCD_RAM_BASE + 0x10)
Definition at line 62 of file lcd.h.
LCD_RAM_COM3
#define LCD_RAM_COM3 MMIO64(LCD_RAM_BASE + 0x18)
Definition at line 64 of file lcd.h.
LCD_RAM_COM4
#define LCD_RAM_COM4 MMIO64(LCD_RAM_BASE + 0x20)
Definition at line 66 of file lcd.h.
LCD_RAM_COM5
#define LCD_RAM_COM5 MMIO64(LCD_RAM_BASE + 0x28)
Definition at line 68 of file lcd.h.
LCD_RAM_COM6
#define LCD_RAM_COM6 MMIO64(LCD_RAM_BASE + 0x30)
Definition at line 70 of file lcd.h.
LCD_RAM_COM7
#define LCD_RAM_COM7 MMIO64(LCD_RAM_BASE + 0x38)
Definition at line 72 of file lcd.h.
LCD_SR_ENS
#define LCD_SR_ENS (1 << 0)
Definition at line 189 of file lcd.h.
LCD_SR_FCRSF
#define LCD_SR_FCRSF (1 << 5)
Definition at line 194 of file lcd.h.
LCD_SR_RDY
#define LCD_SR_RDY (1 << 4)
Definition at line 193 of file lcd.h.
LCD_SR_SOF
#define LCD_SR_SOF (1 << 1)
Definition at line 190 of file lcd.h.
LCD_SR_UDD
#define LCD_SR_UDD (1 << 3)
Definition at line 192 of file lcd.h.
LCD_SR_UDR
#define LCD_SR_UDR (1 << 2)
Definition at line 191 of file lcd.h.
Function Documentation
lcd_disable_segment_multiplexing()
void lcd_disable_segment_multiplexing (void)
Definition at line 98 of file lcd.c.
References LCD_CR.
lcd_enable()
void lcd_enable (void)
Definition at line 23 of file lcd.c.
References LCD_CR, and LCD_CR_LCDEN.
lcd_enable_segment_multiplexing()
void lcd_enable_segment_multiplexing (void)
Definition at line 93 of file lcd.c.
References LCD_CR, and LCD_CR_MUX_SEG.
lcd_is_enabled()
int lcd_is_enabled (void)
Definition at line 48 of file lcd.c.
References LCD_SR, and LCD_SR_ENS.
lcd_is_for_update_ready()
int lcd_is_for_update_ready (void)
Definition at line 58 of file lcd.c.
References LCD_SR, and LCD_SR_UDR.
lcd_is_step_up_ready()
int lcd_is_step_up_ready (void)
Definition at line 53 of file lcd.c.
References LCD_SR, and LCD_SR_RDY.
lcd_set_bias()
void lcd_set_bias (uint8_t bias)
Definition at line 69 of file lcd.c.
References LCD_CR, LCD_CR_BIAS_MASK, and LCD_CR_BIAS_SHIFT.
lcd_set_contrast()
void lcd_set_contrast (uint8_t contrast)
Definition at line 63 of file lcd.c.
References LCD_FCR, LCD_FCR_CC_MASK, and LCD_FCR_CC_SHIFT.
lcd_set_divider()
void lcd_set_divider (uint8_t div)
Definition at line 87 of file lcd.c.
References LCD_FCR, LCD_FCR_DIV_MASK, and LCD_FCR_DIV_SHIFT.
Referenced by lcd_set_refresh_frequency().
lcd_set_duty()
void lcd_set_duty (uint8_t duty)
Definition at line 75 of file lcd.c.
References LCD_CR, LCD_CR_DUTY_MASK, and LCD_CR_DUTY_SHIFT.
lcd_set_prescaler()
void lcd_set_prescaler (uint8_t ps)
Definition at line 81 of file lcd.c.
References LCD_FCR, LCD_FCR_PS_MASK, and LCD_FCR_PS_SHIFT.
Referenced by lcd_set_refresh_frequency().
lcd_set_refresh_frequency()
void lcd_set_refresh_frequency (uint32_t frequency)
Definition at line 103 of file lcd.c.
References LCD_CR, LCD_CR_DUTY_1_2, LCD_CR_DUTY_1_3, LCD_CR_DUTY_1_4, LCD_CR_DUTY_1_8, LCD_CR_DUTY_MASK, LCD_CR_DUTY_SHIFT, LCD_CR_DUTY_STATIC, lcd_set_divider(), lcd_set_prescaler(), RCC_CSR, RCC_CSR_RTCSEL_HSE, RCC_CSR_RTCSEL_LSE, RCC_CSR_RTCSEL_LSI, RCC_CSR_RTCSEL_MASK, and RCC_CSR_RTCSEL_SHIFT.
lcd_update()
void lcd_update (void)
Definition at line 28 of file lcd.c.
References LCD_SR, and LCD_SR_UDR.
lcd_wait_for_lcd_enabled()
void lcd_wait_for_lcd_enabled (void)
Definition at line 33 of file lcd.c.
References LCD_SR, and LCD_SR_ENS.
lcd_wait_for_step_up_ready()
void lcd_wait_for_step_up_ready (void)
Definition at line 38 of file lcd.c.
References LCD_SR, and LCD_SR_RDY.
lcd_wait_for_update_ready()
void lcd_wait_for_update_ready (void)
Definition at line 43 of file lcd.c.
References LCD_SR, and LCD_SR_UDR.