libopencm3: CMU Defines
CMU Defines
EFM32 Wonder Gecko Defines
Defined Constants and Types for the EFM32WG Clock Management Unit
Macros
#define CMU_CTRL MMIO32(CMU_BASE + 0x000)
#define CMU_HFCORECLKDIV MMIO32(CMU_BASE + 0x004)
#define CMU_HFPERCLKDIV MMIO32(CMU_BASE + 0x008)
#define CMU_HFRCOCTRL MMIO32(CMU_BASE + 0x00C)
#define CMU_LFRCOCTRL MMIO32(CMU_BASE + 0x010)
#define CMU_AUXHFRCOCTRL MMIO32(CMU_BASE + 0x014)
#define CMU_CALCTRL MMIO32(CMU_BASE + 0x018)
#define CMU_CALCNT MMIO32(CMU_BASE + 0x01C)
#define CMU_OSCENCMD MMIO32(CMU_BASE + 0x020)
#define CMU_CMD MMIO32(CMU_BASE + 0x024)
#define CMU_LFCLKSEL MMIO32(CMU_BASE + 0x028)
#define CMU_STATUS MMIO32(CMU_BASE + 0x02C)
#define CMU_IF MMIO32(CMU_BASE + 0x030)
#define CMU_IFS MMIO32(CMU_BASE + 0x034)
#define CMU_IFC MMIO32(CMU_BASE + 0x038)
#define CMU_IEN MMIO32(CMU_BASE + 0x03C)
#define CMU_HFCORECLKEN0 MMIO32(CMU_BASE + 0x040)
#define CMU_HFPERCLKEN0 MMIO32(CMU_BASE + 0x044)
#define CMU_SYNCBUSY MMIO32(CMU_BASE + 0x050)
#define CMU_FREEZE MMIO32(CMU_BASE + 0x054)
#define CMU_LFACLKEN0 MMIO32(CMU_BASE + 0x058)
#define CMU_LFBCLKEN0 MMIO32(CMU_BASE + 0x060)
#define CMU_LFAPRESC0 MMIO32(CMU_BASE + 0x068)
#define CMU_LFBPRESC0 MMIO32(CMU_BASE + 0x070)
#define CMU_PCNTCTRL MMIO32(CMU_BASE + 0x078)
#define CMU_LCDCTRL MMIO32(CMU_BASE + 0x07C)
#define CMU_ROUTE MMIO32(CMU_BASE + 0x080)
#define CMU_LOCK MMIO32(CMU_BASE + 0x084)
#define CMU_CTRL_HFLE (1 << 30)
#define CMU_CTRL_DBGCLK (1 << 28)
#define CMU_CTRL_CLKOUTSEL1_SHIFT (23)
#define CMU_CTRL_CLKOUTSEL1_MASK (0x7 << CMU_CTRL_CLKOUTSEL1_SHIFT)
#define CMU_CTRL_CLKOUTSEL1(v) (((v) << CMU_CTRL_CLKOUTSEL1_SHIFT) & CMU_CTRL_CLKOUTSEL1_MASK)
#define CMU_CTRL_CLKOUTSEL1_LFRCO 0
#define CMU_CTRL_CLKOUTSEL1_LFXO 1
#define CMU_CTRL_CLKOUTSEL1_HFCLK 2
#define CMU_CTRL_CLKOUTSEL1_LFXOQ 3
#define CMU_CTRL_CLKOUTSEL1_HFXOQ 4
#define CMU_CTRL_CLKOUTSEL1_LFRCOQ 5
#define CMU_CTRL_CLKOUTSEL1_HFRCOQ 6
#define CMU_CTRL_CLKOUTSEL1_AUXHFRCOQ 7
#define CMU_CTRL_CLKOUTSEL0_SHIFT (23)
#define CMU_CTRL_CLKOUTSEL0_MASK (0x7 << CMU_CTRL_CLKOUTSEL0_SHIFT)
#define CMU_CTRL_CLKOUTSEL0(v) (((v) << CMU_CTRL_CLKOUTSEL0_SHIFT) & CMU_CTRL_CLKOUTSEL0_MASK)
#define CMU_CTRL_CLKOUTSEL0_HFRCO 0
#define CMU_CTRL_CLKOUTSEL0_HFXO 1
#define CMU_CTRL_CLKOUTSEL0_HFCLK2 2
#define CMU_CTRL_CLKOUTSEL0_HFCLK4 3
#define CMU_CTRL_CLKOUTSEL0_HFCLK8 4
#define CMU_CTRL_CLKOUTSEL0_HFCLK16 5
#define CMU_CTRL_CLKOUTSEL0_ULFRCO 6
#define CMU_CTRL_CLKOUTSEL0_AUXHFRCO 7
#define CMU_CTRL_LFXOTIMEOUT_SHIFT (18)
#define CMU_CTRL_LFXOTIMEOUT_MASK (0x3 << CMU_CTRL_LFXOTIMEOUT_SHIFT)
#define CMU_CTRL_LFXOTIMEOUT(v) (((v) << CMU_CTRL_LFXOTIMEOUT_SHIFT) & CMU_CTRL_LFXOTIMEOUT_MASK)
#define CMU_CTRL_LFXOTIMEOUT_8CYCLES 0
#define CMU_CTRL_LFXOTIMEOUT_1KCYCLES 1
#define CMU_CTRL_LFXOTIMEOUT_16KCYCLES 2
#define CMU_CTRL_LFXOTIMEOUT_32KCYCLES 3
#define CMU_CTRL_LFXOBUFCUR (1 << 17)
#define CMU_CTRL_HFCLKDIV_SHIFT (14)
#define CMU_CTRL_HFCLKDIV_MASK (0x7 << CMU_CTRL_HFCLKDIV_SHIFT)
#define CMU_CTRL_HFCLKDIV(v) (((v) << CMU_CTRL_HFCLKDIV_SHIFT) & CMU_CTRL_HFCLKDIV_MASK)
#define CMU_CTRL_HFCLKDIV_NODIV 0
#define CMU_CTRL_HFCLKDIV_DIV2 1
#define CMU_CTRL_HFCLKDIV_DIV3 2
#define CMU_CTRL_HFCLKDIV_DIV4 3
#define CMU_CTRL_HFCLKDIV_DIV5 4
#define CMU_CTRL_HFCLKDIV_DIV6 5
#define CMU_CTRL_HFCLKDIV_DIV7 6
#define CMU_CTRL_HFCLKDIV_DIV8 7
#define CMU_CTRL_LFXOBOOST (1 << 13)
#define CMU_CTRL_LFXOMODE_SHIFT (11)
#define CMU_CTRL_LFXOMODE_MASK (0x3 << CMU_CTRL_LFXOMODE_SHIFT)
#define CMU_CTRL_LFXOMODE(v) (((v) << CMU_CTRL_LFXOMODE_SHIFT) & CMU_CTRL_LFXOMODE_MASK)
#define CMU_CTRL_LFXOMODE_XTAL 0
#define CMU_CTRL_LFXOMODE_BUFEXTCLK 1
#define CMU_CTRL_LFXOMODE_DIGEXTCLK 2
#define CMU_CTRL_HFXOTIMEOUT_SHIFT (9)
#define CMU_CTRL_HFXOTIMEOUT_MASK (0x3 << CMU_CTRL_HFXOTIMEOUT_SHIFT)
#define CMU_CTRL_HFXOTIMEOUT(v) (((v) << CMU_CTRL_HFXOTIMEOUT_SHIFT) & CMU_CTRL_HFXOTIMEOUT_MASK)
#define CMU_CTRL_HFXOTIMEOUT_8CYCLES 0
#define CMU_CTRL_HFXOTIMEOUT_256CYCLES 1
#define CMU_CTRL_HFXOTIMEOUT_1KCYCLES 2
#define CMU_CTRL_HFXOTIMEOUT_16KCYCLES 3
#define CMU_CTRL_HFXOGLITCHDETEN (1 << 7)
#define CMU_CTRL_HFXOBUFCUR_SHIFT (5)
#define CMU_CTRL_HFXOBUFCUR_MASK (0x3 << CMU_CTRL_HFXOBUFCUR_SHIFT)
#define CMU_CTRL_HFXOBUFCUR(v) (((v) << CMU_CTRL_HFXOBUFCUR_SHIFT) & CMU_CTRL_HFXOBUFCUR_MASK)
#define CMU_CTRL_HFXOBUFCUR_BOOSTUPTO32MHZ 1
#define CMU_CTRL_HFXOBUFCUR_BOOSTABOVE32MHZ 3
#define CMU_CTRL_HFXOBOOST_SHIFT (2)
#define CMU_CTRL_HFXOBOOST_MASK (0x3 << CMU_CTRL_HFXOBOOST_SHIFT)
#define CMU_CTRL_HFXOBOOST(v) (((v) << CMU_CTRL_HFXOBOOST_SHIFT) & CMU_CTRL_HFXOBOOST_MASK)
#define CMU_CTRL_HFXOBOOST_50PCENT 0
#define CMU_CTRL_HFXOBOOST_70PCENT 1
#define CMU_CTRL_HFXOBOOST_80PCENT 2
#define CMU_CTRL_HFXOBOOST_100PCENT 3
#define CMU_CTRL_HFXOMODE_SHIFT (0)
#define CMU_CTRL_HFXOMODE_MASK (0x3 << CMU_CTRL_HFXOMODE_SHIFT)
#define CMU_CTRL_HFXOMODE(v) (((v) << CMU_CTRL_HFXOMODE_SHIFT) & CMU_CTRL_HFXOMODE_MASK)
#define CMU_CTRL_HFXOMODE_XTAL 0
#define CMU_CTRL_HFXOMODE_BUFEXTCLK 1
#define CMU_CTRL_HFXOMODE_DIGEXTCLK 2
#define CMU_HFCORECLKDIV_HFCORECLKLEDIV (1 << 8)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_SHIFT (0)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_MASK (0xF << CMU_HFCORECLKDIV_HFCORECLKDIV_SHIFT)
#define CMU_HFCORECLKDIV_HFCORECLKDIV(v)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK CMU_HFCORECLKDIV_HFCORECLKDIV(0)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK2 CMU_HFCORECLKDIV_HFCORECLKDIV(1)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK4 CMU_HFCORECLKDIV_HFCORECLKDIV(2)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK8 CMU_HFCORECLKDIV_HFCORECLKDIV(3)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK16 CMU_HFCORECLKDIV_HFCORECLKDIV(4)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK32 CMU_HFCORECLKDIV_HFCORECLKDIV(5)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK64 CMU_HFCORECLKDIV_HFCORECLKDIV(6)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK128 CMU_HFCORECLKDIV_HFCORECLKDIV(7)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK256 CMU_HFCORECLKDIV_HFCORECLKDIV(8)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK512 CMU_HFCORECLKDIV_HFCORECLKDIV(9)
#define CMU_HFCORECLKDIV_HFCORECLKDIV_NODIV CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV2 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK2
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV4 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK4
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV8 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK8
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV16 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK16
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV32 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK32
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV64 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK64
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV128 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK128
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV256 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK256
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV512 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK512
#define CMU_HFPERCLKDIV_HFPERCLKEN (1 << 8)
#define CMU_HFPERCLKDIV_HFPERCLKDIV_SHIFT (0)
#define CMU_HFPERCLKDIV_HFPERCLKDIV_MASK (0xF << CMU_HFPERCLKDIV_HFPERCLKDIV_SHIFT)
#define CMU_HFPERCLKDIV_HFPERCLKDIV(v)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK CMU_HFPERCLKDIV_HFPERCLKDIV(0)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK2 CMU_HFPERCLKDIV_HFPERCLKDIV(1)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK4 CMU_HFPERCLKDIV_HFPERCLKDIV(2)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK8 CMU_HFPERCLKDIV_HFPERCLKDIV(3)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK16 CMU_HFPERCLKDIV_HFPERCLKDIV(4)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK32 CMU_HFPERCLKDIV_HFPERCLKDIV(5)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK64 CMU_HFPERCLKDIV_HFPERCLKDIV(6)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK128 CMU_HFPERCLKDIV_HFPERCLKDIV(7)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK256 CMU_HFPERCLKDIV_HFPERCLKDIV(8)
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK512 CMU_HFPERCLKDIV_HFPERCLKDIV(9)
#define CMU_HFPERCLKDIV_HFPERCLKDIV_NODIV CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV2 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK2
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV4 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK4
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV8 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK8
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV16 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK16
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV32 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK32
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV64 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK64
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV128 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK128
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV256 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK256
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV512 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK512
#define CMU_HFRCOCTRL_SUDELAY_SHIFT (12)
#define CMU_HFRCOCTRL_SUDELAY_MASK (0x1F << CMU_HFRCOCTRL_SUDELAY_SHIFT)
#define CMU_HFRCOCTRL_SUDELAY(v) ((((v) << CMU_HFRCOCTRL_SUDELAY_SHIFT) & CMU_HFRCOCTRL_SUDELAY_MASK))
#define CMU_HFRCOCTRL_BAND_SHIFT (8)
#define CMU_HFRCOCTRL_BAND_MASK (0x7 << CMU_HFRCOCTRL_BAND_SHIFT)
#define CMU_HFRCOCTRL_BAND(v) (((v) << CMU_HFRCOCTRL_BAND_SHIFT) & CMU_HFRCOCTRL_BAND_MASK)
#define CMU_HFRCOCTRL_BAND_1MHZ 0
#define CMU_HFRCOCTRL_BAND_7MHZ 1
#define CMU_HFRCOCTRL_BAND_11MHZ 2
#define CMU_HFRCOCTRL_BAND_14MHZ 3
#define CMU_HFRCOCTRL_BAND_21MHZ 4
#define CMU_HFRCOCTRL_BAND_28MHZ 5
#define CMU_HFRCOCTRL_TUNING_SHIFT (0)
#define CMU_HFRCOCTRL_TUNING_MASK (0xFF << CMU_HFRCOCTRL_TUNING_SHIFT)
#define CMU_HFRCOCTRL_TUNING(v) (((v) << CMU_HFRCOCTRL_TUNING_SHIFT) & CMU_HFRCOCTRL_TUNING_MASK)
#define CMU_LFRCOCTRL_TUNING_SHIFT (0)
#define CMU_LFRCOCTRL_TUNING_MASK (0xFF << CMU_LFRCOCTRL_TUNING_SHIFT)
#define CMU_LFRCOCTRL_TUNING(v) (((v) << CMU_LFRCOCTRL_TUNING_SHIFT) & CMU_LFRCOCTRL_TUNING_MASK)
#define CMU_AUXHFRCOCTRL_BAND_SHIFT (8)
#define CMU_AUXHFRCOCTRL_BAND_MASK (0x7 << CMU_AUXHFRCOCTRL_BAND_SHIFT)
#define CMU_AUXHFRCOCTRL_BAND(v) (((v) << CMU_AUXHFRCOCTRL_BAND_SHIFT) & CMU_AUXHFRCOCTRL_BAND_MASK)
#define CMU_AUXHFRCOCTRL_BAND_1MHZ 0
#define CMU_AUXHFRCOCTRL_BAND_7MHZ 1
#define CMU_AUXHFRCOCTRL_BAND_11MHZ 2
#define CMU_AUXHFRCOCTRL_BAND_14MHZ 3
#define CMU_AUXHFRCOCTRL_BAND_28MHZ 4
#define CMU_AUXHFRCOCTRL_BAND_21MHZ 5
#define CMU_AUXHFRCOCTRL_TUNING_SHIFT (0)
#define CMU_AUXHFRCOCTRL_TUNING_MASK (0xFF << CMU_AUXHFRCOCTRL_TUNING_SHIFT)
#define CMU_AUXHFRCOCTRL_TUNING(v) (((v) << CMU_AUXHFRCOCTRL_TUNING_SHIFT) & CMU_AUXHFRCOCTRL_TUNING_MASK)
#define CMU_CALCTRL_CONT (1 << 6)
#define CMU_CALCTRL_DOWNSEL_SHIFT (3)
#define CMU_CALCTRL_DOWNSEL_MASK (0x7 << CMU_CALCTRL_DOWNSEL_SHIFT)
#define CMU_CALCTRL_DOWNSEL(v) (((v) << CMU_CALCTRL_DOWNSEL_SHIFT) & CMU_CALCTRL_DOWNSEL_MASK)
#define CMU_CALCTRL_DOWNSEL_HFCLK 0
#define CMU_CALCTRL_DOWNSEL_HFXO 1
#define CMU_CALCTRL_DOWNSEL_LFXO 2
#define CMU_CALCTRL_DOWNSEL_HFRCO 3
#define CMU_CALCTRL_DOWNSEL_LFRCO 4
#define CMU_CALCTRL_DOWNSEL_AUXHFRCO 5
#define CMU_CALCTRL_UPSEL_SHIFT (3)
#define CMU_CALCTRL_UPSEL_MASK (0x7 << CMU_CALCTRL_UPSEL_SHIFT)
#define CMU_CALCTRL_UPSEL(v) (((v) << CMU_CALCTRL_UPSEL_SHIFT) & CMU_CALCTRL_UPSEL_MASK)
#define CMU_CALCTRL_UPSEL_HFXO 0
#define CMU_CALCTRL_UPSEL_LFXO 1
#define CMU_CALCTRL_UPSEL_HFRCO 2
#define CMU_CALCTRL_UPSEL_LFRCO 3
#define CMU_CALCTRL_UPSEL_AUXHFRCO 4
#define CMU_CALCNT_CALCNT_SHIFT (0)
#define CMU_CALCNT_CALCNT_MASK (0xFFFFF << CMU_CALCNT_CALCNT_SHIFT)
#define CMU_CALCNT_CALCNT(v) (((v) << CMU_CALCNT_CALCNT_SHIFT) & CMU_CALCNT_CALCNT_MASK)
#define CMU_OSCENCMD_LFXODIS (1 << 9)
#define CMU_OSCENCMD_LFXOEN (1 << 8)
#define CMU_OSCENCMD_LFRCODIS (1 << 7)
#define CMU_OSCENCMD_LFRCOEN (1 << 6)
#define CMU_OSCENCMD_AUXHFRCODIS (1 << 5)
#define CMU_OSCENCMD_AUXHFRCOEN (1 << 4)
#define CMU_OSCENCMD_HFXODIS (1 << 3)
#define CMU_OSCENCMD_HFXOEN (1 << 2)
#define CMU_OSCENCMD_HFRCODIS (1 << 1)
#define CMU_OSCENCMD_HFRCOEN (1 << 0)
#define CMU_CMD_USBCCLKSEL_SHIFT (5)
#define CMU_CMD_USBCCLKSEL_MASK (0x3 << CMU_CMD_USBCCLKSEL_SHIFT)
#define CMU_CMD_USBCCLKSEL(v) (((v) << CMU_CMD_USBCCLKSEL_SHIFT) & CMU_CMD_USBCCLKSEL_MASK)
#define CMU_CMD_USBCCLKSEL_HFCLKNODIV 1
#define CMU_CMD_USBCCLKSEL_LFXO 2
#define CMU_CMD_USBCCLKSEL_LFRCO 3
#define CMU_CMD_CALSTOP (1 << 4)
#define CMU_CMD_CALSTART (1 << 3)
#define CMU_CMD_HFCLKSEL_SHIFT (0)
#define CMU_CMD_HFCLKSEL_MASK (0x7 << CMU_CMD_HFCLKSEL_SHIFT)
#define CMU_CMD_HFCLKSEL(v) (((v) << CMU_CMD_HFCLKSEL_SHIFT) & CMU_CMD_HFCLKSEL_MASK)
#define CMU_CMD_HFCLKSEL_HFRCO 1
#define CMU_CMD_HFCLKSEL_HFXO 2
#define CMU_CMD_HFCLKSEL_LFRCO 3
#define CMU_CMD_HFCLKSEL_LFXO 4
#define CMU_LFCLKSEL_LFBE (1 << 20)
#define CMU_LFCLKSEL_LFAE (1 << 16)
#define CMU_LFCLKSEL_LFB_SHIFT (2)
#define CMU_LFCLKSEL_LFB_MASK (0x3 << CMU_LFCLKSEL_LFB_MASK)
#define CMU_LFCLKSEL_LFB(v) (((v) << CMU_LFCLKSEL_LFB_MASK) & CMU_LFCLKSEL_LFB_MASK)
#define CMU_LFCLKSEL_LFA_SHIFT (0)
#define CMU_LFCLKSEL_LFA_MASK (0x3 << CMU_LFCLKSEL_LFA_MASK)
#define CMU_LFCLKSEL_LFA(v) (((v) << CMU_LFCLKSEL_LFA_MASK) & CMU_LFCLKSEL_LFA_MASK)
#define CMU_STATUS_USBCLFRCOSEL (1 << 17)
#define CMU_STATUS_USBCLFXOSEL (1 << 16)
#define CMU_STATUS_USBCHFCLKSEL (1 << 15)
#define CMU_STATUS_CALBSY (1 << 14)
#define CMU_STATUS_LFXOSEL (1 << 13)
#define CMU_STATUS_LFRCOSEL (1 << 12)
#define CMU_STATUS_HFXOSEL (1 << 11)
#define CMU_STATUS_HFRCOSEL (1 << 10)
#define CMU_STATUS_LFXORDY (1 << 9)
#define CMU_STATUS_LFXOENS (1 << 8)
#define CMU_STATUS_LFRCORDY (1 << 7)
#define CMU_STATUS_LFRCOENS (1 << 6)
#define CMU_STATUS_AUXHFRCORDY (1 << 5)
#define CMU_STATUS_AUXHFRCOENS (1 << 4)
#define CMU_STATUS_HFXORDY (1 << 3)
#define CMU_STATUS_HFXOENS (1 << 2)
#define CMU_STATUS_HFRCORDY (1 << 1)
#define CMU_STATUS_HFRCOENS (1 << 0)
#define CMU_IF_USBCHFCLKSEL (1 << 7)
#define CMU_IF_CALOF (1 << 6)
#define CMU_IF_CALRDY (1 << 5)
#define CMU_IF_AUXHFRCORDY (1 << 4)
#define CMU_IF_LFXORDY (1 << 3)
#define CMU_IF_LFRCORDY (1 << 2)
#define CMU_IF_HFXORDY (1 << 1)
#define CMU_IF_HFRCORDY (1 << 0)
#define CMU_IFS_USBCHFCLKSEL (1 << 7)
#define CMU_IFS_CALOF (1 << 6)
#define CMU_IFS_CALRDY (1 << 5)
#define CMU_IFS_AUXHFRCORDY (1 << 4)
#define CMU_IFS_LFXORDY (1 << 3)
#define CMU_IFS_LFRCORDY (1 << 2)
#define CMU_IFS_HFXORDY (1 << 1)
#define CMU_IFS_HFRCORDY (1 << 0)
#define CMU_IFC_USBCHFCLKSEL (1 << 7)
#define CMU_IFC_CALOF (1 << 6)
#define CMU_IFC_CALRDY (1 << 5)
#define CMU_IFC_AUXHFRCORDY (1 << 4)
#define CMU_IFC_LFXORDY (1 << 3)
#define CMU_IFC_LFRCORDY (1 << 2)
#define CMU_IFC_HFXORDY (1 << 1)
#define CMU_IFC_HFRCORDY (1 << 0)
#define CMU_IEN_USBCHFCLKSEL (1 << 7)
#define CMU_IEN_CALOF (1 << 6)
#define CMU_IEN_CALRDY (1 << 5)
#define CMU_IEN_AUXHFRCORDY (1 << 4)
#define CMU_IEN_LFXORDY (1 << 3)
#define CMU_IEN_LFRCORDY (1 << 2)
#define CMU_IEN_HFXORDY (1 << 1)
#define CMU_IEN_HFRCORDY (1 << 0)
#define CMU_HFCORECLKEN0_EBI (1 << 5)
#define CMU_HFCORECLKEN0_LE (1 << 4)
#define CMU_HFCORECLKEN0_USB (1 << 3)
#define CMU_HFCORECLKEN0_USBC (1 << 2)
#define CMU_HFCORECLKEN0_AES (1 << 1)
#define CMU_HFCORECLKEN0_DMA (1 << 0)
#define CMU_HFPERCLKEN0_DAC0 (1 << 17)
#define CMU_HFPERCLKEN0_ADC0 (1 << 16)
#define CMU_HFPERCLKEN0_PRS (1 << 15)
#define CMU_HFPERCLKEN0_VCMP (1 << 14)
#define CMU_HFPERCLKEN0_GPIO (1 << 13)
#define CMU_HFPERCLKEN0_I2C1 (1 << 12)
#define CMU_HFPERCLKEN0_I2C0 (1 << 11)
#define CMU_HFPERCLKEN0_ACMP1 (1 << 10)
#define CMU_HFPERCLKEN0_ACMP0 (1 << 9)
#define CMU_HFPERCLKEN0_TIMER3 (1 << 8)
#define CMU_HFPERCLKEN0_TIMER2 (1 << 7)
#define CMU_HFPERCLKEN0_TIMER1 (1 << 6)
#define CMU_HFPERCLKEN0_TIMER0 (1 << 5)
#define CMU_HFPERCLKEN0_UART1 (1 << 4)
#define CMU_HFPERCLKEN0_UART0 (1 << 3)
#define CMU_HFPERCLKEN0_USART2 (1 << 2)
#define CMU_HFPERCLKEN0_USART1 (1 << 1)
#define CMU_HFPERCLKEN0_USART0 (1 << 0)
#define CMU_SYNCBUSY_LFBPRESC0 (1 << 6)
#define CMU_SYNCBUSY_LFBCLKEN0 (1 << 4)
#define CMU_SYNCBUSY_LFAPRESC0 (1 << 2)
#define CMU_SYNCBUSY_LFACLKEN0 (1 << 0)
#define CMU_FREEZE_REGFREEZE (1 << 0)
#define CMU_LFACLKEN0_LCD (1 << 3)
#define CMU_LFACLKEN0_LETIMER0 (1 << 2)
#define CMU_LFACLKEN0_RTC (1 << 1)
#define CMU_LFACLKEN0_LESENSE (1 << 0)
#define CMU_LFBCLKEN0_LEUART1 (1 << 1)
#define CMU_LFBCLKEN0_LEUART0 (1 << 0)
#define CMU_LFAPRESC0_LCD_SHIFT (12)
#define CMU_LFAPRESC0_LCD_MASK (0x3 << CMU_LFAPRESC0_LCD_SHIFT)
#define CMU_LFAPRESC0_LCD(v) (((v) << CMU_LFAPRESC0_LCD_SHIFT) & CMU_LFAPRESC0_LCD_MASK)
#define CMU_LFAPRESC0_LCD_DIV16 0
#define CMU_LFAPRESC0_LCD_DIV32 1
#define CMU_LFAPRESC0_LCD_DIV64 2
#define CMU_LFAPRESC0_LCD_DIV128 3
#define CMU_LFAPRESC0_LETIMER0_SHIFT (8)
#define CMU_LFAPRESC0_LETIMER0_MASK (0xF << CMU_LFAPRESC0_LETIMER0_SHIFT)
#define CMU_LFAPRESC0_LETIMER0(v) (((v) << CMU_LFAPRESC0_LETIMER0_SHIFT) & CMU_LFAPRESC0_LETIMER0_MASK)
#define CMU_LFAPRESC0_LETIMER0_DIV1 0
#define CMU_LFAPRESC0_LETIMER0_DIV2 1
#define CMU_LFAPRESC0_LETIMER0_DIV4 2
#define CMU_LFAPRESC0_LETIMER0_DIV8 3
#define CMU_LFAPRESC0_LETIMER0_DIV16 4
#define CMU_LFAPRESC0_LETIMER0_DIV32 5
#define CMU_LFAPRESC0_LETIMER0_DIV64 6
#define CMU_LFAPRESC0_LETIMER0_DIV128 7
#define CMU_LFAPRESC0_LETIMER0_DIV256 8
#define CMU_LFAPRESC0_LETIMER0_DIV512 9
#define CMU_LFAPRESC0_LETIMER0_DIV1024 10
#define CMU_LFAPRESC0_LETIMER0_DIV2048 11
#define CMU_LFAPRESC0_LETIMER0_DIV4096 12
#define CMU_LFAPRESC0_LETIMER0_DIV8192 13
#define CMU_LFAPRESC0_LETIMER0_DIV16384 14
#define CMU_LFAPRESC0_LETIMER0_DIV32768 15
#define CMU_LFAPRESC0_LETIMER0_NODIV CMU_LFAPRESC0_LETIMER0_DIV1
#define CMU_LFAPRESC0_RTC_SHIFT (4)
#define CMU_LFAPRESC0_RTC_MASK (0xF << CMU_LFAPRESC0_RTC_SHIFT)
#define CMU_LFAPRESC0_RTC(v) (((v) << CMU_LFAPRESC0_RTC_SHIFT) & CMU_LFAPRESC0_RTC_MASK)
#define CMU_LFAPRESC0_RTC_DIV1 0
#define CMU_LFAPRESC0_RTC_DIV2 1
#define CMU_LFAPRESC0_RTC_DIV4 2
#define CMU_LFAPRESC0_RTC_DIV8 3
#define CMU_LFAPRESC0_RTC_DIV16 4
#define CMU_LFAPRESC0_RTC_DIV32 5
#define CMU_LFAPRESC0_RTC_DIV64 6
#define CMU_LFAPRESC0_RTC_DIV128 7
#define CMU_LFAPRESC0_RTC_DIV256 8
#define CMU_LFAPRESC0_RTC_DIV512 9
#define CMU_LFAPRESC0_RTC_DIV1024 10
#define CMU_LFAPRESC0_RTC_DIV2048 11
#define CMU_LFAPRESC0_RTC_DIV4096 12
#define CMU_LFAPRESC0_RTC_DIV8192 13
#define CMU_LFAPRESC0_RTC_DIV16384 14
#define CMU_LFAPRESC0_RTC_DIV32768 15
#define CMU_LFAPRESC0_RTC_NODIV CMU_LFAPRESC0_RTC_DIV1
#define CMU_LFAPRESC0_LESENSE_SHIFT (12)
#define CMU_LFAPRESC0_LESENSE_MASK (0x3 << CMU_LFAPRESC0_LESENSE_SHIFT)
#define CMU_LFAPRESC0_LESENSE(v) (((v) << CMU_LFAPRESC0_LESENSE_SHIFT) & CMU_LFAPRESC0_LESENSE_MASK)
#define CMU_LFAPRESC0_LESENSE_DIV1 0
#define CMU_LFAPRESC0_LESENSE_DIV2 1
#define CMU_LFAPRESC0_LESENSE_DIV4 2
#define CMU_LFAPRESC0_LESENSE_DIV8 3
#define CMU_LFAPRESC0_LESENSE_NODIV CMU_LFAPRESC0_LESENSE_DIV1
#define CMU_LFBPRESC0_LEUART1_SHIFT (4)
#define CMU_LFBPRESC0_LEUART1_MASK (0x3 << CMU_LFBPRESC0_LEUART1_SHIFT)
#define CMU_LFBPRESC0_LEUART1(v) (((v) << CMU_LFBPRESC0_LEUART1_SHIFT) & CMU_LFBPRESC0_LEUART1_MASK)
#define CMU_LFBPRESC0_LEUART1_DIV1 0
#define CMU_LFBPRESC0_LEUART1_DIV2 1
#define CMU_LFBPRESC0_LEUART1_DIV4 2
#define CMU_LFBPRESC0_LEUART1_DIV8 3
#define CMU_LFBPRESC0_LEUART1_NODIV CMU_LFBPRESC0_LEUART1_DIV1
#define CMU_LFBPRESC0_LEUART0_SHIFT (0)
#define CMU_LFBPRESC0_LEUART0_MASK (0x3 << CMU_LFBPRESC0_LEUART0_SHIFT)
#define CMU_LFBPRESC0_LEUART0(v) (((v) << CMU_LFBPRESC0_LEUART0_SHIFT) & CMU_LFBPRESC0_LEUART0_MASK)
#define CMU_LFBPRESC0_LEUART0_DIV1 0
#define CMU_LFBPRESC0_LEUART0_DIV2 1
#define CMU_LFBPRESC0_LEUART0_DIV4 2
#define CMU_LFBPRESC0_LEUART0_DIV8 3
#define CMU_LFBPRESC0_LEUART0_NODIV CMU_LFBPRESC0_LEUART0_DIV1
#define CMU_PCNTCTRL_PCNT2CLKSE (1 << 5)
#define CMU_PCNTCTRL_PCNT2CLKEN (1 << 4)
#define CMU_PCNTCTRL_PCNT1CLKSEL (1 << 3)
#define CMU_PCNTCTRL_PCNT1CLKEN (1 << 2)
#define CMU_PCNTCTRL_PCNT0CLKSEL (1 << 1)
#define CMU_PCNTCTRL_PCNT0CLKEN (1 << 0)
#define CMU_LCDCTRL_VBFDIV_SHIFT (4)
#define CMU_LCDCTRL_VBFDIV_MASK (0xF << CMU_LCDCTRL_VBFDIV_SHIFT)
#define CMU_LCDCTRL_VBFDIV(v) (((v) << CMU_LCDCTRL_VBFDIV_SHIFT) & CMU_LCDCTRL_VBFDIV_MASK)
#define CMU_LCDCTRL_VBFDIV_DIV1 0
#define CMU_LCDCTRL_VBFDIV_DIV2 1
#define CMU_LCDCTRL_VBFDIV_DIV4 2
#define CMU_LCDCTRL_VBFDIV_DIV8 3
#define CMU_LCDCTRL_VBFDIV_DIV16 4
#define CMU_LCDCTRL_VBFDIV_DIV32 5
#define CMU_LCDCTRL_VBFDIV_DIV64 6
#define CMU_LCDCTRL_VBFDIV_DIV128 7
#define CMU_LCDCTRL_VBFDIV_NODIV CMU_LCDCTRL_VBFDIV_DIV1
#define CMU_LCDCTRL_VBOOSTEN (1 << 3)
#define CMU_LCDCTRL_FDIV_SHIFT (0)
#define CMU_LCDCTRL_FDIV_MASK (0x3 << CMU_LCDCTRL_FDIV_SHIFT)
#define CMU_LCDCTRL_FDIV(v) (((v) & CMU_LCDCTRL_FDIV_MASK) << CMU_LCDCTRL_FDIV_SHIFT)
#define CMU_ROUTE_LOCATION_SHIFT (2)
#define CMU_ROUTE_LOCATION_MASK (0x7 << CMU_ROUTE_LOCATION_SHIFT)
#define CMU_ROUTE_LOCATION_LOCx(i) (((i) << CMU_ROUTE_LOCATION_SHIFT) & CMU_ROUTE_LOCATION_MASK)
#define CMU_ROUTE_LOCATION_LOC0 0
#define CMU_ROUTE_LOCATION_LOC1 1
#define CMU_ROUTE_LOCATION_LOC2 2
#define CMU_ROUTE_CLKOUT1PEN (1 << 1)
#define CMU_ROUTE_CLKOUT0PEN (1 << 0)
#define CMU_LOCK_LOCKKEY_SHIFT (0)
#define CMU_LOCK_LOCKKEY_MASK (0xFFFF << CMU_LOCK_LOCKKEY_SHIFT)
#define CMU_LOCK_LOCKKEY_UNLOCKED (0x0000 << CMU_LOCK_LOCKKEY_SHIFT)
#define CMU_LOCK_LOCKKEY_LOCKED (0x0001 << CMU_LOCK_LOCKKEY_SHIFT)
#define CMU_LOCK_LOCKKEY_LOCK (0x0000 << CMU_LOCK_LOCKKEY_SHIFT)
#define CMU_LOCK_LOCKKEY_UNLOCK (0x580E << CMU_LOCK_LOCKKEY_SHIFT)
#define _REG_BIT(base, bit) (((base) << 5) + (bit))
Enumerations
enum cmu_periph_clken {
CMU_PCNT2 = _REG_BIT(0x078, 4) , CMU_PCNT1 = _REG_BIT(0x078, 2) , CMU_PCNT0 = _REG_BIT(0x078, 0) , CMU_LEUART1 = _REG_BIT(0x060, 1) ,
CMU_LEUART0 = _REG_BIT(0x060, 0) , CMU_LCD = _REG_BIT(0x058, 3) , CMU_LETIMER0 = _REG_BIT(0x058, 2) , CMU_RTC = _REG_BIT(0x058, 1) ,
CMU_LESENSE = _REG_BIT(0x058, 0) , CMU_DAC0 = _REG_BIT(0x044, 17) , CMU_ADC0 = _REG_BIT(0x044, 16) , CMU_PRS = _REG_BIT(0x044, 15) ,
CMU_VCMP = _REG_BIT(0x044, 14) , CMU_GPIO = _REG_BIT(0x044, 13) , CMU_I2C1 = _REG_BIT(0x044, 12) , CMU_I2C0 = _REG_BIT(0x044, 11) ,
CMU_ACMP1 = _REG_BIT(0x044, 10) , CMU_ACMP0 = _REG_BIT(0x044, 9) , CMU_TIMER3 = _REG_BIT(0x044, 8) , CMU_TIMER2 = _REG_BIT(0x044, 7) ,
CMU_TIMER1 = _REG_BIT(0x044, 6) , CMU_TIMER0 = _REG_BIT(0x044, 5) , CMU_UART1 = _REG_BIT(0x044, 4) , CMU_UART0 = _REG_BIT(0x044, 3) ,
CMU_USART2 = _REG_BIT(0x044, 2) , CMU_USART1 = _REG_BIT(0x044, 1) , CMU_USART0 = _REG_BIT(0x044, 0) , CMU_EBI = _REG_BIT(0x040, 5) ,
CMU_LE = _REG_BIT(0x040, 4) , CMU_USB = _REG_BIT(0x040, 3) , CMU_USBC = _REG_BIT(0x040, 2) , CMU_AES = _REG_BIT(0x040, 1) ,
CMU_DMA = _REG_BIT(0x040, 0)
}
enum cmu_osc {
HFRCO , LFRCO , ULFRCO , HFXO ,
LFXO , AUXHFRCO
}
Functions
void cmu_enable_lock (void)
Enable CMU registers lock.
void cmu_disable_lock (void)
Disable CMU registers lock.
bool cmu_get_lock_flag (void)
Get CMU register lock flag.
void cmu_periph_clock_enable (enum cmu_periph_clken periph)
Enable Peripheral Clock in running mode.
void cmu_periph_clock_disable (enum cmu_periph_clken periph)
Disable Peripheral Clock in running mode.
void cmu_osc_on (enum cmu_osc osc)
Turn on Oscillator.
void cmu_osc_off (enum cmu_osc osc)
Turn off Oscillator.
bool cmu_osc_ready_flag (enum cmu_osc osc)
Get Oscillator read flag.
void cmu_wait_for_osc_ready (enum cmu_osc osc)
Wait till oscillator is not ready.
void cmu_set_hfclk_source (enum cmu_osc osc)
Set HFCLK clock source.
void cmu_set_usbclk_source (enum cmu_osc osc)
enum cmu_osc cmu_get_hfclk_source (void)
void cmu_clock_setup_in_hfxo_out_48mhz (void)
HFXO output 48Mhz and core running at 48Mhz.
Detailed Description
Defined Constants and Types for the EFM32WG Clock Management Unit
LGPL License Terms libopencm3 License
Macro Definition Documentation
_REG_BIT
#define _REG_BIT (base, bit) (((base) << 5) + (bit))
Definition at line 615 of file cmu_common.h.
CMU_AUXHFRCOCTRL
#define CMU_AUXHFRCOCTRL MMIO32(CMU_BASE + 0x014)
Definition at line 34 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND
#define CMU_AUXHFRCOCTRL_BAND (v) (((v) << CMU_AUXHFRCOCTRL_BAND_SHIFT) & CMU_AUXHFRCOCTRL_BAND_MASK)
Definition at line 282 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_11MHZ
#define CMU_AUXHFRCOCTRL_BAND_11MHZ 2
Definition at line 286 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_14MHZ
#define CMU_AUXHFRCOCTRL_BAND_14MHZ 3
Definition at line 287 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_1MHZ
#define CMU_AUXHFRCOCTRL_BAND_1MHZ 0
Definition at line 284 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_21MHZ
#define CMU_AUXHFRCOCTRL_BAND_21MHZ 5
Definition at line 289 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_28MHZ
#define CMU_AUXHFRCOCTRL_BAND_28MHZ 4
Definition at line 288 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_7MHZ
#define CMU_AUXHFRCOCTRL_BAND_7MHZ 1
Definition at line 285 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_MASK
#define CMU_AUXHFRCOCTRL_BAND_MASK (0x7 << CMU_AUXHFRCOCTRL_BAND_SHIFT)
Definition at line 281 of file cmu_common.h.
CMU_AUXHFRCOCTRL_BAND_SHIFT
#define CMU_AUXHFRCOCTRL_BAND_SHIFT (8)
Definition at line 280 of file cmu_common.h.
CMU_AUXHFRCOCTRL_TUNING
#define CMU_AUXHFRCOCTRL_TUNING (v) (((v) << CMU_AUXHFRCOCTRL_TUNING_SHIFT) & CMU_AUXHFRCOCTRL_TUNING_MASK)
Definition at line 293 of file cmu_common.h.
CMU_AUXHFRCOCTRL_TUNING_MASK
#define CMU_AUXHFRCOCTRL_TUNING_MASK (0xFF << CMU_AUXHFRCOCTRL_TUNING_SHIFT)
Definition at line 292 of file cmu_common.h.
CMU_AUXHFRCOCTRL_TUNING_SHIFT
#define CMU_AUXHFRCOCTRL_TUNING_SHIFT (0)
Definition at line 291 of file cmu_common.h.
CMU_CALCNT
#define CMU_CALCNT MMIO32(CMU_BASE + 0x01C)
Definition at line 36 of file cmu_common.h.
CMU_CALCNT_CALCNT
#define CMU_CALCNT_CALCNT (v) (((v) << CMU_CALCNT_CALCNT_SHIFT) & CMU_CALCNT_CALCNT_MASK)
Definition at line 323 of file cmu_common.h.
CMU_CALCNT_CALCNT_MASK
#define CMU_CALCNT_CALCNT_MASK (0xFFFFF << CMU_CALCNT_CALCNT_SHIFT)
Definition at line 322 of file cmu_common.h.
CMU_CALCNT_CALCNT_SHIFT
#define CMU_CALCNT_CALCNT_SHIFT (0)
Definition at line 321 of file cmu_common.h.
CMU_CALCTRL
#define CMU_CALCTRL MMIO32(CMU_BASE + 0x018)
Definition at line 35 of file cmu_common.h.
CMU_CALCTRL_CONT
#define CMU_CALCTRL_CONT (1 << 6)
Definition at line 297 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL
#define CMU_CALCTRL_DOWNSEL (v) (((v) << CMU_CALCTRL_DOWNSEL_SHIFT) & CMU_CALCTRL_DOWNSEL_MASK)
Definition at line 301 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_AUXHFRCO
#define CMU_CALCTRL_DOWNSEL_AUXHFRCO 5
Definition at line 308 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_HFCLK
#define CMU_CALCTRL_DOWNSEL_HFCLK 0
Definition at line 303 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_HFRCO
#define CMU_CALCTRL_DOWNSEL_HFRCO 3
Definition at line 306 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_HFXO
#define CMU_CALCTRL_DOWNSEL_HFXO 1
Definition at line 304 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_LFRCO
#define CMU_CALCTRL_DOWNSEL_LFRCO 4
Definition at line 307 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_LFXO
#define CMU_CALCTRL_DOWNSEL_LFXO 2
Definition at line 305 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_MASK
#define CMU_CALCTRL_DOWNSEL_MASK (0x7 << CMU_CALCTRL_DOWNSEL_SHIFT)
Definition at line 300 of file cmu_common.h.
CMU_CALCTRL_DOWNSEL_SHIFT
#define CMU_CALCTRL_DOWNSEL_SHIFT (3)
Definition at line 299 of file cmu_common.h.
CMU_CALCTRL_UPSEL
#define CMU_CALCTRL_UPSEL (v) (((v) << CMU_CALCTRL_UPSEL_SHIFT) & CMU_CALCTRL_UPSEL_MASK)
Definition at line 312 of file cmu_common.h.
CMU_CALCTRL_UPSEL_AUXHFRCO
#define CMU_CALCTRL_UPSEL_AUXHFRCO 4
Definition at line 318 of file cmu_common.h.
CMU_CALCTRL_UPSEL_HFRCO
#define CMU_CALCTRL_UPSEL_HFRCO 2
Definition at line 316 of file cmu_common.h.
CMU_CALCTRL_UPSEL_HFXO
#define CMU_CALCTRL_UPSEL_HFXO 0
Definition at line 314 of file cmu_common.h.
CMU_CALCTRL_UPSEL_LFRCO
#define CMU_CALCTRL_UPSEL_LFRCO 3
Definition at line 317 of file cmu_common.h.
CMU_CALCTRL_UPSEL_LFXO
#define CMU_CALCTRL_UPSEL_LFXO 1
Definition at line 315 of file cmu_common.h.
CMU_CALCTRL_UPSEL_MASK
#define CMU_CALCTRL_UPSEL_MASK (0x7 << CMU_CALCTRL_UPSEL_SHIFT)
Definition at line 311 of file cmu_common.h.
CMU_CALCTRL_UPSEL_SHIFT
#define CMU_CALCTRL_UPSEL_SHIFT (3)
Definition at line 310 of file cmu_common.h.
CMU_CMD
#define CMU_CMD MMIO32(CMU_BASE + 0x024)
Definition at line 38 of file cmu_common.h.
CMU_CMD_CALSTART
#define CMU_CMD_CALSTART (1 << 3)
Definition at line 348 of file cmu_common.h.
CMU_CMD_CALSTOP
#define CMU_CMD_CALSTOP (1 << 4)
Definition at line 347 of file cmu_common.h.
CMU_CMD_HFCLKSEL
#define CMU_CMD_HFCLKSEL (v) (((v) << CMU_CMD_HFCLKSEL_SHIFT) & CMU_CMD_HFCLKSEL_MASK)
Definition at line 352 of file cmu_common.h.
CMU_CMD_HFCLKSEL_HFRCO
#define CMU_CMD_HFCLKSEL_HFRCO 1
Definition at line 354 of file cmu_common.h.
CMU_CMD_HFCLKSEL_HFXO
#define CMU_CMD_HFCLKSEL_HFXO 2
Definition at line 355 of file cmu_common.h.
CMU_CMD_HFCLKSEL_LFRCO
#define CMU_CMD_HFCLKSEL_LFRCO 3
Definition at line 356 of file cmu_common.h.
CMU_CMD_HFCLKSEL_LFXO
#define CMU_CMD_HFCLKSEL_LFXO 4
Definition at line 357 of file cmu_common.h.
CMU_CMD_HFCLKSEL_MASK
#define CMU_CMD_HFCLKSEL_MASK (0x7 << CMU_CMD_HFCLKSEL_SHIFT)
Definition at line 351 of file cmu_common.h.
CMU_CMD_HFCLKSEL_SHIFT
#define CMU_CMD_HFCLKSEL_SHIFT (0)
Definition at line 350 of file cmu_common.h.
CMU_CMD_USBCCLKSEL
#define CMU_CMD_USBCCLKSEL (v) (((v) << CMU_CMD_USBCCLKSEL_SHIFT) & CMU_CMD_USBCCLKSEL_MASK)
Definition at line 341 of file cmu_common.h.
CMU_CMD_USBCCLKSEL_HFCLKNODIV
#define CMU_CMD_USBCCLKSEL_HFCLKNODIV 1
Definition at line 343 of file cmu_common.h.
CMU_CMD_USBCCLKSEL_LFRCO
#define CMU_CMD_USBCCLKSEL_LFRCO 3
Definition at line 345 of file cmu_common.h.
CMU_CMD_USBCCLKSEL_LFXO
#define CMU_CMD_USBCCLKSEL_LFXO 2
Definition at line 344 of file cmu_common.h.
CMU_CMD_USBCCLKSEL_MASK
#define CMU_CMD_USBCCLKSEL_MASK (0x3 << CMU_CMD_USBCCLKSEL_SHIFT)
Definition at line 340 of file cmu_common.h.
CMU_CMD_USBCCLKSEL_SHIFT
#define CMU_CMD_USBCCLKSEL_SHIFT (5)
Definition at line 339 of file cmu_common.h.
CMU_CTRL
#define CMU_CTRL MMIO32(CMU_BASE + 0x000)
Definition at line 29 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0
#define CMU_CTRL_CLKOUTSEL0 (v) (((v) << CMU_CTRL_CLKOUTSEL0_SHIFT) & CMU_CTRL_CLKOUTSEL0_MASK)
Definition at line 78 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_AUXHFRCO
#define CMU_CTRL_CLKOUTSEL0_AUXHFRCO 7
Definition at line 87 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_HFCLK16
#define CMU_CTRL_CLKOUTSEL0_HFCLK16 5
Definition at line 85 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_HFCLK2
#define CMU_CTRL_CLKOUTSEL0_HFCLK2 2
Definition at line 82 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_HFCLK4
#define CMU_CTRL_CLKOUTSEL0_HFCLK4 3
Definition at line 83 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_HFCLK8
#define CMU_CTRL_CLKOUTSEL0_HFCLK8 4
Definition at line 84 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_HFRCO
#define CMU_CTRL_CLKOUTSEL0_HFRCO 0
Definition at line 80 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_HFXO
#define CMU_CTRL_CLKOUTSEL0_HFXO 1
Definition at line 81 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_MASK
#define CMU_CTRL_CLKOUTSEL0_MASK (0x7 << CMU_CTRL_CLKOUTSEL0_SHIFT)
Definition at line 77 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_SHIFT
#define CMU_CTRL_CLKOUTSEL0_SHIFT (23)
Definition at line 76 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL0_ULFRCO
#define CMU_CTRL_CLKOUTSEL0_ULFRCO 6
Definition at line 86 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1
#define CMU_CTRL_CLKOUTSEL1 (v) (((v) << CMU_CTRL_CLKOUTSEL1_SHIFT) & CMU_CTRL_CLKOUTSEL1_MASK)
Definition at line 65 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_AUXHFRCOQ
#define CMU_CTRL_CLKOUTSEL1_AUXHFRCOQ 7
Definition at line 74 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_HFCLK
#define CMU_CTRL_CLKOUTSEL1_HFCLK 2
Definition at line 69 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_HFRCOQ
#define CMU_CTRL_CLKOUTSEL1_HFRCOQ 6
Definition at line 73 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_HFXOQ
#define CMU_CTRL_CLKOUTSEL1_HFXOQ 4
Definition at line 71 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_LFRCO
#define CMU_CTRL_CLKOUTSEL1_LFRCO 0
Definition at line 67 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_LFRCOQ
#define CMU_CTRL_CLKOUTSEL1_LFRCOQ 5
Definition at line 72 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_LFXO
#define CMU_CTRL_CLKOUTSEL1_LFXO 1
Definition at line 68 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_LFXOQ
#define CMU_CTRL_CLKOUTSEL1_LFXOQ 3
Definition at line 70 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_MASK
#define CMU_CTRL_CLKOUTSEL1_MASK (0x7 << CMU_CTRL_CLKOUTSEL1_SHIFT)
Definition at line 64 of file cmu_common.h.
CMU_CTRL_CLKOUTSEL1_SHIFT
#define CMU_CTRL_CLKOUTSEL1_SHIFT (23)
Definition at line 63 of file cmu_common.h.
CMU_CTRL_DBGCLK
#define CMU_CTRL_DBGCLK (1 << 28)
Definition at line 60 of file cmu_common.h.
CMU_CTRL_HFCLKDIV
#define CMU_CTRL_HFCLKDIV (v) (((v) << CMU_CTRL_HFCLKDIV_SHIFT) & CMU_CTRL_HFCLKDIV_MASK)
Definition at line 102 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_DIV2
#define CMU_CTRL_HFCLKDIV_DIV2 1
Definition at line 105 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_DIV3
#define CMU_CTRL_HFCLKDIV_DIV3 2
Definition at line 106 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_DIV4
#define CMU_CTRL_HFCLKDIV_DIV4 3
Definition at line 107 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_DIV5
#define CMU_CTRL_HFCLKDIV_DIV5 4
Definition at line 108 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_DIV6
#define CMU_CTRL_HFCLKDIV_DIV6 5
Definition at line 109 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_DIV7
#define CMU_CTRL_HFCLKDIV_DIV7 6
Definition at line 110 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_DIV8
#define CMU_CTRL_HFCLKDIV_DIV8 7
Definition at line 111 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_MASK
#define CMU_CTRL_HFCLKDIV_MASK (0x7 << CMU_CTRL_HFCLKDIV_SHIFT)
Definition at line 101 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_NODIV
#define CMU_CTRL_HFCLKDIV_NODIV 0
Definition at line 104 of file cmu_common.h.
CMU_CTRL_HFCLKDIV_SHIFT
#define CMU_CTRL_HFCLKDIV_SHIFT (14)
Definition at line 100 of file cmu_common.h.
CMU_CTRL_HFLE
#define CMU_CTRL_HFLE (1 << 30)
Definition at line 59 of file cmu_common.h.
CMU_CTRL_HFXOBOOST
#define CMU_CTRL_HFXOBOOST (v) (((v) << CMU_CTRL_HFXOBOOST_SHIFT) & CMU_CTRL_HFXOBOOST_MASK)
Definition at line 143 of file cmu_common.h.
CMU_CTRL_HFXOBOOST_100PCENT
#define CMU_CTRL_HFXOBOOST_100PCENT 3
Definition at line 148 of file cmu_common.h.
CMU_CTRL_HFXOBOOST_50PCENT
#define CMU_CTRL_HFXOBOOST_50PCENT 0
Definition at line 145 of file cmu_common.h.
CMU_CTRL_HFXOBOOST_70PCENT
#define CMU_CTRL_HFXOBOOST_70PCENT 1
Definition at line 146 of file cmu_common.h.
CMU_CTRL_HFXOBOOST_80PCENT
#define CMU_CTRL_HFXOBOOST_80PCENT 2
Definition at line 147 of file cmu_common.h.
CMU_CTRL_HFXOBOOST_MASK
#define CMU_CTRL_HFXOBOOST_MASK (0x3 << CMU_CTRL_HFXOBOOST_SHIFT)
Definition at line 142 of file cmu_common.h.
CMU_CTRL_HFXOBOOST_SHIFT
#define CMU_CTRL_HFXOBOOST_SHIFT (2)
Definition at line 141 of file cmu_common.h.
CMU_CTRL_HFXOBUFCUR
#define CMU_CTRL_HFXOBUFCUR (v) (((v) << CMU_CTRL_HFXOBUFCUR_SHIFT) & CMU_CTRL_HFXOBUFCUR_MASK)
Definition at line 136 of file cmu_common.h.
CMU_CTRL_HFXOBUFCUR_BOOSTABOVE32MHZ
#define CMU_CTRL_HFXOBUFCUR_BOOSTABOVE32MHZ 3
Definition at line 139 of file cmu_common.h.
CMU_CTRL_HFXOBUFCUR_BOOSTUPTO32MHZ
#define CMU_CTRL_HFXOBUFCUR_BOOSTUPTO32MHZ 1
Definition at line 138 of file cmu_common.h.
CMU_CTRL_HFXOBUFCUR_MASK
#define CMU_CTRL_HFXOBUFCUR_MASK (0x3 << CMU_CTRL_HFXOBUFCUR_SHIFT)
Definition at line 135 of file cmu_common.h.
CMU_CTRL_HFXOBUFCUR_SHIFT
#define CMU_CTRL_HFXOBUFCUR_SHIFT (5)
Definition at line 134 of file cmu_common.h.
CMU_CTRL_HFXOGLITCHDETEN
#define CMU_CTRL_HFXOGLITCHDETEN (1 << 7)
Definition at line 132 of file cmu_common.h.
CMU_CTRL_HFXOMODE
#define CMU_CTRL_HFXOMODE (v) (((v) << CMU_CTRL_HFXOMODE_SHIFT) & CMU_CTRL_HFXOMODE_MASK)
Definition at line 152 of file cmu_common.h.
CMU_CTRL_HFXOMODE_BUFEXTCLK
#define CMU_CTRL_HFXOMODE_BUFEXTCLK 1
Definition at line 155 of file cmu_common.h.
CMU_CTRL_HFXOMODE_DIGEXTCLK
#define CMU_CTRL_HFXOMODE_DIGEXTCLK 2
Definition at line 156 of file cmu_common.h.
CMU_CTRL_HFXOMODE_MASK
#define CMU_CTRL_HFXOMODE_MASK (0x3 << CMU_CTRL_HFXOMODE_SHIFT)
Definition at line 151 of file cmu_common.h.
CMU_CTRL_HFXOMODE_SHIFT
#define CMU_CTRL_HFXOMODE_SHIFT (0)
Definition at line 150 of file cmu_common.h.
CMU_CTRL_HFXOMODE_XTAL
#define CMU_CTRL_HFXOMODE_XTAL 0
Definition at line 154 of file cmu_common.h.
CMU_CTRL_HFXOTIMEOUT
#define CMU_CTRL_HFXOTIMEOUT (v) (((v) << CMU_CTRL_HFXOTIMEOUT_SHIFT) & CMU_CTRL_HFXOTIMEOUT_MASK)
Definition at line 125 of file cmu_common.h.
CMU_CTRL_HFXOTIMEOUT_16KCYCLES
#define CMU_CTRL_HFXOTIMEOUT_16KCYCLES 3
Definition at line 130 of file cmu_common.h.
CMU_CTRL_HFXOTIMEOUT_1KCYCLES
#define CMU_CTRL_HFXOTIMEOUT_1KCYCLES 2
Definition at line 129 of file cmu_common.h.
CMU_CTRL_HFXOTIMEOUT_256CYCLES
#define CMU_CTRL_HFXOTIMEOUT_256CYCLES 1
Definition at line 128 of file cmu_common.h.
CMU_CTRL_HFXOTIMEOUT_8CYCLES
#define CMU_CTRL_HFXOTIMEOUT_8CYCLES 0
Definition at line 127 of file cmu_common.h.
CMU_CTRL_HFXOTIMEOUT_MASK
#define CMU_CTRL_HFXOTIMEOUT_MASK (0x3 << CMU_CTRL_HFXOTIMEOUT_SHIFT)
Definition at line 124 of file cmu_common.h.
CMU_CTRL_HFXOTIMEOUT_SHIFT
#define CMU_CTRL_HFXOTIMEOUT_SHIFT (9)
Definition at line 123 of file cmu_common.h.
CMU_CTRL_LFXOBOOST
#define CMU_CTRL_LFXOBOOST (1 << 13)
Definition at line 113 of file cmu_common.h.
CMU_CTRL_LFXOBUFCUR
#define CMU_CTRL_LFXOBUFCUR (1 << 17)
Definition at line 98 of file cmu_common.h.
CMU_CTRL_LFXOMODE
#define CMU_CTRL_LFXOMODE (v) (((v) << CMU_CTRL_LFXOMODE_SHIFT) & CMU_CTRL_LFXOMODE_MASK)
Definition at line 117 of file cmu_common.h.
CMU_CTRL_LFXOMODE_BUFEXTCLK
#define CMU_CTRL_LFXOMODE_BUFEXTCLK 1
Definition at line 120 of file cmu_common.h.
CMU_CTRL_LFXOMODE_DIGEXTCLK
#define CMU_CTRL_LFXOMODE_DIGEXTCLK 2
Definition at line 121 of file cmu_common.h.
CMU_CTRL_LFXOMODE_MASK
#define CMU_CTRL_LFXOMODE_MASK (0x3 << CMU_CTRL_LFXOMODE_SHIFT)
Definition at line 116 of file cmu_common.h.
CMU_CTRL_LFXOMODE_SHIFT
#define CMU_CTRL_LFXOMODE_SHIFT (11)
Definition at line 115 of file cmu_common.h.
CMU_CTRL_LFXOMODE_XTAL
#define CMU_CTRL_LFXOMODE_XTAL 0
Definition at line 119 of file cmu_common.h.
CMU_CTRL_LFXOTIMEOUT
#define CMU_CTRL_LFXOTIMEOUT (v) (((v) << CMU_CTRL_LFXOTIMEOUT_SHIFT) & CMU_CTRL_LFXOTIMEOUT_MASK)
Definition at line 91 of file cmu_common.h.
CMU_CTRL_LFXOTIMEOUT_16KCYCLES
#define CMU_CTRL_LFXOTIMEOUT_16KCYCLES 2
Definition at line 95 of file cmu_common.h.
CMU_CTRL_LFXOTIMEOUT_1KCYCLES
#define CMU_CTRL_LFXOTIMEOUT_1KCYCLES 1
Definition at line 94 of file cmu_common.h.
CMU_CTRL_LFXOTIMEOUT_32KCYCLES
#define CMU_CTRL_LFXOTIMEOUT_32KCYCLES 3
Definition at line 96 of file cmu_common.h.
CMU_CTRL_LFXOTIMEOUT_8CYCLES
#define CMU_CTRL_LFXOTIMEOUT_8CYCLES 0
Definition at line 93 of file cmu_common.h.
CMU_CTRL_LFXOTIMEOUT_MASK
#define CMU_CTRL_LFXOTIMEOUT_MASK (0x3 << CMU_CTRL_LFXOTIMEOUT_SHIFT)
Definition at line 90 of file cmu_common.h.
CMU_CTRL_LFXOTIMEOUT_SHIFT
#define CMU_CTRL_LFXOTIMEOUT_SHIFT (18)
Definition at line 89 of file cmu_common.h.
CMU_FREEZE
#define CMU_FREEZE MMIO32(CMU_BASE + 0x054)
Definition at line 48 of file cmu_common.h.
CMU_FREEZE_REGFREEZE
#define CMU_FREEZE_REGFREEZE (1 << 0)
Definition at line 468 of file cmu_common.h.
CMU_HFCORECLKDIV
#define CMU_HFCORECLKDIV MMIO32(CMU_BASE + 0x004)
Definition at line 30 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV
#define CMU_HFCORECLKDIV_HFCORECLKDIV (v)
Value:
        (((v) << CMU_HFCORECLKDIV_HFCORECLKDIV_SHIFT) & \
        CMU_HFCORECLKDIV_HFCORECLKDIV_MASK)
Definition at line 164 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV128
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV128 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK128
Definition at line 202 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV16
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV16 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK16
Definition at line 196 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV2
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV2 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK2
Definition at line 190 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV256
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV256 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK256
Definition at line 204 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV32
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV32 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK32
Definition at line 198 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV4
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV4 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK4
Definition at line 192 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV512
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV512 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK512
Definition at line 206 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV64
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV64 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK64
Definition at line 200 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_DIV8
#define CMU_HFCORECLKDIV_HFCORECLKDIV_DIV8 CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK8
Definition at line 194 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK CMU_HFCORECLKDIV_HFCORECLKDIV(0)
Definition at line 167 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK128
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK128 CMU_HFCORECLKDIV_HFCORECLKDIV(7)
Definition at line 181 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK16
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK16 CMU_HFCORECLKDIV_HFCORECLKDIV(4)
Definition at line 175 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK2
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK2 CMU_HFCORECLKDIV_HFCORECLKDIV(1)
Definition at line 169 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK256
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK256 CMU_HFCORECLKDIV_HFCORECLKDIV(8)
Definition at line 183 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK32
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK32 CMU_HFCORECLKDIV_HFCORECLKDIV(5)
Definition at line 177 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK4
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK4 CMU_HFCORECLKDIV_HFCORECLKDIV(2)
Definition at line 171 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK512
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK512 CMU_HFCORECLKDIV_HFCORECLKDIV(9)
Definition at line 185 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK64
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK64 CMU_HFCORECLKDIV_HFCORECLKDIV(6)
Definition at line 179 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK8
#define CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK8 CMU_HFCORECLKDIV_HFCORECLKDIV(3)
Definition at line 173 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_MASK
#define CMU_HFCORECLKDIV_HFCORECLKDIV_MASK (0xF << CMU_HFCORECLKDIV_HFCORECLKDIV_SHIFT)
Definition at line 162 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_NODIV
#define CMU_HFCORECLKDIV_HFCORECLKDIV_NODIV CMU_HFCORECLKDIV_HFCORECLKDIV_HFCLK
Definition at line 188 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKDIV_SHIFT
#define CMU_HFCORECLKDIV_HFCORECLKDIV_SHIFT (0)
Definition at line 161 of file cmu_common.h.
CMU_HFCORECLKDIV_HFCORECLKLEDIV
#define CMU_HFCORECLKDIV_HFCORECLKLEDIV (1 << 8)
Definition at line 159 of file cmu_common.h.
CMU_HFCORECLKEN0
#define CMU_HFCORECLKEN0 MMIO32(CMU_BASE + 0x040)
Definition at line 45 of file cmu_common.h.
CMU_HFCORECLKEN0_AES
#define CMU_HFCORECLKEN0_AES (1 << 1)
Definition at line 438 of file cmu_common.h.
CMU_HFCORECLKEN0_DMA
#define CMU_HFCORECLKEN0_DMA (1 << 0)
Definition at line 439 of file cmu_common.h.
CMU_HFCORECLKEN0_EBI
#define CMU_HFCORECLKEN0_EBI (1 << 5)
Definition at line 434 of file cmu_common.h.
CMU_HFCORECLKEN0_LE
#define CMU_HFCORECLKEN0_LE (1 << 4)
Definition at line 435 of file cmu_common.h.
CMU_HFCORECLKEN0_USB
#define CMU_HFCORECLKEN0_USB (1 << 3)
Definition at line 436 of file cmu_common.h.
CMU_HFCORECLKEN0_USBC
#define CMU_HFCORECLKEN0_USBC (1 << 2)
Definition at line 437 of file cmu_common.h.
CMU_HFPERCLKDIV
#define CMU_HFPERCLKDIV MMIO32(CMU_BASE + 0x008)
Definition at line 31 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV
#define CMU_HFPERCLKDIV_HFPERCLKDIV (v)
Value:
        (((v) << CMU_HFPERCLKDIV_HFPERCLKDIV_SHIFT) & \
         CMU_HFPERCLKDIV_HFPERCLKDIV_MASK)
Definition at line 215 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV128
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV128 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK128
Definition at line 244 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV16
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV16 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK16
Definition at line 238 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV2
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV2 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK2
Definition at line 232 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV256
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV256 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK256
Definition at line 246 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV32
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV32 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK32
Definition at line 240 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV4
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV4 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK4
Definition at line 234 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV512
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV512 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK512
Definition at line 248 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV64
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV64 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK64
Definition at line 242 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_DIV8
#define CMU_HFPERCLKDIV_HFPERCLKDIV_DIV8 CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK8
Definition at line 236 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_MASK
#define CMU_HFPERCLKDIV_HFPERCLKDIV_MASK (0xF << CMU_HFPERCLKDIV_HFPERCLKDIV_SHIFT)
Definition at line 213 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_NODIV
#define CMU_HFPERCLKDIV_HFPERCLKDIV_NODIV CMU_HFPERCLKDIV_HFPERCLKDIV_HFCLK
Definition at line 230 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKDIV_SHIFT
#define CMU_HFPERCLKDIV_HFPERCLKDIV_SHIFT (0)
Definition at line 212 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKEN
#define CMU_HFPERCLKDIV_HFPERCLKEN (1 << 8)
Definition at line 210 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK CMU_HFPERCLKDIV_HFPERCLKDIV(0)
Definition at line 218 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK128
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK128 CMU_HFPERCLKDIV_HFPERCLKDIV(7)
Definition at line 225 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK16
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK16 CMU_HFPERCLKDIV_HFPERCLKDIV(4)
Definition at line 222 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK2
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK2 CMU_HFPERCLKDIV_HFPERCLKDIV(1)
Definition at line 219 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK256
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK256 CMU_HFPERCLKDIV_HFPERCLKDIV(8)
Definition at line 226 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK32
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK32 CMU_HFPERCLKDIV_HFPERCLKDIV(5)
Definition at line 223 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK4
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK4 CMU_HFPERCLKDIV_HFPERCLKDIV(2)
Definition at line 220 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK512
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK512 CMU_HFPERCLKDIV_HFPERCLKDIV(9)
Definition at line 227 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK64
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK64 CMU_HFPERCLKDIV_HFPERCLKDIV(6)
Definition at line 224 of file cmu_common.h.
CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK8
#define CMU_HFPERCLKDIV_HFPERCLKHFCLK_HFCLK8 CMU_HFPERCLKDIV_HFPERCLKDIV(3)
Definition at line 221 of file cmu_common.h.
CMU_HFPERCLKEN0
#define CMU_HFPERCLKEN0 MMIO32(CMU_BASE + 0x044)
Definition at line 46 of file cmu_common.h.
CMU_HFPERCLKEN0_ACMP0
#define CMU_HFPERCLKEN0_ACMP0 (1 << 9)
Definition at line 450 of file cmu_common.h.
CMU_HFPERCLKEN0_ACMP1
#define CMU_HFPERCLKEN0_ACMP1 (1 << 10)
Definition at line 449 of file cmu_common.h.
CMU_HFPERCLKEN0_ADC0
#define CMU_HFPERCLKEN0_ADC0 (1 << 16)
Definition at line 443 of file cmu_common.h.
CMU_HFPERCLKEN0_DAC0
#define CMU_HFPERCLKEN0_DAC0 (1 << 17)
Definition at line 442 of file cmu_common.h.
CMU_HFPERCLKEN0_GPIO
#define CMU_HFPERCLKEN0_GPIO (1 << 13)
Definition at line 446 of file cmu_common.h.
CMU_HFPERCLKEN0_I2C0
#define CMU_HFPERCLKEN0_I2C0 (1 << 11)
Definition at line 448 of file cmu_common.h.
CMU_HFPERCLKEN0_I2C1
#define CMU_HFPERCLKEN0_I2C1 (1 << 12)
Definition at line 447 of file cmu_common.h.
CMU_HFPERCLKEN0_PRS
#define CMU_HFPERCLKEN0_PRS (1 << 15)
Definition at line 444 of file cmu_common.h.
CMU_HFPERCLKEN0_TIMER0
#define CMU_HFPERCLKEN0_TIMER0 (1 << 5)
Definition at line 454 of file cmu_common.h.
CMU_HFPERCLKEN0_TIMER1
#define CMU_HFPERCLKEN0_TIMER1 (1 << 6)
Definition at line 453 of file cmu_common.h.
CMU_HFPERCLKEN0_TIMER2
#define CMU_HFPERCLKEN0_TIMER2 (1 << 7)
Definition at line 452 of file cmu_common.h.
CMU_HFPERCLKEN0_TIMER3
#define CMU_HFPERCLKEN0_TIMER3 (1 << 8)
Definition at line 451 of file cmu_common.h.
CMU_HFPERCLKEN0_UART0
#define CMU_HFPERCLKEN0_UART0 (1 << 3)
Definition at line 456 of file cmu_common.h.
CMU_HFPERCLKEN0_UART1
#define CMU_HFPERCLKEN0_UART1 (1 << 4)
Definition at line 455 of file cmu_common.h.
CMU_HFPERCLKEN0_USART0
#define CMU_HFPERCLKEN0_USART0 (1 << 0)
Definition at line 459 of file cmu_common.h.
CMU_HFPERCLKEN0_USART1
#define CMU_HFPERCLKEN0_USART1 (1 << 1)
Definition at line 458 of file cmu_common.h.
CMU_HFPERCLKEN0_USART2
#define CMU_HFPERCLKEN0_USART2 (1 << 2)
Definition at line 457 of file cmu_common.h.
CMU_HFPERCLKEN0_VCMP
#define CMU_HFPERCLKEN0_VCMP (1 << 14)
Definition at line 445 of file cmu_common.h.
CMU_HFRCOCTRL
#define CMU_HFRCOCTRL MMIO32(CMU_BASE + 0x00C)
Definition at line 32 of file cmu_common.h.
CMU_HFRCOCTRL_BAND
#define CMU_HFRCOCTRL_BAND (v) (((v) << CMU_HFRCOCTRL_BAND_SHIFT) & CMU_HFRCOCTRL_BAND_MASK)
Definition at line 259 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_11MHZ
#define CMU_HFRCOCTRL_BAND_11MHZ 2
Definition at line 263 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_14MHZ
#define CMU_HFRCOCTRL_BAND_14MHZ 3
Definition at line 264 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_1MHZ
#define CMU_HFRCOCTRL_BAND_1MHZ 0
Definition at line 261 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_21MHZ
#define CMU_HFRCOCTRL_BAND_21MHZ 4
Definition at line 265 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_28MHZ
#define CMU_HFRCOCTRL_BAND_28MHZ 5
Definition at line 266 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_7MHZ
#define CMU_HFRCOCTRL_BAND_7MHZ 1
Definition at line 262 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_MASK
#define CMU_HFRCOCTRL_BAND_MASK (0x7 << CMU_HFRCOCTRL_BAND_SHIFT)
Definition at line 258 of file cmu_common.h.
CMU_HFRCOCTRL_BAND_SHIFT
#define CMU_HFRCOCTRL_BAND_SHIFT (8)
Definition at line 257 of file cmu_common.h.
CMU_HFRCOCTRL_SUDELAY
#define CMU_HFRCOCTRL_SUDELAY (v) ((((v) << CMU_HFRCOCTRL_SUDELAY_SHIFT) & CMU_HFRCOCTRL_SUDELAY_MASK))
Definition at line 254 of file cmu_common.h.
CMU_HFRCOCTRL_SUDELAY_MASK
#define CMU_HFRCOCTRL_SUDELAY_MASK (0x1F << CMU_HFRCOCTRL_SUDELAY_SHIFT)
Definition at line 253 of file cmu_common.h.
CMU_HFRCOCTRL_SUDELAY_SHIFT
#define CMU_HFRCOCTRL_SUDELAY_SHIFT (12)
Definition at line 252 of file cmu_common.h.
CMU_HFRCOCTRL_TUNING
#define CMU_HFRCOCTRL_TUNING (v) (((v) << CMU_HFRCOCTRL_TUNING_SHIFT) & CMU_HFRCOCTRL_TUNING_MASK)
Definition at line 270 of file cmu_common.h.
CMU_HFRCOCTRL_TUNING_MASK
#define CMU_HFRCOCTRL_TUNING_MASK (0xFF << CMU_HFRCOCTRL_TUNING_SHIFT)
Definition at line 269 of file cmu_common.h.
CMU_HFRCOCTRL_TUNING_SHIFT
#define CMU_HFRCOCTRL_TUNING_SHIFT (0)
Definition at line 268 of file cmu_common.h.
CMU_IEN
#define CMU_IEN MMIO32(CMU_BASE + 0x03C)
Definition at line 44 of file cmu_common.h.
CMU_IEN_AUXHFRCORDY
#define CMU_IEN_AUXHFRCORDY (1 << 4)
Definition at line 427 of file cmu_common.h.
CMU_IEN_CALOF
#define CMU_IEN_CALOF (1 << 6)
Definition at line 425 of file cmu_common.h.
CMU_IEN_CALRDY
#define CMU_IEN_CALRDY (1 << 5)
Definition at line 426 of file cmu_common.h.
CMU_IEN_HFRCORDY
#define CMU_IEN_HFRCORDY (1 << 0)
Definition at line 431 of file cmu_common.h.
CMU_IEN_HFXORDY
#define CMU_IEN_HFXORDY (1 << 1)
Definition at line 430 of file cmu_common.h.
CMU_IEN_LFRCORDY
#define CMU_IEN_LFRCORDY (1 << 2)
Definition at line 429 of file cmu_common.h.
CMU_IEN_LFXORDY
#define CMU_IEN_LFXORDY (1 << 3)
Definition at line 428 of file cmu_common.h.
CMU_IEN_USBCHFCLKSEL
#define CMU_IEN_USBCHFCLKSEL (1 << 7)
Definition at line 424 of file cmu_common.h.
CMU_IF
#define CMU_IF MMIO32(CMU_BASE + 0x030)
Definition at line 41 of file cmu_common.h.
CMU_IF_AUXHFRCORDY
#define CMU_IF_AUXHFRCORDY (1 << 4)
Definition at line 397 of file cmu_common.h.
CMU_IF_CALOF
#define CMU_IF_CALOF (1 << 6)
Definition at line 395 of file cmu_common.h.
CMU_IF_CALRDY
#define CMU_IF_CALRDY (1 << 5)
Definition at line 396 of file cmu_common.h.
CMU_IF_HFRCORDY
#define CMU_IF_HFRCORDY (1 << 0)
Definition at line 401 of file cmu_common.h.
CMU_IF_HFXORDY
#define CMU_IF_HFXORDY (1 << 1)
Definition at line 400 of file cmu_common.h.
CMU_IF_LFRCORDY
#define CMU_IF_LFRCORDY (1 << 2)
Definition at line 399 of file cmu_common.h.
CMU_IF_LFXORDY
#define CMU_IF_LFXORDY (1 << 3)
Definition at line 398 of file cmu_common.h.
CMU_IF_USBCHFCLKSEL
#define CMU_IF_USBCHFCLKSEL (1 << 7)
Definition at line 394 of file cmu_common.h.
CMU_IFC
#define CMU_IFC MMIO32(CMU_BASE + 0x038)
Definition at line 43 of file cmu_common.h.
CMU_IFC_AUXHFRCORDY
#define CMU_IFC_AUXHFRCORDY (1 << 4)
Definition at line 417 of file cmu_common.h.
CMU_IFC_CALOF
#define CMU_IFC_CALOF (1 << 6)
Definition at line 415 of file cmu_common.h.
CMU_IFC_CALRDY
#define CMU_IFC_CALRDY (1 << 5)
Definition at line 416 of file cmu_common.h.
CMU_IFC_HFRCORDY
#define CMU_IFC_HFRCORDY (1 << 0)
Definition at line 421 of file cmu_common.h.
CMU_IFC_HFXORDY
#define CMU_IFC_HFXORDY (1 << 1)
Definition at line 420 of file cmu_common.h.
CMU_IFC_LFRCORDY
#define CMU_IFC_LFRCORDY (1 << 2)
Definition at line 419 of file cmu_common.h.
CMU_IFC_LFXORDY
#define CMU_IFC_LFXORDY (1 << 3)
Definition at line 418 of file cmu_common.h.
CMU_IFC_USBCHFCLKSEL
#define CMU_IFC_USBCHFCLKSEL (1 << 7)
Definition at line 414 of file cmu_common.h.
CMU_IFS
#define CMU_IFS MMIO32(CMU_BASE + 0x034)
Definition at line 42 of file cmu_common.h.
CMU_IFS_AUXHFRCORDY
#define CMU_IFS_AUXHFRCORDY (1 << 4)
Definition at line 407 of file cmu_common.h.
CMU_IFS_CALOF
#define CMU_IFS_CALOF (1 << 6)
Definition at line 405 of file cmu_common.h.
CMU_IFS_CALRDY
#define CMU_IFS_CALRDY (1 << 5)
Definition at line 406 of file cmu_common.h.
CMU_IFS_HFRCORDY
#define CMU_IFS_HFRCORDY (1 << 0)
Definition at line 411 of file cmu_common.h.
CMU_IFS_HFXORDY
#define CMU_IFS_HFXORDY (1 << 1)
Definition at line 410 of file cmu_common.h.
CMU_IFS_LFRCORDY
#define CMU_IFS_LFRCORDY (1 << 2)
Definition at line 409 of file cmu_common.h.
CMU_IFS_LFXORDY
#define CMU_IFS_LFXORDY (1 << 3)
Definition at line 408 of file cmu_common.h.
CMU_IFS_USBCHFCLKSEL
#define CMU_IFS_USBCHFCLKSEL (1 << 7)
Definition at line 404 of file cmu_common.h.
CMU_LCDCTRL
#define CMU_LCDCTRL MMIO32(CMU_BASE + 0x07C)
Definition at line 54 of file cmu_common.h.
CMU_LCDCTRL_FDIV
#define CMU_LCDCTRL_FDIV (v) (((v) & CMU_LCDCTRL_FDIV_MASK) << CMU_LCDCTRL_FDIV_SHIFT)
Definition at line 592 of file cmu_common.h.
CMU_LCDCTRL_FDIV_MASK
#define CMU_LCDCTRL_FDIV_MASK (0x3 << CMU_LCDCTRL_FDIV_SHIFT)
Definition at line 591 of file cmu_common.h.
CMU_LCDCTRL_FDIV_SHIFT
#define CMU_LCDCTRL_FDIV_SHIFT (0)
Definition at line 590 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV
#define CMU_LCDCTRL_VBFDIV (v) (((v) << CMU_LCDCTRL_VBFDIV_SHIFT) & CMU_LCDCTRL_VBFDIV_MASK)
Definition at line 576 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV1
#define CMU_LCDCTRL_VBFDIV_DIV1 0
Definition at line 578 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV128
#define CMU_LCDCTRL_VBFDIV_DIV128 7
Definition at line 585 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV16
#define CMU_LCDCTRL_VBFDIV_DIV16 4
Definition at line 582 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV2
#define CMU_LCDCTRL_VBFDIV_DIV2 1
Definition at line 579 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV32
#define CMU_LCDCTRL_VBFDIV_DIV32 5
Definition at line 583 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV4
#define CMU_LCDCTRL_VBFDIV_DIV4 2
Definition at line 580 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV64
#define CMU_LCDCTRL_VBFDIV_DIV64 6
Definition at line 584 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_DIV8
#define CMU_LCDCTRL_VBFDIV_DIV8 3
Definition at line 581 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_MASK
#define CMU_LCDCTRL_VBFDIV_MASK (0xF << CMU_LCDCTRL_VBFDIV_SHIFT)
Definition at line 575 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_NODIV
#define CMU_LCDCTRL_VBFDIV_NODIV CMU_LCDCTRL_VBFDIV_DIV1
Definition at line 586 of file cmu_common.h.
CMU_LCDCTRL_VBFDIV_SHIFT
#define CMU_LCDCTRL_VBFDIV_SHIFT (4)
Definition at line 574 of file cmu_common.h.
CMU_LCDCTRL_VBOOSTEN
#define CMU_LCDCTRL_VBOOSTEN (1 << 3)
Definition at line 588 of file cmu_common.h.
CMU_LFACLKEN0
#define CMU_LFACLKEN0 MMIO32(CMU_BASE + 0x058)
Definition at line 49 of file cmu_common.h.
CMU_LFACLKEN0_LCD
#define CMU_LFACLKEN0_LCD (1 << 3)
Definition at line 471 of file cmu_common.h.
CMU_LFACLKEN0_LESENSE
#define CMU_LFACLKEN0_LESENSE (1 << 0)
Definition at line 474 of file cmu_common.h.
CMU_LFACLKEN0_LETIMER0
#define CMU_LFACLKEN0_LETIMER0 (1 << 2)
Definition at line 472 of file cmu_common.h.
CMU_LFACLKEN0_RTC
#define CMU_LFACLKEN0_RTC (1 << 1)
Definition at line 473 of file cmu_common.h.
CMU_LFAPRESC0
#define CMU_LFAPRESC0 MMIO32(CMU_BASE + 0x068)
Definition at line 51 of file cmu_common.h.
CMU_LFAPRESC0_LCD
#define CMU_LFAPRESC0_LCD (v) (((v) << CMU_LFAPRESC0_LCD_SHIFT) & CMU_LFAPRESC0_LCD_MASK)
Definition at line 483 of file cmu_common.h.
CMU_LFAPRESC0_LCD_DIV128
#define CMU_LFAPRESC0_LCD_DIV128 3
Definition at line 488 of file cmu_common.h.
CMU_LFAPRESC0_LCD_DIV16
#define CMU_LFAPRESC0_LCD_DIV16 0
Definition at line 485 of file cmu_common.h.
CMU_LFAPRESC0_LCD_DIV32
#define CMU_LFAPRESC0_LCD_DIV32 1
Definition at line 486 of file cmu_common.h.
CMU_LFAPRESC0_LCD_DIV64
#define CMU_LFAPRESC0_LCD_DIV64 2
Definition at line 487 of file cmu_common.h.
CMU_LFAPRESC0_LCD_MASK
#define CMU_LFAPRESC0_LCD_MASK (0x3 << CMU_LFAPRESC0_LCD_SHIFT)
Definition at line 482 of file cmu_common.h.
CMU_LFAPRESC0_LCD_SHIFT
#define CMU_LFAPRESC0_LCD_SHIFT (12)
Definition at line 481 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE
#define CMU_LFAPRESC0_LESENSE (v) (((v) << CMU_LFAPRESC0_LESENSE_SHIFT) & CMU_LFAPRESC0_LESENSE_MASK)
Definition at line 536 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE_DIV1
#define CMU_LFAPRESC0_LESENSE_DIV1 0
Definition at line 538 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE_DIV2
#define CMU_LFAPRESC0_LESENSE_DIV2 1
Definition at line 539 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE_DIV4
#define CMU_LFAPRESC0_LESENSE_DIV4 2
Definition at line 540 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE_DIV8
#define CMU_LFAPRESC0_LESENSE_DIV8 3
Definition at line 541 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE_MASK
#define CMU_LFAPRESC0_LESENSE_MASK (0x3 << CMU_LFAPRESC0_LESENSE_SHIFT)
Definition at line 535 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE_NODIV
#define CMU_LFAPRESC0_LESENSE_NODIV CMU_LFAPRESC0_LESENSE_DIV1
Definition at line 542 of file cmu_common.h.
CMU_LFAPRESC0_LESENSE_SHIFT
#define CMU_LFAPRESC0_LESENSE_SHIFT (12)
Definition at line 534 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0
#define CMU_LFAPRESC0_LETIMER0 (v) (((v) << CMU_LFAPRESC0_LETIMER0_SHIFT) & CMU_LFAPRESC0_LETIMER0_MASK)
Definition at line 492 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV1
#define CMU_LFAPRESC0_LETIMER0_DIV1 0
Definition at line 494 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV1024
#define CMU_LFAPRESC0_LETIMER0_DIV1024 10
Definition at line 504 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV128
#define CMU_LFAPRESC0_LETIMER0_DIV128 7
Definition at line 501 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV16
#define CMU_LFAPRESC0_LETIMER0_DIV16 4
Definition at line 498 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV16384
#define CMU_LFAPRESC0_LETIMER0_DIV16384 14
Definition at line 508 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV2
#define CMU_LFAPRESC0_LETIMER0_DIV2 1
Definition at line 495 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV2048
#define CMU_LFAPRESC0_LETIMER0_DIV2048 11
Definition at line 505 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV256
#define CMU_LFAPRESC0_LETIMER0_DIV256 8
Definition at line 502 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV32
#define CMU_LFAPRESC0_LETIMER0_DIV32 5
Definition at line 499 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV32768
#define CMU_LFAPRESC0_LETIMER0_DIV32768 15
Definition at line 509 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV4
#define CMU_LFAPRESC0_LETIMER0_DIV4 2
Definition at line 496 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV4096
#define CMU_LFAPRESC0_LETIMER0_DIV4096 12
Definition at line 506 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV512
#define CMU_LFAPRESC0_LETIMER0_DIV512 9
Definition at line 503 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV64
#define CMU_LFAPRESC0_LETIMER0_DIV64 6
Definition at line 500 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV8
#define CMU_LFAPRESC0_LETIMER0_DIV8 3
Definition at line 497 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_DIV8192
#define CMU_LFAPRESC0_LETIMER0_DIV8192 13
Definition at line 507 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_MASK
#define CMU_LFAPRESC0_LETIMER0_MASK (0xF << CMU_LFAPRESC0_LETIMER0_SHIFT)
Definition at line 491 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_NODIV
#define CMU_LFAPRESC0_LETIMER0_NODIV CMU_LFAPRESC0_LETIMER0_DIV1
Definition at line 510 of file cmu_common.h.
CMU_LFAPRESC0_LETIMER0_SHIFT
#define CMU_LFAPRESC0_LETIMER0_SHIFT (8)
Definition at line 490 of file cmu_common.h.
CMU_LFAPRESC0_RTC
#define CMU_LFAPRESC0_RTC (v) (((v) << CMU_LFAPRESC0_RTC_SHIFT) & CMU_LFAPRESC0_RTC_MASK)
Definition at line 514 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV1
#define CMU_LFAPRESC0_RTC_DIV1 0
Definition at line 516 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV1024
#define CMU_LFAPRESC0_RTC_DIV1024 10
Definition at line 526 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV128
#define CMU_LFAPRESC0_RTC_DIV128 7
Definition at line 523 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV16
#define CMU_LFAPRESC0_RTC_DIV16 4
Definition at line 520 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV16384
#define CMU_LFAPRESC0_RTC_DIV16384 14
Definition at line 530 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV2
#define CMU_LFAPRESC0_RTC_DIV2 1
Definition at line 517 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV2048
#define CMU_LFAPRESC0_RTC_DIV2048 11
Definition at line 527 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV256
#define CMU_LFAPRESC0_RTC_DIV256 8
Definition at line 524 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV32
#define CMU_LFAPRESC0_RTC_DIV32 5
Definition at line 521 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV32768
#define CMU_LFAPRESC0_RTC_DIV32768 15
Definition at line 531 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV4
#define CMU_LFAPRESC0_RTC_DIV4 2
Definition at line 518 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV4096
#define CMU_LFAPRESC0_RTC_DIV4096 12
Definition at line 528 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV512
#define CMU_LFAPRESC0_RTC_DIV512 9
Definition at line 525 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV64
#define CMU_LFAPRESC0_RTC_DIV64 6
Definition at line 522 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV8
#define CMU_LFAPRESC0_RTC_DIV8 3
Definition at line 519 of file cmu_common.h.
CMU_LFAPRESC0_RTC_DIV8192
#define CMU_LFAPRESC0_RTC_DIV8192 13
Definition at line 529 of file cmu_common.h.
CMU_LFAPRESC0_RTC_MASK
#define CMU_LFAPRESC0_RTC_MASK (0xF << CMU_LFAPRESC0_RTC_SHIFT)
Definition at line 513 of file cmu_common.h.
CMU_LFAPRESC0_RTC_NODIV
#define CMU_LFAPRESC0_RTC_NODIV CMU_LFAPRESC0_RTC_DIV1
Definition at line 532 of file cmu_common.h.
CMU_LFAPRESC0_RTC_SHIFT
#define CMU_LFAPRESC0_RTC_SHIFT (4)
Definition at line 512 of file cmu_common.h.
CMU_LFBCLKEN0
#define CMU_LFBCLKEN0 MMIO32(CMU_BASE + 0x060)
Definition at line 50 of file cmu_common.h.
CMU_LFBCLKEN0_LEUART0
#define CMU_LFBCLKEN0_LEUART0 (1 << 0)
Definition at line 478 of file cmu_common.h.
CMU_LFBCLKEN0_LEUART1
#define CMU_LFBCLKEN0_LEUART1 (1 << 1)
Definition at line 477 of file cmu_common.h.
CMU_LFBPRESC0
#define CMU_LFBPRESC0 MMIO32(CMU_BASE + 0x070)
Definition at line 52 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0
#define CMU_LFBPRESC0_LEUART0 (v) (((v) << CMU_LFBPRESC0_LEUART0_SHIFT) & CMU_LFBPRESC0_LEUART0_MASK)
Definition at line 557 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0_DIV1
#define CMU_LFBPRESC0_LEUART0_DIV1 0
Definition at line 559 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0_DIV2
#define CMU_LFBPRESC0_LEUART0_DIV2 1
Definition at line 560 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0_DIV4
#define CMU_LFBPRESC0_LEUART0_DIV4 2
Definition at line 561 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0_DIV8
#define CMU_LFBPRESC0_LEUART0_DIV8 3
Definition at line 562 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0_MASK
#define CMU_LFBPRESC0_LEUART0_MASK (0x3 << CMU_LFBPRESC0_LEUART0_SHIFT)
Definition at line 556 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0_NODIV
#define CMU_LFBPRESC0_LEUART0_NODIV CMU_LFBPRESC0_LEUART0_DIV1
Definition at line 563 of file cmu_common.h.
CMU_LFBPRESC0_LEUART0_SHIFT
#define CMU_LFBPRESC0_LEUART0_SHIFT (0)
Definition at line 555 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1
#define CMU_LFBPRESC0_LEUART1 (v) (((v) << CMU_LFBPRESC0_LEUART1_SHIFT) & CMU_LFBPRESC0_LEUART1_MASK)
Definition at line 547 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1_DIV1
#define CMU_LFBPRESC0_LEUART1_DIV1 0
Definition at line 549 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1_DIV2
#define CMU_LFBPRESC0_LEUART1_DIV2 1
Definition at line 550 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1_DIV4
#define CMU_LFBPRESC0_LEUART1_DIV4 2
Definition at line 551 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1_DIV8
#define CMU_LFBPRESC0_LEUART1_DIV8 3
Definition at line 552 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1_MASK
#define CMU_LFBPRESC0_LEUART1_MASK (0x3 << CMU_LFBPRESC0_LEUART1_SHIFT)
Definition at line 546 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1_NODIV
#define CMU_LFBPRESC0_LEUART1_NODIV CMU_LFBPRESC0_LEUART1_DIV1
Definition at line 553 of file cmu_common.h.
CMU_LFBPRESC0_LEUART1_SHIFT
#define CMU_LFBPRESC0_LEUART1_SHIFT (4)
Definition at line 545 of file cmu_common.h.
CMU_LFCLKSEL
#define CMU_LFCLKSEL MMIO32(CMU_BASE + 0x028)
Definition at line 39 of file cmu_common.h.
CMU_LFCLKSEL_LFA
#define CMU_LFCLKSEL_LFA (v) (((v) << CMU_LFCLKSEL_LFA_MASK) & CMU_LFCLKSEL_LFA_MASK)
Definition at line 370 of file cmu_common.h.
CMU_LFCLKSEL_LFA_MASK
#define CMU_LFCLKSEL_LFA_MASK (0x3 << CMU_LFCLKSEL_LFA_MASK)
Definition at line 369 of file cmu_common.h.
CMU_LFCLKSEL_LFA_SHIFT
#define CMU_LFCLKSEL_LFA_SHIFT (0)
Definition at line 368 of file cmu_common.h.
CMU_LFCLKSEL_LFAE
#define CMU_LFCLKSEL_LFAE (1 << 16)
Definition at line 361 of file cmu_common.h.
CMU_LFCLKSEL_LFB
#define CMU_LFCLKSEL_LFB (v) (((v) << CMU_LFCLKSEL_LFB_MASK) & CMU_LFCLKSEL_LFB_MASK)
Definition at line 365 of file cmu_common.h.
CMU_LFCLKSEL_LFB_MASK
#define CMU_LFCLKSEL_LFB_MASK (0x3 << CMU_LFCLKSEL_LFB_MASK)
Definition at line 364 of file cmu_common.h.
CMU_LFCLKSEL_LFB_SHIFT
#define CMU_LFCLKSEL_LFB_SHIFT (2)
Definition at line 363 of file cmu_common.h.
CMU_LFCLKSEL_LFBE
#define CMU_LFCLKSEL_LFBE (1 << 20)
Definition at line 360 of file cmu_common.h.
CMU_LFRCOCTRL
#define CMU_LFRCOCTRL MMIO32(CMU_BASE + 0x010)
Definition at line 33 of file cmu_common.h.
CMU_LFRCOCTRL_TUNING
#define CMU_LFRCOCTRL_TUNING (v) (((v) << CMU_LFRCOCTRL_TUNING_SHIFT) & CMU_LFRCOCTRL_TUNING_MASK)
Definition at line 276 of file cmu_common.h.
CMU_LFRCOCTRL_TUNING_MASK
#define CMU_LFRCOCTRL_TUNING_MASK (0xFF << CMU_LFRCOCTRL_TUNING_SHIFT)
Definition at line 275 of file cmu_common.h.
CMU_LFRCOCTRL_TUNING_SHIFT
#define CMU_LFRCOCTRL_TUNING_SHIFT (0)
Definition at line 274 of file cmu_common.h.
CMU_LOCK
#define CMU_LOCK MMIO32(CMU_BASE + 0x084)
Definition at line 56 of file cmu_common.h.
CMU_LOCK_LOCKKEY_LOCK
#define CMU_LOCK_LOCKKEY_LOCK (0x0000 << CMU_LOCK_LOCKKEY_SHIFT)
Definition at line 612 of file cmu_common.h.
CMU_LOCK_LOCKKEY_LOCKED
#define CMU_LOCK_LOCKKEY_LOCKED (0x0001 << CMU_LOCK_LOCKKEY_SHIFT)
Definition at line 611 of file cmu_common.h.
CMU_LOCK_LOCKKEY_MASK
#define CMU_LOCK_LOCKKEY_MASK (0xFFFF << CMU_LOCK_LOCKKEY_SHIFT)
Definition at line 609 of file cmu_common.h.
CMU_LOCK_LOCKKEY_SHIFT
#define CMU_LOCK_LOCKKEY_SHIFT (0)
Definition at line 608 of file cmu_common.h.
CMU_LOCK_LOCKKEY_UNLOCK
#define CMU_LOCK_LOCKKEY_UNLOCK (0x580E << CMU_LOCK_LOCKKEY_SHIFT)
Definition at line 613 of file cmu_common.h.
CMU_LOCK_LOCKKEY_UNLOCKED
#define CMU_LOCK_LOCKKEY_UNLOCKED (0x0000 << CMU_LOCK_LOCKKEY_SHIFT)
Definition at line 610 of file cmu_common.h.
CMU_OSCENCMD
#define CMU_OSCENCMD MMIO32(CMU_BASE + 0x020)
Definition at line 37 of file cmu_common.h.
CMU_OSCENCMD_AUXHFRCODIS
#define CMU_OSCENCMD_AUXHFRCODIS (1 << 5)
Definition at line 331 of file cmu_common.h.
CMU_OSCENCMD_AUXHFRCOEN
#define CMU_OSCENCMD_AUXHFRCOEN (1 << 4)
Definition at line 332 of file cmu_common.h.
CMU_OSCENCMD_HFRCODIS
#define CMU_OSCENCMD_HFRCODIS (1 << 1)
Definition at line 335 of file cmu_common.h.
CMU_OSCENCMD_HFRCOEN
#define CMU_OSCENCMD_HFRCOEN (1 << 0)
Definition at line 336 of file cmu_common.h.
CMU_OSCENCMD_HFXODIS
#define CMU_OSCENCMD_HFXODIS (1 << 3)
Definition at line 333 of file cmu_common.h.
CMU_OSCENCMD_HFXOEN
#define CMU_OSCENCMD_HFXOEN (1 << 2)
Definition at line 334 of file cmu_common.h.
CMU_OSCENCMD_LFRCODIS
#define CMU_OSCENCMD_LFRCODIS (1 << 7)
Definition at line 329 of file cmu_common.h.
CMU_OSCENCMD_LFRCOEN
#define CMU_OSCENCMD_LFRCOEN (1 << 6)
Definition at line 330 of file cmu_common.h.
CMU_OSCENCMD_LFXODIS
#define CMU_OSCENCMD_LFXODIS (1 << 9)
Definition at line 327 of file cmu_common.h.
CMU_OSCENCMD_LFXOEN
#define CMU_OSCENCMD_LFXOEN (1 << 8)
Definition at line 328 of file cmu_common.h.
CMU_PCNTCTRL
#define CMU_PCNTCTRL MMIO32(CMU_BASE + 0x078)
Definition at line 53 of file cmu_common.h.
CMU_PCNTCTRL_PCNT0CLKEN
#define CMU_PCNTCTRL_PCNT0CLKEN (1 << 0)
Definition at line 571 of file cmu_common.h.
CMU_PCNTCTRL_PCNT0CLKSEL
#define CMU_PCNTCTRL_PCNT0CLKSEL (1 << 1)
Definition at line 570 of file cmu_common.h.
CMU_PCNTCTRL_PCNT1CLKEN
#define CMU_PCNTCTRL_PCNT1CLKEN (1 << 2)
Definition at line 569 of file cmu_common.h.
CMU_PCNTCTRL_PCNT1CLKSEL
#define CMU_PCNTCTRL_PCNT1CLKSEL (1 << 3)
Definition at line 568 of file cmu_common.h.
CMU_PCNTCTRL_PCNT2CLKEN
#define CMU_PCNTCTRL_PCNT2CLKEN (1 << 4)
Definition at line 567 of file cmu_common.h.
CMU_PCNTCTRL_PCNT2CLKSE
#define CMU_PCNTCTRL_PCNT2CLKSE (1 << 5)
Definition at line 566 of file cmu_common.h.
CMU_ROUTE
#define CMU_ROUTE MMIO32(CMU_BASE + 0x080)
Definition at line 55 of file cmu_common.h.
CMU_ROUTE_CLKOUT0PEN
#define CMU_ROUTE_CLKOUT0PEN (1 << 0)
Definition at line 605 of file cmu_common.h.
CMU_ROUTE_CLKOUT1PEN
#define CMU_ROUTE_CLKOUT1PEN (1 << 1)
Definition at line 604 of file cmu_common.h.
CMU_ROUTE_LOCATION_LOC0
#define CMU_ROUTE_LOCATION_LOC0 0
Definition at line 600 of file cmu_common.h.
CMU_ROUTE_LOCATION_LOC1
#define CMU_ROUTE_LOCATION_LOC1 1
Definition at line 601 of file cmu_common.h.
CMU_ROUTE_LOCATION_LOC2
#define CMU_ROUTE_LOCATION_LOC2 2
Definition at line 602 of file cmu_common.h.
CMU_ROUTE_LOCATION_LOCx
#define CMU_ROUTE_LOCATION_LOCx (i) (((i) << CMU_ROUTE_LOCATION_SHIFT) & CMU_ROUTE_LOCATION_MASK)
Definition at line 598 of file cmu_common.h.
CMU_ROUTE_LOCATION_MASK
#define CMU_ROUTE_LOCATION_MASK (0x7 << CMU_ROUTE_LOCATION_SHIFT)
Definition at line 597 of file cmu_common.h.
CMU_ROUTE_LOCATION_SHIFT
#define CMU_ROUTE_LOCATION_SHIFT (2)
Definition at line 596 of file cmu_common.h.
CMU_STATUS
#define CMU_STATUS MMIO32(CMU_BASE + 0x02C)
Definition at line 40 of file cmu_common.h.
CMU_STATUS_AUXHFRCOENS
#define CMU_STATUS_AUXHFRCOENS (1 << 4)
Definition at line 387 of file cmu_common.h.
CMU_STATUS_AUXHFRCORDY
#define CMU_STATUS_AUXHFRCORDY (1 << 5)
Definition at line 386 of file cmu_common.h.
CMU_STATUS_CALBSY
#define CMU_STATUS_CALBSY (1 << 14)
Definition at line 377 of file cmu_common.h.
CMU_STATUS_HFRCOENS
#define CMU_STATUS_HFRCOENS (1 << 0)
Definition at line 391 of file cmu_common.h.
CMU_STATUS_HFRCORDY
#define CMU_STATUS_HFRCORDY (1 << 1)
Definition at line 390 of file cmu_common.h.
CMU_STATUS_HFRCOSEL
#define CMU_STATUS_HFRCOSEL (1 << 10)
Definition at line 381 of file cmu_common.h.
CMU_STATUS_HFXOENS
#define CMU_STATUS_HFXOENS (1 << 2)
Definition at line 389 of file cmu_common.h.
CMU_STATUS_HFXORDY
#define CMU_STATUS_HFXORDY (1 << 3)
Definition at line 388 of file cmu_common.h.
CMU_STATUS_HFXOSEL
#define CMU_STATUS_HFXOSEL (1 << 11)
Definition at line 380 of file cmu_common.h.
CMU_STATUS_LFRCOENS
#define CMU_STATUS_LFRCOENS (1 << 6)
Definition at line 385 of file cmu_common.h.
CMU_STATUS_LFRCORDY
#define CMU_STATUS_LFRCORDY (1 << 7)
Definition at line 384 of file cmu_common.h.
CMU_STATUS_LFRCOSEL
#define CMU_STATUS_LFRCOSEL (1 << 12)
Definition at line 379 of file cmu_common.h.
CMU_STATUS_LFXOENS
#define CMU_STATUS_LFXOENS (1 << 8)
Definition at line 383 of file cmu_common.h.
CMU_STATUS_LFXORDY
#define CMU_STATUS_LFXORDY (1 << 9)
Definition at line 382 of file cmu_common.h.
CMU_STATUS_LFXOSEL
#define CMU_STATUS_LFXOSEL (1 << 13)
Definition at line 378 of file cmu_common.h.
CMU_STATUS_USBCHFCLKSEL
#define CMU_STATUS_USBCHFCLKSEL (1 << 15)
Definition at line 376 of file cmu_common.h.
CMU_STATUS_USBCLFRCOSEL
#define CMU_STATUS_USBCLFRCOSEL (1 << 17)
Definition at line 374 of file cmu_common.h.
CMU_STATUS_USBCLFXOSEL
#define CMU_STATUS_USBCLFXOSEL (1 << 16)
Definition at line 375 of file cmu_common.h.
CMU_SYNCBUSY
#define CMU_SYNCBUSY MMIO32(CMU_BASE + 0x050)
Definition at line 47 of file cmu_common.h.
CMU_SYNCBUSY_LFACLKEN0
#define CMU_SYNCBUSY_LFACLKEN0 (1 << 0)
Definition at line 465 of file cmu_common.h.
CMU_SYNCBUSY_LFAPRESC0
#define CMU_SYNCBUSY_LFAPRESC0 (1 << 2)
Definition at line 464 of file cmu_common.h.
CMU_SYNCBUSY_LFBCLKEN0
#define CMU_SYNCBUSY_LFBCLKEN0 (1 << 4)
Definition at line 463 of file cmu_common.h.
CMU_SYNCBUSY_LFBPRESC0
#define CMU_SYNCBUSY_LFBPRESC0 (1 << 6)
Definition at line 462 of file cmu_common.h.
Enumeration Type Documentation
cmu_osc
enum cmu_osc
Enumerator
HFRCO
Internal, 1 - 28Mhz.
LFRCO
Internal, 32.768kHz.
ULFRCO
Internal, 1Khz.
HFXO
External, 4-48Mhz.
LFXO
External, 32.768kHz.
AUXHFRCO
Internal, 1-28Mhz.
Definition at line 662 of file cmu_common.h.
cmu_periph_clken
enum cmu_periph_clken
Enumerator
CMU_PCNT2
CMU_PCNT1
CMU_PCNT0
CMU_LEUART1
CMU_LEUART0
CMU_LCD
CMU_LETIMER0
CMU_RTC
CMU_LESENSE
CMU_DAC0
CMU_ADC0
CMU_PRS
CMU_VCMP
CMU_GPIO
CMU_I2C1
CMU_I2C0
CMU_ACMP1
CMU_ACMP0
CMU_TIMER3
CMU_TIMER2
CMU_TIMER1
CMU_TIMER0
CMU_UART1
CMU_UART0
CMU_USART2
CMU_USART1
CMU_USART0
CMU_EBI
CMU_LE
CMU_USB
CMU_USBC
CMU_AES
CMU_DMA
Definition at line 617 of file cmu_common.h.
Function Documentation
cmu_clock_setup_in_hfxo_out_48mhz()
void cmu_clock_setup_in_hfxo_out_48mhz (void)
HFXO output 48Mhz and core running at 48Mhz.
Definition at line 252 of file cmu_common.c.
References CMU_CTRL, CMU_CTRL_HFCLKDIV_MASK, CMU_CTRL_HFCLKDIV_NODIV, CMU_CTRL_HFXOBUFCUR_BOOSTABOVE32MHZ, CMU_CTRL_HFXOBUFCUR_MASK, cmu_get_hfclk_source(), CMU_HFCORECLKDIV, CMU_HFCORECLKDIV_HFCORECLKDIV_NODIV, CMU_HFCORECLKDIV_HFCORECLKLEDIV, cmu_osc_on(), cmu_set_hfclk_source(), cmu_wait_for_osc_ready(), HFXO, MSC_READCTRL, and MSC_READCTRL_MODE_WS2.
cmu_disable_lock()
void cmu_disable_lock (void)
Disable CMU registers lock.
Definition at line 39 of file cmu_common.c.
References CMU_LOCK, and CMU_LOCK_LOCKKEY_UNLOCK.
cmu_enable_lock()
void cmu_enable_lock (void)
Enable CMU registers lock.
Definition at line 31 of file cmu_common.c.
References CMU_LOCK, and CMU_LOCK_LOCKKEY_LOCK.
cmu_get_hfclk_source()
enum cmu_osc cmu_get_hfclk_source (void)
Definition at line 232 of file cmu_common.c.
References CMU_STATUS, CMU_STATUS_HFRCOSEL, CMU_STATUS_HFXOSEL, CMU_STATUS_LFRCOSEL, CMU_STATUS_LFXOSEL, HFRCO, HFXO, LFRCO, and LFXO.
Referenced by cmu_clock_setup_in_hfxo_out_48mhz().
cmu_get_lock_flag()
bool cmu_get_lock_flag (void)
Get CMU register lock flag.
Return values
true if flag is set
false if flag is not set
Definition at line 49 of file cmu_common.c.
References CMU_LOCK, CMU_LOCK_LOCKKEY_LOCKED, and CMU_LOCK_LOCKKEY_MASK.
cmu_osc_off()
void cmu_osc_off (enum cmu_osc osc)
Turn off Oscillator.
Parameters
[in] osc enum cmu_osc Oscillator name
Definition at line 120 of file cmu_common.c.
References AUXHFRCO, CMU_OSCENCMD, CMU_OSCENCMD_AUXHFRCODIS, CMU_OSCENCMD_HFRCODIS, CMU_OSCENCMD_HFXODIS, CMU_OSCENCMD_LFRCODIS, CMU_OSCENCMD_LFXODIS, HFRCO, HFXO, LFRCO, LFXO, and ULFRCO.
cmu_osc_on()
void cmu_osc_on (enum cmu_osc osc)
Turn on Oscillator.
Parameters
[in] osc enum cmu_osc Oscillator name
Definition at line 92 of file cmu_common.c.
References AUXHFRCO, CMU_OSCENCMD, CMU_OSCENCMD_AUXHFRCOEN, CMU_OSCENCMD_HFRCOEN, CMU_OSCENCMD_HFXOEN, CMU_OSCENCMD_LFRCOEN, CMU_OSCENCMD_LFXOEN, HFRCO, HFXO, LFRCO, LFXO, and ULFRCO.
Referenced by cmu_clock_setup_in_hfxo_out_48mhz().
cmu_osc_ready_flag()
bool cmu_osc_ready_flag (enum cmu_osc osc)
Get Oscillator read flag.
Parameters
[in] osc enum cmu_osc Oscillator name
Return values
true if flag is set
false if flag is not set
Definition at line 150 of file cmu_common.c.
References AUXHFRCO, CMU_STATUS, CMU_STATUS_AUXHFRCORDY, CMU_STATUS_HFRCORDY, CMU_STATUS_HFXORDY, CMU_STATUS_LFRCORDY, CMU_STATUS_LFXORDY, HFRCO, HFXO, LFRCO, LFXO, and ULFRCO.
cmu_periph_clock_disable()
void cmu_periph_clock_disable (enum cmu_periph_clken clken)
Disable Peripheral Clock in running mode.
Disable the clock on particular peripheral.
Parameters
[in] clken Peripheral Name
For available constants, see enum::cmu_periph_clken (CMU_LEUART1 for example)
Definition at line 83 of file cmu_common.c.
References _CMU_REG.
cmu_periph_clock_enable()
void cmu_periph_clock_enable (enum cmu_periph_clken clken)
Enable Peripheral Clock in running mode.
Enable the clock on particular peripheral.
Parameters
[in] clken Peripheral Name
For available constants, see enum::cmu_periph_clken (CMU_LEUART1 for example)
Definition at line 68 of file cmu_common.c.
References _CMU_BIT, and _CMU_REG.
cmu_set_hfclk_source()
void cmu_set_hfclk_source (enum cmu_osc osc)
Set HFCLK clock source.
Parameters
[in] osc enum cmu_osc Oscillator name
Note
calling cmu_set_hfclk_source() do not set source immediately, use cmu_get_hfclk_source() to verify that the source has been set.
See also
cmu_get_hfclk_source()
Definition at line 211 of file cmu_common.c.
References CMU_CMD, CMU_CMD_HFCLKSEL_HFRCO, CMU_CMD_HFCLKSEL_HFXO, CMU_CMD_HFCLKSEL_LFRCO, CMU_CMD_HFCLKSEL_LFXO, HFRCO, HFXO, LFRCO, and LFXO.
Referenced by cmu_clock_setup_in_hfxo_out_48mhz().
cmu_set_usbclk_source()
void cmu_set_usbclk_source (enum cmu_osc osc)
cmu_wait_for_osc_ready()
void cmu_wait_for_osc_ready (enum cmu_osc osc)
Wait till oscillator is not ready.
Parameters
[in] osc enum cmu_osc Oscillator name
Definition at line 180 of file cmu_common.c.
References AUXHFRCO, CMU_STATUS, CMU_STATUS_AUXHFRCORDY, CMU_STATUS_HFRCORDY, CMU_STATUS_HFXORDY, CMU_STATUS_LFRCORDY, CMU_STATUS_LFXORDY, HFRCO, HFXO, LFRCO, LFXO, and ULFRCO.
Referenced by cmu_clock_setup_in_hfxo_out_48mhz().