libopencm3: pmc.c File Reference
pmc.c File Reference
#include <libopencm3/sam/pmc.h>
#include <libopencm3/sam/eefc.h>
Functions
void pmc_xtal_enable (bool en, uint8_t startup_time)
void pmc_plla_config (uint8_t mul, uint8_t div)
void pmc_peripheral_clock_enable (uint8_t pid)
void pmc_peripheral_clock_disable (uint8_t pid)
void pmc_mck_set_source (enum mck_src src)
void pmc_clock_setup_in_xtal_12mhz_out_84mhz (void)
void pmc_clock_setup_in_rc_4mhz_out_84mhz (void)
Variables
uint32_t pmc_mck_frequency = 4000000
Default peripheral clock frequency after reset.
Function Documentation
pmc_clock_setup_in_rc_4mhz_out_84mhz()
void pmc_clock_setup_in_rc_4mhz_out_84mhz (void)
Definition at line 93 of file pmc.c.
References eefc_set_latency(), pmc_mck_frequency, pmc_mck_set_source(), and pmc_plla_config().
pmc_clock_setup_in_xtal_12mhz_out_84mhz()
void pmc_clock_setup_in_xtal_12mhz_out_84mhz (void)
Definition at line 78 of file pmc.c.
References eefc_set_latency(), pmc_mck_frequency, pmc_mck_set_source(), pmc_plla_config(), and pmc_xtal_enable().
pmc_mck_set_source()
void pmc_mck_set_source (enum mck_src src)
Definition at line 72 of file pmc.c.
Referenced by pmc_clock_setup_in_rc_4mhz_out_84mhz(), and pmc_clock_setup_in_xtal_12mhz_out_84mhz().
pmc_peripheral_clock_disable()
void pmc_peripheral_clock_disable (uint8_t pid)
Definition at line 59 of file pmc.c.
pmc_peripheral_clock_enable()
void pmc_peripheral_clock_enable (uint8_t pid)
Definition at line 45 of file pmc.c.
pmc_plla_config()
void pmc_plla_config (uint8_t mul, uint8_t div)
Definition at line 38 of file pmc.c.
Referenced by pmc_clock_setup_in_rc_4mhz_out_84mhz(), and pmc_clock_setup_in_xtal_12mhz_out_84mhz().
pmc_xtal_enable()
void pmc_xtal_enable (bool en, uint8_t startup_time)
Definition at line 26 of file pmc.c.
Referenced by pmc_clock_setup_in_xtal_12mhz_out_84mhz().
Variable Documentation
pmc_mck_frequency
uint32_t pmc_mck_frequency = 4000000
Default peripheral clock frequency after reset.
Definition at line 24 of file pmc.c.
Referenced by pmc_clock_setup_in_rc_4mhz_out_84mhz(), pmc_clock_setup_in_xtal_12mhz_out_84mhz(), and usart_set_baudrate().