libopencm3: flash_common_f.h File Reference
flash_common_f.h File Reference
#include <libopencm3/cm3/common.h>
Functions
void flash_clear_eop_flag (void)
Clear the End of OPeration flag.
void flash_clear_status_flags (void)
Clear all status flags.
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
Function Documentation
flash_clear_status_flags()
void flash_clear_status_flags (void)
Clear all status flags.
The number of bits can vary across families.
flash_wait_for_last_operation()
void flash_wait_for_last_operation (void)
Wait until Last Operation has Ended.
This loops indefinitely until an operation (write or erase) has completed by testing the busy flag
Referenced by flash_erase_all_sectors(), flash_erase_sector(), flash_program_byte(), flash_program_double_word(), flash_program_half_word(), flash_program_option_bytes(), and flash_program_word().